ALTER TABLE "Partner" ADD COLUMN application JSONB NOT NULL DEFAULT '{}', ADD COLUMN "reviewReason" TEXT, ADD COLUMN "submittedAt" TIMESTAMP(3);
ALTER TABLE "Document" ADD COLUMN "byteSize" INTEGER NOT NULL DEFAULT 0, ADD COLUMN "scanStatus" TEXT NOT NULL DEFAULT 'LEGACY_METADATA', ADD COLUMN "scanDetail" TEXT, ADD COLUMN "storageMode" TEXT NOT NULL DEFAULT 'fixture';
CREATE TABLE "Invitation" (
 id TEXT PRIMARY KEY, "companyId" TEXT NOT NULL, "partnerId" TEXT NOT NULL,
 email TEXT NOT NULL, "tokenHash" TEXT NOT NULL UNIQUE,
 "expiresAt" TIMESTAMP(3) NOT NULL, "acceptedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
