import {test,expect} from '@playwright/test';
import {signIn} from './auth';
import {nativeCoachWorkflow} from '../helpers/native-coach-workflow';
import {nativeHttp} from '../helpers/native-http';

test('Coach uses ordinary partner, catalogue, order, return and finance pages',async({page})=>{
 test.setTimeout(240000);
 await signIn(page,'admin@ati.demo');await page.goto('/operator/coach');
 await expect(page).toHaveURL(/\/operator\/partners$/);
 await expect(page.getByRole('link',{name:'Coach UAE walkthrough'})).toHaveCount(0);
 await page.getByRole('button',{name:'Invite a partner',exact:true}).click();
 await page.getByRole('button',{name:'Use fictional Coach UAE details'}).click();
 await expect(page.getByLabel('Trading name',{exact:true})).toHaveValue('Coach UAE');
 await expect(page.getByLabel('Invited email',{exact:true})).toHaveValue('admin@coachuae.demo');
 const transport=nativeHttp('http://127.0.0.1:3002');const admin=await transport.login('admin@ati.demo','Demo123!');
 const result=await nativeCoachWorkflow(transport,admin,{password:'CoachDemo123!'});
 await page.reload();await expect(page.getByRole('row').filter({hasText:'Coach UAE'})).toContainText('active');
 await page.getByRole('row').filter({hasText:'Coach UAE'}).getByRole('button',{name:'Review'}).click();
 await expect(page.getByRole('heading',{name:'Coach UAE',exact:true})).toBeVisible();
 await expect(page.locator('.launch-readiness')).not.toContainText('Action needed');
 await page.screenshot({path:test.info().outputPath('coach-native-partner.png'),fullPage:true});
 await page.goto('/operator/catalog/items');await expect(page.getByText('Tabby shoulder bag — black',{exact:true})).toBeVisible();
 await page.goto('/operator/catalog/imports');await expect(page.getByLabel('Coach sample location')).toBeVisible();
 await page.getByLabel('Coach sample location').selectOption(result.locationId);await expect(page.getByLabel('CSV content')).toHaveValue(/COACH-TABBY-BLK/);
 await page.goto('/operator/orders');await expect(page.getByLabel('Sample basket').getByRole('option',{name:'Coach UAE',exact:true})).toBeEnabled();
 await page.getByLabel('Search shipments').fill('Coach UAE');await expect(page.getByRole('row').filter({hasText:result.orderReference})).toContainText('Coach UAE Demo Warehouse');
 await page.goto('/operator/orders/'+result.shipmentId);await expect(page.getByRole('heading',{name:'Fulfilment workspace'})).toBeVisible();await expect(page.getByText('Coach UAE · Coach UAE Demo Warehouse',{exact:true})).toBeVisible();
 await page.goto('/operator/returns/'+result.returnId);await expect(page.locator('main')).toContainText('closed');
 await page.goto('/operator/settlements/'+result.statementId);await expect(page.locator('.statement-total')).toContainText('2,380.00');await expect(page.getByText('paid · simulated',{exact:true})).toBeVisible();
 await page.screenshot({path:test.info().outputPath('coach-native-statement.png'),fullPage:true});
 await page.goto('/login?next=/onboarding');await page.getByLabel('Email',{exact:true}).fill('admin@coachuae.demo');await page.getByLabel('Password',{exact:true}).fill('CoachDemo123!');await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(page).toHaveURL(/\/onboarding$/);await expect(page.locator('.journey-intro')).toContainText('Coach UAE');await page.screenshot({path:test.info().outputPath('coach-native-onboarding.png'),fullPage:true});
 await page.goto('/vendor/partners');await expect(page.getByRole('row').filter({hasText:'Coach UAE'})).toBeVisible();await expect(page.getByRole('row').filter({hasText:'Maison Azure'})).toHaveCount(0);
});
