ALTER TABLE "Location" ADD COLUMN "deliveryCities" TEXT[] NOT NULL DEFAULT ARRAY['Dubai']::TEXT[], ADD COLUMN "cutoffHour" INTEGER NOT NULL DEFAULT 18, ADD COLUMN "dailyCapacity" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Location" ADD CONSTRAINT location_routing_limits CHECK ("cutoffHour" BETWEEN 0 AND 24 AND "dailyCapacity" >= 0);
ALTER TABLE "Order" ADD COLUMN "payloadHash" TEXT NOT NULL DEFAULT 'legacy', ADD COLUMN "lines" JSONB NOT NULL DEFAULT '[]', ADD COLUMN "deliveryCity" TEXT NOT NULL DEFAULT 'Dubai', ADD COLUMN "routingPolicy" TEXT NOT NULL DEFAULT 'HYBRID_WATERFALL';
ALTER TABLE "FulfilmentLeg" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1, ADD COLUMN "requestedStatus" TEXT, ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
