import {describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {coachSteps} from '../../packages/simulation/coach-catalog';
import {loginDestination} from '../../apps/web/lib/login-destination';
import {startCoach,advanceCoach,coachStepDefaults,coachAvailable,coachTotals,coachCommand,type CoachRun,type CoachValues} from '../../packages/simulation/coach-engine';
const now='2026-09-30T10:00:00.000Z';
const fresh=()=>startCoach(randomUUID(),now);
function go(r:CoachRun,values:CoachValues={},fail=false){return advanceCoach(r,coachCommand.parse({commandId:randomUUID(),expectedVersion:r.version,step:coachSteps[r.cursor].id,values:{...coachStepDefaults(r),...values},fail}),now);}
function until(id:string,overrides:Record<string,CoachValues>={}){let r=fresh();while(coachSteps[r.cursor]?.id!==id){r=go(r,overrides[coachSteps[r.cursor].id]);if(r.status==='complete')throw Error('Missing step');}return r;}
describe('Coach UAE connected demo',()=>{
 it('keeps the requested Coach login destination without allowing external redirects',()=>{expect(loginDestination(false,'/operator/coach')).toBe('/operator/coach');for(const bad of ['https://example.test','//example.test','/operator//example.test','/operator/../login','/operator/coach?next=https://example.test'])expect(loginDestination(false,bad)).toBe('/operator/dashboard');expect(loginDestination(true,'/operator/coach')).toBe('/vendor/dashboard');});
 it('maps every workbook requirement exactly within 1–54 and gives every step a plain action',()=>{const ids=new Set(coachSteps.flatMap(s=>s.requirements));expect([...ids].sort((a,b)=>a-b)).toEqual(Array.from({length:54},(_,i)=>i+1));expect(new Set(coachSteps.map(s=>s.id)).size).toBe(coachSteps.length);expect(coachSteps.every(s=>s.action&&s.owner&&s.help&&s.result)).toBe(true);});
 it('carries the same collection, stock, returns and locked statement to the end',()=>{let r=fresh();while(r.status!=='complete')r=go(r);expect(r.cursor).toBe(coachSteps.length);expect(r.products).toHaveLength(5);expect(r.products.every(p=>p.visible&&p.approved&&p.published)).toBe(true);expect(r.legs.map(l=>l.state)).toEqual(['Delivered','Delivered','Delivered']);expect(r.products[0]).toMatchObject({onHand:11,reserved:0,damaged:0,safety:2});expect(r.products[2].onHand).toBe(12);expect(r.products[3].onHand).toBe(11);expect(r.products[4].onHand).toBe(11);expect(r.statement).toEqual({...coachTotals(r),locked:true});expect(r.statement?.sales).toBe('2670.00');expect(r.statement?.charges).toBe('35.00');expect(r.facts.financeReceived).toBe(r.statement?.payable);expect(r.facts.reportSource).toBe('This saved Coach journey');expect(r.profile.market).toBe('UAE');expect(r.history.filter(h=>h.status==='done')).toHaveLength(coachSteps.length);});
 it('keeps partner and reviewer pages separate',()=>{for(const id of ['apply','correct','import','stock','pack','inspect'])expect(coachSteps.find(s=>s.id===id)?.page).toBe('partner');for(const id of ['approve','catalogue-review','activate','refund','payout'])expect(coachSteps.find(s=>s.id===id)?.page).toBe('operator');});
 it('refuses skipped steps, stale updates and unexpected inputs',()=>{const r=fresh();expect(()=>advanceCoach(r,{commandId:randomUUID(),expectedVersion:1,step:'activate',values:{},fail:false},now)).toThrow('highlighted step');expect(()=>advanceCoach(r,{commandId:randomUUID(),expectedVersion:2,step:'invite',values:{email:'a@example.test'},fail:false},now)).toThrow('another tab');expect(()=>go(r,{admin:true})).toThrow('unexpected field');});
 it('does not consume stock in the safe launch test and cannot activate without visibility',()=>{const r=until('test');const before=structuredClone(r.products);const tested=go(r);expect(tested.products).toEqual(before);expect(tested.facts.launchStockConsumed).toBe(0);tested.products[0].visible=false;expect(()=>go(tested)).toThrow('launch checklist');});
 it('rejects invalid documents, duplicates, mapping and below-floor prices',()=>{expect(()=>go(until('apply'),{documents:false})).toThrow('sample documents');expect(()=>go(until('correct'),{expiry:'2020-01-01'})).toThrow('expiry');expect(()=>go(until('validate'),{removeDuplicate:false})).toThrow('duplicate');expect(()=>go(until('validate'),{colourMapping:'Material'})).toThrow('Colour');const r=until('promotion');expect(()=>go(r,{discount:50})).toThrow('minimum');expect(go(r,{discount:50,override:true}).facts.priceException).toBe(true);});
 it('routes trusted lower-value products to automatic approval and retains human control',()=>{const r=go(until('catalogue-review'));expect(r.products[0].approval).toContain('manual');expect(r.products[2].approval).toContain('Automatic');expect(()=>go(until('catalogue-review'),{manualReview:false})).toThrow('above');});
 it('protects stock, packed quantities, and paused order completion',()=>{const r=until('order');expect(()=>go(r,{quantity:99})).toThrow('not enough');const ordered=go(r);expect(coachAvailable(ordered.products[0])).toBe(8);expect(()=>go(ordered,{packed:3})).toThrow('Packed quantities');const paused=go(go(ordered));expect(paused.partnerStatus).toBe('Paused');expect(coachAvailable(paused.products[0],false)).toBe(0);const restored=go(go(paused));expect(restored.partnerStatus).toBe('Active');expect(coachAvailable(restored.products[0])).toBe(8);});
 it('rejects wrong collection codes without changing any stock',()=>{const r=until('collection'),snapshot=JSON.stringify(r);expect(()=>go(r,{code:'0000'})).toThrow('not been handed over');expect(JSON.stringify(r)).toBe(snapshot);});
 it('enforces return windows and quarantines damaged stock even when refund is overridden',()=>{expect(()=>go(until('return'),{day:31})).toThrow('outside');expect(()=>go(until('inspect'),{receiptDay:50})).toThrow('operational period');const r=go(until('inspect'),{condition:'Damaged'});expect(r.products[0].damaged).toBe(1);expect(coachAvailable(r.products[0])).toBe(8);expect(()=>go(r)).toThrow('damaged');const refunded=go(r,{override:true});expect(refunded.products[0].damaged).toBe(1);expect(refunded.facts.refundAmount).toBe('1620.00');});
 it('declined replacement never consumes replacement stock or adds a replacement sale',()=>{const r=until('exchange'),before=r.products[3].onHand;const declined=go(r,{payment:'Declined'});expect(declined.products[3].onHand).toBe(before);expect(declined.ledger.some(e=>e.id==='replacement-sale')).toBe(false);expect(declined.facts.exchangeState).toContain('declined');});
 it('failed updates preserve facts and retry uses the same step key',()=>{const r=until('publish'),failed=go(r,{},true);expect(failed.products).toEqual(r.products);expect(failed.cursor).toBe(r.cursor);expect(failed.status).toBe('needs_attention');const retried=go(failed);expect(retried.history.at(-1)?.key).toBe(failed.history.at(-1)?.key);expect(retried.products.every(p=>p.published)).toBe(true);});
 it('duplicate commands have one effect and reject a reused key with changed inputs',()=>{const r=until('order'),c=coachCommand.parse({expectedVersion:r.version,commandId:randomUUID(),step:'order',values:coachStepDefaults(r)});const next=advanceCoach(r,c,now);expect(advanceCoach(next,c,now)).toBe(next);expect(()=>advanceCoach(next,{...c,values:{...c.values,quantity:3}},now)).toThrow('different details');expect(next.ledger).toHaveLength(2);});
 it('reconciliation never changes the locked statement',()=>{const r=until('reconcile'),locked=structuredClone(r.statement);const next=go(r,{actualFx:1.2,importTax:15});expect(next.statement).toEqual(locked);expect(next.facts.importTaxAdjustment).toBe('15.00');expect(Number(next.facts.conversionDifference)).toBeGreaterThan(0);});
});
