packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  esbuild: true
  sharp: true
  msgpackr-extract: false
  '@embedded-postgres/darwin-arm64': true
  '@embedded-postgres/linux-x64': false
