import {beforeAll,afterAll,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import type {FastifyInstance} from 'fastify';
import {db} from '../../packages/db/client';
import {hashPassword} from '../../packages/auth/security';
import {createServer} from '../../apps/api/src/server';
import {coachSteps} from '../../packages/simulation/coach-catalog';
import {coachStepDefaults,type CoachRun} from '../../packages/simulation/coach-engine';
const id=`coach-${randomUUID()}`;let app:FastifyInstance;let run:CoachRun;
const sessions:Record<string,Record<string,string>>={};
beforeAll(async()=>{
 const url=new URL(process.env.DATABASE_URL??'');if(!['localhost','127.0.0.1'].includes(url.hostname)||url.pathname!=='/ecs_test')throw Error('Isolated local ecs_test required');
 for(const [name,role,companyId] of [['admin','ATI_SUPER_ADMIN',id],['other','ATI_SUPER_ADMIN',id],['foreign','ATI_SUPER_ADMIN',`${id}-other`],['vendor','VENDOR_ADMIN',id]])await db.user.create({data:{id:`${id}-${name}`,name,email:`${id}-${name}@example.test`,companyId,role,partnerId:name==='vendor'?`${id}-partner`:null,passwordHash:hashPassword('Demo123!')}});
 app=await createServer({verifyResponseContracts:true});
 for(const name of ['admin','other','foreign','vendor']){const r=await app.inject({method:'POST',url:'/api/v1/auth/login',payload:{email:`${id}-${name}@example.test`,password:'Demo123!'}});expect(r.statusCode,r.body).toBe(200);sessions[name]={cookie:`${r.cookies[0].name}=${r.cookies[0].value}`,'x-csrf-token':r.json().csrfToken};}
});
afterAll(async()=>{await app?.close();await db.$disconnect();});
it('requires login, ATI demo access and CSRF',async()=>{expect((await app.inject('/api/v1/coach-journeys')).statusCode).toBe(401);expect((await app.inject({url:'/api/v1/coach-journeys',headers:sessions.vendor})).statusCode).toBe(403);expect((await app.inject({url:'/api/v1/coach-journeys',method:'POST',headers:{cookie:sessions.admin.cookie},payload:{requestId:randomUUID()}})).statusCode).toBe(403);});
it('saves a private new journey once and excludes other users and companies',async()=>{const requestId=randomUUID();for(let n=0;n<2;n++){const r=await app.inject({method:'POST',url:'/api/v1/coach-journeys',headers:sessions.admin,payload:{requestId}});expect(r.statusCode,r.body).toBe(200);run=r.json().run;expect(run.version).toBe(1);}expect(await db.auditEvent.count({where:{entityId:`coach:${requestId}`}})).toBe(1);for(const name of ['other','foreign']){expect((await app.inject({url:`/api/v1/coach-journeys/${requestId}`,headers:sessions[name]})).statusCode).toBe(404);expect((await app.inject({url:'/api/v1/coach-journeys',headers:sessions[name]})).json().runs).toEqual([]);}});
it('completes and reloads the whole connected journey without altering operational tables',async()=>{const before=await Promise.all([db.partner.count(),db.order.count(),db.outbox.count()]);while(run.status!=='complete'){const payload={expectedVersion:run.version,commandId:randomUUID(),step:coachSteps[run.cursor].id,values:coachStepDefaults(run)};const r=await app.inject({method:'POST',url:`/api/v1/coach-journeys/${run.id}/commands`,headers:sessions.admin,payload});expect(r.statusCode,r.body).toBe(200);run=r.json().run;const duplicate=await app.inject({method:'POST',url:`/api/v1/coach-journeys/${run.id}/commands`,headers:sessions.admin,payload});expect(duplicate.statusCode,duplicate.body).toBe(200);expect(duplicate.json().run.version).toBe(run.version);}const saved=await app.inject({url:`/api/v1/coach-journeys/${run.id}`,headers:sessions.admin});expect(saved.json().run).toEqual(run);expect(run.statement?.sales).toBe('2670.00');expect(await Promise.all([db.partner.count(),db.order.count(),db.outbox.count()])).toEqual(before);},90000);
it('rejects foreign mutations and concurrent stale actions',async()=>{const r=await app.inject({method:'POST',url:'/api/v1/coach-journeys',headers:sessions.admin,payload:{requestId:randomUUID()}});const fresh=r.json().run as CoachRun;const payload={expectedVersion:1,commandId:randomUUID(),step:'invite',values:coachStepDefaults(fresh)};expect((await app.inject({method:'POST',url:`/api/v1/coach-journeys/${fresh.id}/commands`,headers:sessions.foreign,payload})).statusCode).toBe(404);const results=await Promise.all([1,2].map(()=>app.inject({method:'POST',url:`/api/v1/coach-journeys/${fresh.id}/commands`,headers:sessions.admin,payload:{...payload,commandId:randomUUID()}})));expect(results.map(r=>r.statusCode).sort()).toEqual([200,409]);});
