'use client';
import {useEffect,useState} from 'react';
import {ShieldCheck,Plus,LockKeyhole} from 'lucide-react';
import {api,type Partner,type User} from '../lib/api';
type Right={id:string;brand:string;market:string;categories:string[];status:string;effectiveState:string;validFrom:string;validUntil:string;evidence:string;reason:string;version:number};
type Product={id:string;sku:string;brand:string;category:string;market:string;status:string;authorized:boolean};
type Registry={now:string;items:Right[];products:Product[]};
const actions:Record<string,string[]>={DRAFT:['approve','reject'],APPROVED:['pause','suspend','revoke'],PAUSED:['resume','suspend','revoke'],SUSPENDED:['resume','revoke']};
const brandNames:Record<string,string>={br_maz:'Maison Azure',br_lum:'Lumera Beauty',br_nrh:'Northline Home',br_orb:'Orbit Footwear'};
export function BrandRights({user,refreshToken=0}:{user:User;refreshToken?:number}){
 const[partners,setPartners]=useState<Partner[]>([]),[id,setId]=useState(''),[registry,setRegistry]=useState<Registry|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reasons,setReasons]=useState<Record<string,string>>({});
 const[form,setForm]=useState({brand:'',market:'AE',categories:'',validFrom:'',validUntil:'2027-12-31T00:00',evidence:'',reason:''});
 const write=['ATI_SUPER_ADMIN','ATI_PARTNER_MANAGER'].includes(user.role);
 useEffect(()=>{void api<{items:Partner[]}>('/partners?limit=100').then(r=>{setPartners(r.items);setId(r.items.find(p=>p.id==='vnd_maz')?.id??r.items[0]?.id??'');}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{setOpen(false);},[id]);
 useEffect(()=>{let cancelled=false;setRegistry(null);setError('');setNotice('');if(id)void api<Registry>(`/partners/${id}/brand-rights`).then(r=>{if(!cancelled)setRegistry(r);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[id,refreshToken]);
 async function reload(){setRegistry(await api<Registry>(`/partners/${id}/brand-rights`));}
 async function save(){setBusy(true);setError('');try{await api(`/partners/${id}/brand-rights`,{...form,categories:form.categories.split('\n').map(c=>c.trim()).filter(Boolean),validFrom:new Date(form.validFrom+'Z').toISOString(),validUntil:new Date(form.validUntil+'Z').toISOString()});await reload();setOpen(false);setNotice('Draft saved. A separate ATI review is required before it grants any selling rights.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function command(r:Right,action:string){setBusy(true);setError('');try{await api(`/brand-rights/${r.id}/commands`,{action,expectedVersion:r.version,reason:reasons[r.id]});await reload();setNotice('Decision recorded. New-order eligibility is recalculated immediately. Any changed inventory availability is queued to Fynd and SFCC; existing shipments are unchanged.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function draft(){setForm({brand:registry?.products[0]?.brand??'',market:partners.find(p=>p.id===id)?.markets.find(m=>user.markets.includes(m))??'AE',categories:'',validFrom:registry?.now.slice(0,16)??'',validUntil:'2027-12-31T00:00',evidence:'',reason:''});setOpen(true);}
 return <div className="commercial-workbench rights-workbench"><section className="panel commercial-intro"><div><ShieldCheck size={24}/><h2>Brand authorization registry</h2><p>The right brand. The right market. The right categories. Review the scope before a partner’s products become available for new orders.</p></div><label>Partner<select disabled={busy} value={id} onChange={e=>setId(e.target.value)}>{partners.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select></label>{write&&<button className="primary" disabled={!registry||busy} onClick={draft}><Plus size={16}/>New authorization</button>}</section>
 {error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="journey-notice" role="status">{notice}</div>}
 <div className="rights-explainer"><span><b>01</b> Record scope & evidence</span><span><b>02</b> ATI reviews authorization</span><span><b>03</b> Eligible availability syncs</span></div>
 <p className="footnote">Demo clock: {registry?.now.slice(0,19).replace('T',' ')} UTC · Fictional governance records, not verification of a legal licence. Paused, suspended, revoked and expired rights stop new availability; existing orders can still be fulfilled.</p>
 {open&&<section className="panel commercial-editor"><div className="panel-title"><h2>Draft authorization</h2><button className="text-button" disabled={busy} onClick={()=>setOpen(false)}>Cancel draft</button></div><p className="footnote">Use the canonical brand ID shown in the catalogue. A category path includes its descendants; wildcards are not accepted. One reviewed authorization per brand/market period prevents conflicting grants.</p><form onSubmit={e=>{e.preventDefault();void save();}}><div className="commercial-grid"><label>Canonical brand ID<input required list="rights-brand-ids" value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})}/><datalist id="rights-brand-ids">{[...new Set(registry?.products.map(p=>p.brand))].map(b=><option key={b} value={b}>{brandNames[b]??b}</option>)}</datalist></label><label>Market<select value={form.market} onChange={e=>setForm({...form,market:e.target.value})}>{partners.find(p=>p.id===id)?.markets.filter(m=>user.markets.includes(m)).map(m=><option key={m}>{m}</option>)}</select></label><label>Evidence reference<input required minLength={5} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})} placeholder="Document or distributor agreement reference"/></label><label>Effective from (UTC)<input required placeholder="YYYY-MM-DDTHH:mm" value={form.validFrom} onChange={e=>setForm({...form,validFrom:e.target.value})}/></label><label>Effective until, exclusive (UTC)<input required placeholder="YYYY-MM-DDTHH:mm" value={form.validUntil} onChange={e=>setForm({...form,validUntil:e.target.value})}/></label><label>Creation reason<input required minLength={5} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label></div><label>Authorized category paths — one per line<textarea required rows={3} value={form.categories} onChange={e=>setForm({...form,categories:e.target.value})} placeholder={'Women/Dresses\nWomen/Handbags'}/></label><button className="primary" disabled={busy}>Save draft for review</button></form></section>}
 <section className="panel commercial-history"><div className="panel-title"><h2>Authorizations</h2><span>{registry?.items.length??0} records</span></div>{registry?.items.map(r=><article key={r.id}><div className="commercial-version"><strong>{r.market}</strong><b>{brandNames[r.brand]??r.brand}</b><span className={`badge ${r.effectiveState==='EFFECTIVE'?'green':'amber'}`}>{r.effectiveState}</span><small>{r.brand} · Revision {r.version}</small></div><p>{r.validFrom.slice(0,16).replace('T',' ')} → {r.validUntil.slice(0,16).replace('T',' ')} UTC</p><div className="commercial-tags">{r.categories.map(c=><span key={c}>{c}</span>)}</div><p>Evidence: {r.evidence}</p><p>Latest decision: {r.reason}</p>{r.status!=='DRAFT'&&<small className="locked-note"><LockKeyhole size={13}/>Reviewed scope is immutable. Create a new record for changed scope or renewal.</small>}{write&&actions[r.status]&&<div className="rights-actions"><label>Decision reason for {r.brand}<input aria-label={`Decision reason ${r.id}`} value={reasons[r.id]??''} onChange={e=>setReasons({...reasons,[r.id]:e.target.value})}/></label><div>{actions[r.status].map(action=><button className={action==='approve'||action==='resume'?'primary':'button'} key={action} disabled={busy||(reasons[r.id]??'').trim().length<5} onClick={()=>void command(r,action)}>{action==='revoke'?'Revoke permanently':action[0].toUpperCase()+action.slice(1)}</button>)}</div></div>}</article>)}{registry&&!registry.items.length&&<div className="empty"><ShieldCheck size={32}/><h3>No selling rights approved</h3><p>Create a scoped authorization and complete ATI review before catalogue publication.</p></div>}</section>
 <section className="panel commercial-history"><div className="panel-title"><h2>Catalogue coverage</h2><span>{registry?.products.filter(p=>p.authorized).length??0} / {registry?.products.length??0} covered</span></div><p className="footnote">Coverage is a brand-right check only. Partner, publication, location, inventory and commercial gates still apply.</p><div className="rights-table"><table><thead><tr><th>SKU</th><th>Category / market</th><th>Rights coverage</th></tr></thead><tbody>{registry?.products.map(p=><tr key={p.id}><td><b>{p.sku}</b><small>{brandNames[p.brand]??p.brand}</small></td><td>{p.category}<small>{p.market}</small></td><td><span className={`badge ${p.authorized?'green':'amber'}`}>{p.authorized?'Authorized':'Blocked'}</span></td></tr>)}</tbody></table></div></section></div>;
}
