'use client';
import {useState} from 'react';
import {api} from '../lib/api';
export type Mapping={fields:Record<string,string>;ignoredHeaders:string[];values:{field:string;from:string;to:string}[]};
type Preview={sourceHeaders:string[];mapping:Mapping;missingFields:string[];unmappedHeaders:string[];numericIssues:string[];ready:boolean;rowCount:number;sampleRows:{number:number;raw:Record<string,string>;canonical:Record<string,string>}[]};
export function CatalogFieldMapping({payload,fields,required,labels,onReady}:{payload:object;fields:string[];required:string[];labels:Record<string,string>;onReady:(mapping:Mapping|null)=>void}){
 const[preview,setPreview]=useState<Preview|null>(null),[mapping,setMapping]=useState<Mapping|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[dirty,setDirty]=useState(false);
 function change(next:Mapping){setMapping(next);setDirty(true);onReady(null);}
 async function inspect(){setBusy(true);setError('');onReady(null);try{const next=await api<Preview>('/catalog/imports/preview',{...payload,...(mapping?{mapping}:{})});setPreview(next);setMapping(next.mapping);setDirty(false);onReady(next.ready?next.mapping:null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="catalog-form" aria-label="Source field mapping"><h3>Map your source fields</h3><p className="footnote">Preview only — no batch, product or stock is saved. Match vendor columns to ATI fields, explicitly ignore unused columns and review exact value conversions. Business validation follows when staging.</p>
 <button className="button" disabled={busy} onClick={()=>void inspect()}>{busy?'Reading source…':preview?'Refresh mapping preview':'Preview source columns'}</button>
 {error&&<p role="alert" className="error">{error}</p>}
 {mapping&&preview&&<><div className="import-row-form">{fields.map(field=><label key={field}>{labels[field]??field}{required.includes(field)?' *':''}<select aria-label={`Map ${field}`} disabled={busy} value={mapping.fields[field]??''} onChange={e=>{const next={...mapping.fields};if(e.target.value)next[field]=e.target.value;else delete next[field];change({...mapping,fields:next,ignoredHeaders:mapping.ignoredHeaders.filter(h=>h!==e.target.value)});}}><option value="">Not mapped</option>{preview.sourceHeaders.map(h=><option key={h} value={h}>{h}</option>)}</select></label>)}</div>
 <details><summary>Unused columns and exact value conversions</summary><p>Unused columns must be acknowledged. They remain in the private original source, not in the product.</p>{preview.sourceHeaders.filter(h=>!Object.values(mapping.fields).includes(h)).map(h=><label className="import-exclude" key={h}><input type="checkbox" disabled={busy} checked={mapping.ignoredHeaders.includes(h)} onChange={e=>change({...mapping,ignoredHeaders:e.target.checked?[...mapping.ignoredHeaders,h]:mapping.ignoredHeaders.filter(v=>v!==h)})}/>Ignore {h}</label>)}
 <p>Values are trimmed and matched exactly once. No inferred categories, units or translations.</p>{mapping.values.map((v,i)=><div className="import-row-form" key={i}><label>Canonical field<select aria-label={`Conversion field ${i+1}`} value={v.field} disabled={busy} onChange={e=>change({...mapping,values:mapping.values.map((r,n)=>n===i?{...r,field:e.target.value}:r)})}>{['category','colour','size','currency','country_of_origin'].map(f=><option key={f}>{f}</option>)}</select></label><label>Source value<input aria-label={`Source value ${i+1}`} value={v.from} disabled={busy} onChange={e=>change({...mapping,values:mapping.values.map((r,n)=>n===i?{...r,from:e.target.value}:r)})}/></label><label>ATI value<input aria-label={`ATI value ${i+1}`} value={v.to} disabled={busy} onChange={e=>change({...mapping,values:mapping.values.map((r,n)=>n===i?{...r,to:e.target.value}:r)})}/></label><button className="text-button" disabled={busy} onClick={()=>change({...mapping,values:mapping.values.filter((_,n)=>n!==i)})}>Remove conversion {i+1}</button></div>)}<button className="button" disabled={busy||mapping.values.length>=100} onClick={()=>change({...mapping,values:[...mapping.values,{field:'category',from:'',to:''}]})}>Add value conversion</button></details>
 {dirty?<p role="status">Mapping changed. Refresh the preview before saving.</p>:<><p role="status">{preview.ready?'Mapping ready':'Mapping incomplete'} · {preview.rowCount} source rows · first row shown below</p>{preview.missingFields.length>0&&<p className="error">Required fields: {preview.missingFields.join(', ')}</p>}{preview.unmappedHeaders.length>0&&<p className="error">Map or ignore: {preview.unmappedHeaders.join(', ')}</p>}{preview.numericIssues.length>0&&<p className="error">Save these identifier/text columns as text in Excel: {preview.numericIssues.join(', ')}</p>}
 <div className="import-table"><table><thead><tr><th>ATI field</th><th>Source column</th><th>Source row 2</th><th>Mapped row 2</th></tr></thead><tbody>{fields.filter(f=>mapping.fields[f]).map(f=><tr key={f}><td>{labels[f]??f}</td><td>{mapping.fields[f]}</td><td>{preview.sampleRows[0]?.raw[mapping.fields[f]]}</td><td dir={f==='title_ar'?'rtl':undefined}>{preview.sampleRows[0]?.canonical[f]}</td></tr>)}</tbody></table></div></>}
 </>}
 </section>;
}
