'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Upload,FileSpreadsheet,AlertCircle,CheckCircle2,ArrowLeft,RefreshCw,Save} from 'lucide-react';
import {api,type User} from '../lib/api';
import {CatalogFieldMapping,type Mapping} from './catalog-field-mapping';
import {coachCatalogue} from '../../../seed/coach-native';
type Issue={code:string;field:string;message:string};
type Row={number:number;input:Record<string,string>;issues:Issue[];warnings:Issue[];excluded?:boolean;reason?:string;floor:string|null;productId?:string;duplicateCandidates?:{id:string;sku:string;title:string}[];duplicateApproval?:{reason:string}};
type Batch={id:string;fileName:string;source:string;checksum:string;status:string;version:number;rows:Row[];createdAt:string;mapping:(Mapping&{version:1})|null};
type Metadata={fields:string[];requiredHeaders:string[];assets:string[];brands:{id:string;name:string}[];partners:{id:string;code:string;displayName:string}[];locations:{id:string;code:string;name:string;partnerId:string|null}[]};
const labels:Record<string,string>={partner_code:'Partner code',brand:'Brand name or ID',vendor_sku:'Vendor SKU',gtin:'GTIN',parent_sku:'Parent SKU',title_en:'English title',title_ar:'Arabic title',category:'Category path',colour:'Colour',size:'Size',list_price:'List price',selling_price:'Selling price',currency:'Currency',image_url:'Image asset',location_code:'Location code',quantity:'Opening quantity',material:'Material',country_of_origin:'Country of origin',skin_type:'Skin type',finish:'Finish',scent:'Scent'};
export function CatalogImports({user,root,id,refreshToken}:{user:User;root:string;id?:string;refreshToken:number}){
 const[meta,setMeta]=useState<Metadata|null>(null),[history,setHistory]=useState<Batch[]>([]),[batch,setBatch]=useState<Batch|null>(null),[csv,setCsv]=useState(''),[fileName,setFileName]=useState('catalogue.csv'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[editing,setEditing]=useState<Row|null>(null),[reason,setReason]=useState(''),[filter,setFilter]=useState('all'),[key,setKey]=useState('');
 const moderator=['ATI_SUPER_ADMIN','ATI_CATALOG_MODERATOR'].includes(user.role);
 const[source,setSource]=useState<'CSV'|'XLSX'>('CSV'),[base64,setBase64]=useState('');
 const[mapping,setMapping]=useState<Mapping|null>(null);
 const[mappingKey,setMappingKey]=useState('');
 const allowed=moderator||['VENDOR_ADMIN','VENDOR_CATALOG_MANAGER'].includes(user.role);
 async function load(){try{const [m,h]=await Promise.all([api<Metadata>('/catalog/imports/metadata'),api<{items:Batch[]}>('/catalog/imports')]);setMeta(m);setHistory(h.items);if(id)setBatch(await api<Batch>(`/catalog/imports/${id}`));else setBatch(null);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{if(allowed)void load();},[id,refreshToken]);
 async function perform(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function updateSource(value:string,name:string){setSource('CSV');setBase64('');setCsv(value);setFileName(name);setKey(crypto.randomUUID());setMapping(null);}
 async function readFile(file?:File){
  if(!file)return;
  if(file.size>262144||!(/\.(csv|xlsx)$/i.test(file.name))){setError('Choose a CSV or XLSX file up to 256 KB. Legacy XLS, macros and SFTP are not supported.');return;}
  await perform(async()=>{
   if(/\.xlsx$/i.test(file.name)){
    const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);
    setBase64(btoa(binary));setSource('XLSX');setCsv('');setFileName(file.name);setKey(crypto.randomUUID());setMapping(null);
   }else updateSource(await file.text(),file.name);
  });
 }
 const included=batch?.rows.filter(r=>!r.excluded)??[],blocked=included.filter(r=>r.issues.length),valid=included.length-blocked.length;
 const shown=batch?.rows.filter(r=>filter==='all'||filter==='errors'&&!r.excluded&&r.issues.length||filter==='ready'&&!r.excluded&&!r.issues.length||filter==='excluded'&&r.excluded)??[];
 if(!allowed)return <div className="error">Your role cannot manage catalogue imports.</div>;
 return <div className="catalog-imports">
  {error&&<div role="alert" className="error">{error}</div>}{notice&&<div role="status" className="success-note">{notice}</div>}
  <div className="import-intro"><FileSpreadsheet size={28}/><div><h2>{batch?batch.fileName:'Bring your assortment into ECS'}</h2><p>Validate first. Correct every row. Submit for ATI moderation.</p></div><span className="badge amber">{batch?batch.status.replaceAll('_',' ').toLowerCase():'CSV + Excel + REST API'}</span></div>
  <ol className="import-steps"><li className={!batch?'current':''}>1 <span>Upload, map & stage</span></li><li className={batch?.status==='STAGED'?'current':''}>2 <span>Resolve validation</span></li><li className={batch?.status==='SUBMITTED'?'current':''}>3 <span>Submit for review</span></li></ol>
  <div className="import-actions"><a className="button" href="/api/v1/catalog/imports/template" download>Download CSV template</a><a className="button" href="/templates/ecs-catalogue-template.xlsx" download>Download Excel template</a>{batch?.status==='STAGED'&&<a className="button" href={`/api/v1/catalog/imports/${batch.id}/errors.csv`} download>Download validation report</a>}</div>
  {!batch&&!id&&<><section className="panel import-upload"><div>
   {meta?.partners.filter(p=>p.displayName==='Coach UAE').map(p=><div className="review-feedback" key={p.id}><b>Coach UAE sample collection</b><p>Three fictional handbags. Uses this partner’s real record and location. Review and submit through the same checks as every import.</p><label>Coach fulfilment location<select aria-label="Coach sample location" defaultValue="" onChange={e=>{if(!e.target.value)return;const rows=coachCatalogue(p.code,e.target.value),fields=meta.fields;updateSource(fields.join(',')+'\n'+rows.map(row=>fields.map(f=>'"'+String((row as Record<string,string>)[f]??'').replaceAll('"','""')+'"').join(',')).join('\n'),'coach-uae-collection.csv');}}><option value="">Choose location to fill the sample file</option>{meta.locations.filter(l=>l.partnerId===p.id).map(l=><option value={l.code} key={l.id}>{l.name}</option>)}</select></label><small>Create and prepare Coach’s location first. Re-importing existing product codes is blocked.</small></div>)}
   <h3>Upload your product catalogue</h3><p>CSV or Excel · Up to 100 products · 256 KB · AE / AED</p>
   <label className="import-drop"><Upload size={25}/><strong>Choose a CSV or Excel file</strong><span>Use the templates above to keep your columns consistent</span><input type="file" aria-label="Catalogue file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" disabled={busy} onChange={e=>{void readFile(e.target.files?.[0]);e.target.value='';}}/></label>
   <label className="import-label">File name<input value={fileName} onChange={e=>{setFileName(e.target.value);setKey(crypto.randomUUID());setMapping(null);}}/></label>
   {source==='XLSX'?<div className="review-feedback" role="status"><b>Excel workbook selected</b><p>{fileName} is ready for server-side validation. Nothing has been imported yet.</p><button className="text-button" disabled={busy} onClick={()=>updateSource('','catalogue.csv')}>Remove file and use CSV</button></div>:<label className="import-label">Or paste CSV content<textarea aria-label="CSV content" spellCheck={false} value={csv} onChange={e=>updateSource(e.target.value,fileName)} placeholder={meta?.requiredHeaders.join(',')}/></label>}
  </div><aside><h3>Before you upload</h3><p>This is a <b>create-only</b> workflow. Existing SKUs are never overwritten. Products and opening stock are created only when you submit a valid batch.</p><h4>Required columns</h4><code>{meta?.requiredHeaders.join(', ')}</code><h4>Category-specific columns</h4><code>material, country_of_origin, skin_type, finish, scent</code><h4>Excel checklist</h4><p>Use one visible sheet named <b>Catalogue</b>, with headers in row 1 and consecutive product rows below. Paste values, not formulas. Unmerge cells and unhide rows and columns.</p><p>Store GTINs, SKUs and other identifiers as text to retain leading zeros. Prices and quantities can be plain numbers. For CSV, quote values containing commas.</p><details><summary>Your partner & location codes</summary>{meta?.partners.map(p=><div className="import-code" key={p.id}><b>{p.code} · {p.displayName}</b>{meta.locations.filter(l=>l.partnerId===p.id).map(l=><small key={l.id}>{l.code} · {l.name}</small>)}</div>)}</details><details><summary>Available local demo images</summary>{meta?.assets.map(a=><code key={a}>{a}</code>)}</details><p className="footnote">SFTP, commerce-platform connectors and remote media ingestion remain pending. All supported sources share staged validation. No direct Fynd write occurs here.</p></aside></section><section className="panel source-mapping-panel">
   {!!meta&&!!(source==='XLSX'?base64:csv.trim())&&<CatalogFieldMapping key={key} payload={{fileName,requestKey:key,...(source==='XLSX'?{source,base64}:{source,content:csv})}} fields={meta.fields} required={meta.requiredHeaders} labels={labels} onReady={m=>{setMapping(m);setMappingKey(key);}}/>}
   <button className="primary" disabled={busy||!mapping||mappingKey!==key||!(source==='XLSX'?base64:csv.trim())} onClick={()=>void perform(async()=>{const saved=await api<Batch>('/catalog/imports',{fileName,requestKey:key||crypto.randomUUID(),mapping,...(source==='XLSX'?{source,base64}:{source,content:csv})});location.href=`${root}/catalog/imports/${saved.id}`;})}>{busy?'Validating…':'Validate and save batch'}</button>
</section><section className="panel"><h3>Recent imports</h3>{history.length?<div className="import-history">{history.map(b=><Link key={b.id} href={`${root}/catalog/imports/${b.id}`}><FileSpreadsheet size={20}/><div><b>{b.fileName}</b><small>{b.source} · {new Date(b.createdAt).toLocaleString()}</small></div><span className="badge amber">{b.status.toLowerCase()}</span></Link>)}</div>:<p className="muted">No imports in your permitted workspace yet.</p>}</section></>}
  {id&&!batch&&!error&&<p>Loading saved import…</p>}
  {batch&&<><div className="import-actions"><Link href={`${root}/catalog/imports`} className="back-link"><ArrowLeft size={15}/> All imports</Link><button className="button" disabled={busy} onClick={()=>void perform(async()=>{await load();setNotice('Validation refreshed against current permissions, rights and catalogue.');})}><RefreshCw size={14}/> Revalidate</button></div><div className="import-counts"><div><b>{batch.rows.length}</b><span>Source rows</span></div><div><b>{blocked.length}</b><span>Need correction</span></div><div><b>{valid}</b><span>{batch.status==='SUBMITTED'?'Submitted':'Ready for review'}</span></div><div><b>{batch.rows.length-included.length}</b><span>Excluded</span></div></div>
   {batch.mapping&&<details className="panel"><summary>Retained source mapping · version {batch.mapping.version}</summary><p>Mapping and original source are immutable. Row corrections are separately audited.</p><div className="import-table"><table><thead><tr><th>ATI field</th><th>Source column</th></tr></thead><tbody>{Object.entries(batch.mapping.fields).map(([f,h])=><tr key={f}><td>{labels[f]??f}</td><td>{h}</td></tr>)}</tbody></table></div><p>Ignored: {batch.mapping.ignoredHeaders.join(', ')||'None'}</p>{batch.mapping.values.map((v,i)=><p key={i}>{v.field}: {v.from} → {v.to}</p>)}</details>}
   {batch.status==='SUBMITTED'?<div className="success-note"><CheckCircle2 size={17}/> {included.length} products created in review. Media approval and ERP → Fynd / SFCC acknowledgements are still required. Stock is not sellable.</div>:<p className="import-help">Correct or exclude blocked rows. ATI owns price-floor policies; vendors cannot override them. Validation runs again inside the submission transaction.</p>}
   <section className="panel import-results"><div className="import-tabs">{[['all','All rows'],['errors','Needs correction'],['ready','Ready'],['excluded','Excluded']].map(([v,l])=><button key={v} className={filter===v?'selected':''} onClick={()=>setFilter(v)}>{l}</button>)}</div><div className="import-table"><table><thead><tr><th>Row / product</th><th>Partner / price</th><th>Validation</th><th>Action</th></tr></thead><tbody>{shown.map(row=><tr key={row.number} className={row.excluded?'excluded':''}><td><small>ROW {row.number} · {row.input.vendor_sku||'No SKU'}</small><b>{row.input.title_en||'Untitled product'}</b><small lang="ar" dir="rtl">{row.input.title_ar||'Arabic title missing'}</small></td><td>{row.input.partner_code}<small>{row.input.currency} {row.input.selling_price}</small>{row.floor&&<small>Operator floor: {row.floor}</small>}</td><td>{row.excluded?<><span className="badge amber">Excluded</span><small>{row.reason}</small></>:row.issues.length?<><span className="badge red">{row.issues.length} issues</span><small>{row.issues.slice(0,2).map(i=>i.message).join(' · ')}</small>{row.issues.length>2&&<small>+{row.issues.length-2} more</small>}</>:<><span className="badge green">{row.productId?'In review':'Validated'}</span><small>Human media review pending</small></>}</td><td>{row.productId?<Link className="text-button" href={`${root}/catalog/items/${row.productId}`}>Review product →</Link>:batch.status==='STAGED'?<button className="text-button" disabled={busy} onClick={()=>{setEditing(structuredClone(row));setReason('');}}>Inspect & correct</button>:<small>Source row retained</small>}</td></tr>)}</tbody></table>{!shown.length&&<p className="import-help">No rows match this filter.</p>}</div></section>
   {batch.status==='STAGED'&&<div className="import-submit"><div><b>{valid} of {included.length} included rows ready</b><p>Submission creates products in review. It does not approve or publish them.</p></div><button className="primary" disabled={busy||blocked.length>0||included.length===0} onClick={()=>void perform(async()=>{setBatch(await api<Batch>(`/catalog/imports/${batch.id}/submit`,{expectedVersion:batch.version}));setNotice('Batch submitted atomically. No live integration was called.');})}>Submit {included.length} products for review</button></div>}<p className="footnote">Batch {batch.id} · Revision {batch.version} · Source checksum {batch.checksum.slice(0,16)} · Original source retained privately.</p>
  </>}
  {editing&&batch&&<div className="drawer-backdrop"><aside className="drawer import-editor" role="dialog" aria-modal="true" aria-label={`Correct row ${editing.number}`}><button className="drawer-close" disabled={busy} onClick={()=>setEditing(null)} aria-label="Close row editor">×</button><span className="eyebrow">ROW {editing.number} · BATCH REVISION {batch.version}</span><h2>Inspect & correct product</h2><div className="import-issues">{editing.issues.map((i,n)=><div key={n}><AlertCircle size={15}/><span><b>{i.code.replaceAll('_',' ')}</b><small>{i.message}</small></span></div>)}</div>{editing.duplicateCandidates?.length? <div className="review-feedback"><b>Similar products to inspect</b>{editing.duplicateCandidates.map(c=><p key={c.id}><Link href={`${root}/catalog/items/${c.id}`} target="_blank" rel="noreferrer">{c.sku} · {c.title} ↗</Link></p>)}</div>:null}<div className="import-row-form">{meta?.fields.map(field=><label key={field}>{labels[field]??field}<input dir={field==='title_ar'?'rtl':undefined} value={editing.input[field]??''} disabled={busy||field==='partner_code'&&!moderator} onChange={e=>setEditing({...editing,input:{...editing.input,[field]:e.target.value}})}/></label>)}</div><label className="import-exclude"><input type="checkbox" checked={editing.excluded??false} onChange={e=>setEditing({...editing,excluded:e.target.checked})}/> Exclude this row from submission</label><label className="import-label">Correction / exclusion reason<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain the change for the audit trail"/></label>{error&&<div className="error" role="alert">{error}</div>}<div className="drawer-actions"><button className="primary" disabled={busy||reason.trim().length<5} onClick={()=>void perform(async()=>{const saved=await api<Batch>(`/catalog/imports/${batch.id}/rows`,{expectedVersion:batch.version,rowNumber:editing.number,input:editing.input,excluded:!!editing.excluded,reason});setBatch(saved);setEditing(null);setNotice('Correction saved and batch revalidated.');})}><Save size={15}/> Save & validate</button>{moderator&&editing.issues.some(i=>i.code==='PROBABLE_DUPLICATE')&&<button className="button" disabled={busy||reason.trim().length<10||JSON.stringify(editing.input)!==JSON.stringify(batch.rows.find(r=>r.number===editing.number)?.input)} onClick={()=>void perform(async()=>{setBatch(await api<Batch>(`/catalog/imports/${batch.id}/duplicate-decision`,{expectedVersion:batch.version,rowNumber:editing.number,reason}));setEditing(null);setNotice('Saved row reviewed as a distinct product. Exact duplicates remain blocked.');})}>Confirm saved row is distinct</button>}</div></aside></div>}
 </div>;
}
