'use client';
import {useEffect,useState} from 'react';
import {api} from '../lib/api';
import type {MediaJob} from '../lib/single-flight';
type Job={id:string;sourceType:string;sourceRef:string;status:string;attempts:number;replayCount:number;version:number;lastError:string|null;receiptId:string|null;demoFailures:number};
export function CatalogDamJobs({id,version,editable,moderator,onChanged,readJobs}:{readJobs:()=>Promise<{items:MediaJob[]}>;id:string;version:number;editable:boolean;moderator:boolean;onChanged:()=>Promise<void>}){
 const[jobs,setJobs]=useState<Job[]>([]),[sourceRef,setRef]=useState('studio-front'),[failures,setFailures]=useState(0),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{setJobs((await readJobs()).items.filter(j=>j.sourceType==='DAM'));setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[id,version]);
 return <section className="panel" aria-label="DAM import jobs"><h3>Vendor DAM · local connector</h3><p className="footnote">Durable imports from a deterministic DAM simulator, not a real vendor account. Original product version and local destination are pinned. New images require ATI review. Refresh to see worker progress; do not edit the draft while an import is pending.</p>
 {editable&&<div className="catalog-form"><label>DAM asset reference<select value={sourceRef} disabled={busy} onChange={e=>setRef(e.target.value)}><option value="studio-front">Studio front · synthetic sample</option><option value="studio-back">Studio back · synthetic sample</option></select></label><label>Demo failure scenario<select value={failures} disabled={busy} onChange={e=>setFailures(Number(e.target.value))}><option value={0}>No injected failure</option><option value={1}>Fail first attempt, then retry</option><option value={3}>Exhaust retries, then ATI replay</option></select></label><button className="button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await api(`/catalog/items/${id}/media/jobs`,{requestId:crypto.randomUUID(),expectedVersion:version,sourceRef,demoFailures:failures});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Queue DAM import</button></div>}
 <button className="button" disabled={busy} onClick={async()=>{await load();await onChanged();}}>Refresh DAM jobs</button>{error&&<p className="error" role="alert">{error}</p>}
 {moderator&&jobs.some(j=>j.status==='DLQ')&&<label className="review-reason">DAM replay reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label>}
 {jobs.map(j=><div className="evidence-row" key={j.id} role="group" aria-label={`DAM job ${j.sourceRef}`}><div><b>{j.sourceRef}</b> <span className={`badge ${j.status==='SUCCEEDED'?'green':j.status==='DLQ'?'red':'amber'}`}>{j.status}</span><p>{j.attempts} attempts · {j.replayCount} replays · {j.demoFailures} simulated failures</p>{j.lastError&&<p>{j.lastError} · If the product changed, queue a new import at its current version.</p>}{j.receiptId&&<small>Private ingestion receipt: {j.receiptId}</small>}{moderator&&j.status==='DLQ'&&<button className="button" disabled={busy||reason.trim().length<5} onClick={async()=>{setBusy(true);try{await api(`/catalog/media/jobs/${j.id}/replay`,{expectedVersion:j.version,reason});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Replay DAM job</button>}</div></div>)}
 {!jobs.length&&<p className="footnote">No DAM jobs for this product yet.</p>}<p className="footnote">DAM, queued URL and queued ZIP imports share the durable worker. Optional direct URL/ZIP actions remain synchronous.</p></section>;
}
