'use client';
import {useEffect,useState} from 'react';
import {api} from '../lib/api';
import type {MediaJob} from '../lib/single-flight';
type Job={id:string;sourceType:string;sourceRef:string;status:string;attempts:number;replayCount:number;version:number;lastError:string|null;receiptIds:string[]};
export function CatalogMediaZip({id,version,editable,moderator,onImported,readJobs}:{readJobs:()=>Promise<{items:MediaJob[]}>;id:string;version:number;editable:boolean;moderator:boolean;onImported:()=>Promise<void>}){
 const[file,setFile]=useState<{requestId:string;expectedVersion:number;fileName:string;base64:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[jobs,setJobs]=useState<Job[]>([]),[reason,setReason]=useState(''),[failures,setFailures]=useState(0);
 async function load(){setJobs((await readJobs()).items.filter(j=>j.sourceType==='ZIP'));}
 useEffect(()=>{void load().catch(e=>setError((e as Error).message));},[id,version]);
 return <div className="catalog-form" aria-label="ZIP image import"><h3>Import an image ZIP</h3><p className="footnote">For this product only. Up to 10 raster images, 10 MB ZIP, 20 MB expanded total and 5 MB per image. Images must sit at the ZIP root alongside manifest.json. The entire batch succeeds or fails together; nothing is published.</p>
 <details><summary>Manifest format and archive rules</summary><pre>{JSON.stringify({version:1,images:[{file:'front.png'},{file:'back.jpg'}]},null,2)}</pre><p className="footnote">List every image once, in display order. PNG/JPEG/WebP only. No folders, extra files, encrypted files or links. Names are ASCII and case-insensitively unique. New images are appended in manifest order; use image controls to change the primary image.</p></details>
 {editable&&<><label>Choose image ZIP<input type="file" accept=".zip,application/zip" disabled={busy} onChange={async e=>{setFile(null);setError('');setNotice('');const picked=e.target.files?.[0];if(!picked)return;if(picked.size>10*1024*1024){setError('ZIP exceeds 10 MB.');return;}try{const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Could not read ZIP'));reader.readAsDataURL(picked);});setFile({requestId:crypto.randomUUID(),expectedVersion:version,fileName:picked.name,base64});}catch(err){setError((err as Error).message);}}}/></label>
 <label>ZIP demo failure scenario<select aria-label="ZIP demo failure scenario" value={failures} disabled={busy} onChange={e=>{setFailures(Number(e.target.value));if(file)setFile({...file,requestId:crypto.randomUUID()});}}><option value={0}>No injected failure</option><option value={1}>Fail first attempt, then retry</option><option value={3}>Exhaust retries, then ATI replay</option></select></label>
 <button className="primary" disabled={busy||!file} onClick={async()=>{if(!file)return;setBusy(true);setError('');try{await api(`/catalog/items/${id}/media/zip/jobs`,{...file,demoFailures:failures});setNotice('ZIP queued privately. Validation runs in the worker; keep this product unchanged until completion.');setFile(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Queue ZIP import</button>
 <details><summary>Direct synchronous ZIP import</summary><p className="footnote">Runs in this request without a durable job. Failure scenarios apply only to the queued action.</p><button className="button" disabled={busy||!file} onClick={async()=>{if(!file)return;setBusy(true);setError('');try{const r=await api<{receipts:unknown[];replayed:boolean}>(`/catalog/items/${id}/media/zip`,file);setNotice(`${r.receipts.length} image sources retained. New attachments require ATI review.${r.replayed?' Previous import receipt recovered.':''}`);setFile(null);await onImported();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Validating ZIP and images…':'Import ZIP for review'}</button></details></>}
 <button className="button" disabled={busy} onClick={async()=>{setBusy(true);try{await load();await onImported();setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Refresh ZIP jobs</button>
 {moderator&&jobs.some(j=>j.status==='DLQ')&&<label>ZIP replay reason<textarea value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label>}
 {jobs.map(j=><div className="evidence-row" role="group" aria-label={`ZIP job ${j.sourceRef}`} key={j.id}><div><b>{j.sourceRef}</b> <span className={`badge ${j.status==='SUCCEEDED'?'green':j.status==='DLQ'?'red':'amber'}`}>{j.status}</span><p>{j.attempts} attempts · {j.replayCount} replays · {j.receiptIds.length} image receipts</p>{j.lastError&&<p>{j.lastError} · Invalid archives or changed products require a new corrected import; replay cannot alter stored evidence.</p>}{moderator&&j.status==='DLQ'&&<button className="button" disabled={busy||reason.trim().length<5} onClick={async()=>{setBusy(true);try{await api(`/catalog/media/jobs/${j.id}/replay`,{expectedVersion:j.version,reason});await load();setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Replay ZIP job</button>}</div></div>)}
 <p className="footnote">Queued archives stay in private quarantine storage; raw bytes are never downloadable through this UI. The worker validates every entry and attaches all valid images atomically, pending ATI review. Stored job and source evidence is immutable. Production storage, scanning and retention policies remain unverified.</p>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success-note">{notice}</p>}</div>;
}
