'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {ArrowRight,Check,Download,RefreshCw,ShoppingBag,ShieldCheck,BookOpen,AlertCircle} from 'lucide-react';
import {api} from '../lib/api';
import {BloomShell} from './bloom-shell';
import {coachSteps,coachChapters,coachNotice,coachRequirements} from '../../../packages/simulation/coach-catalog';
import {coachAvailable,coachStepDefaults,coachTotals,type CoachRun,type CoachValues} from '../../../packages/simulation/coach-engine';

const route=(page:string,id:string)=>page==='partner'?`/onboarding/coach/${id}`:`/operator/coach/${id}`;
const currency=(v:unknown)=>`AED ${Number(v??0).toLocaleString('en-AE',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
function download(name:string,content:string,type='text/plain'){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
const arabic:Record<string,string>={
 'Complete your business application':'أكمل طلب شراكة Coach الإمارات','Replace the requested document':'استبدل المستند المطلوب','Business name':'اسم الشركة','Contact name':'اسم جهة الاتصال','Company registration':'رقم تسجيل الشركة','Attach the three fictional sample documents':'أرفق المستندات التجريبية الثلاثة','I understand these are sample business details':'أفهم أن هذه بيانات تجريبية','New sample licence expiry':'تاريخ انتهاء الرخصة التجريبية الجديدة','Attach corrected sample licence':'أرفق الرخصة التجريبية المصححة','Submit application':'إرسال الطلب','Send corrected application':'إرسال الطلب المصحح',
 'Use the fictional details below. Sample trade licence, tax certificate and bank letter are attached within this demonstration.':'استخدم البيانات التجريبية أدناه. يتضمن العرض رخصة تجارية وشهادة ضريبية وخطاب بنك تجريبية.',
 'The first document stays in the history. Submit the updated fictional trade licence for another review.':'يُحفظ المستند الأول في السجل. أرسل الرخصة التجارية التجريبية المحدّثة للمراجعة مجدداً.',
};
function ProductArt({wallet=false}:{wallet?:boolean}){return <svg viewBox="0 0 180 135" role="img" aria-label={wallet?'Sample wallet illustration':'Sample bag illustration'}><ellipse cx="90" cy="116" rx="54" ry="8" fill="#ddd4c7"/>{wallet?<><rect x="36" y="48" width="110" height="65" rx="7" fill="#987551"/><path d="M38 62h106M38 68h106" stroke="#c3a078"/><path d="M130 49v62" stroke="#64472e"/><circle cx="115" cy="83" r="3" fill="#dac39b"/></>:<><path d="M60 48V35q30-40 60 0v13" fill="none" stroke="#5b4230" strokeWidth="6"/><path d="M39 46h102l10 64H29Z" fill="#a27d56"/><path d="M39 47l11 39h80l11-39" fill="#b49167" stroke="#8d6746"/><rect x="80" y="80" width="20" height="13" rx="3" fill="#dbc29a"/></>}<text x="90" y="104" textAnchor="middle" fontSize="7" fill="#4b3526" letterSpacing="2">DEMO</text></svg>;}

export function CoachJourney({partner=false}:{partner?:boolean}){
 const path=usePathname(),id=path.split('/')[3];
 const[run,setRun]=useState<CoachRun|null>(null),[runs,setRuns]=useState<CoachRun[]>([]),[values,setValues]=useState<CoachValues>({}),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saved,setSaved]=useState(''),[ar,setAr]=useState(false),[inspect,setInspect]=useState<string|null>(null),[tab,setTab]=useState('journey');
 const t=(s:string)=>ar?(arabic[s]??s):s;
 function accept(next:CoachRun){setRun(next);setValues(coachStepDefaults(next));}
 async function load(){setError('');try{await api('/auth/me');if(id)accept((await api<{run:CoachRun}>(`/coach-journeys/${id}`)).run);else setRuns((await api<{runs:CoachRun[]}>('/coach-journeys')).runs);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[id]); // Server checks owner/company on every read and action.
 async function start(){setBusy(true);setError('');try{const r=await api<{run:CoachRun}>('/coach-journeys',{requestId:crypto.randomUUID()});location.assign(route('operator',r.run.id));}catch(e){setError((e as Error).message);setBusy(false);}}
 async function submit(fail=false){if(!run)return;setBusy(true);setError('');setSaved('');try{const response=await api<{run:CoachRun}>(`/coach-journeys/${run.id}/commands`,{expectedVersion:run.version,commandId:crypto.randomUUID(),step:coachSteps[run.cursor].id,values,fail});accept(response.run);setInspect(null);setSaved(response.run.history.at(-1)?.result??'Saved.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const step=run?coachSteps[run.cursor]:undefined,correctPage=step?.page===(partner?'partner':'operator');
 const completed=new Set(run?.history.filter(e=>e.status==='done').map(e=>e.step));
 const covered=new Set(coachSteps.filter(s=>completed.has(s.id)).flatMap(s=>s.requirements));
 const inspected=run?[...run.history].reverse().find(e=>e.step===inspect&&e.status==='done'):undefined;
 function exportGuide(){download('Coach-UAE-demo-workflow.txt',`COACH UAE — DEMONSTRATION WORKFLOW\n${coachNotice}\n\nSign in as admin@ati.demo with the fictional password Demo123! and open /operator/coach.\nThe same presenter opens separate partner and ATI pages; this is not real user impersonation.\n\n${coachSteps.map((s,i)=>`${i+1}. ${s.title}\nWho: ${s.owner}\nWhere: ${s.page==='partner'?'Partner page':'ATI page'}\nAction: ${s.action}\n${s.help}\nExpected: ${s.result}\nRequirements: ${s.requirements.join(', ')}`).join('\n\n')}\n\nExternal services are simulated. Saved journeys do not alter the separate operational workspace. Generated-image and translation responses are labelled examples, not live AI. Market expansion is a settings demonstration, not performance testing.`);}
 const content=<div className={`coach-journey ${partner?'coach-partner':''}`} dir={ar?'rtl':'ltr'} lang={ar?'ar':'en'}>
  <div className="coach-topline"><span>COACH UAE <span className="coach-demo-tag">FICTIONAL DEMO PARTNER</span></span><div><button className="text-button" onClick={exportGuide}><BookOpen size={15}/> Download walkthrough</button>{partner&&<button className="text-button" onClick={()=>setAr(!ar)}>{ar?'English':'العربية'}</button>}</div></div>
  {loading?<section className="coach-card"><p>Opening your saved journey…</p></section>:!id?<>
   <section className="coach-welcome"><div><span className="eyebrow">START HERE</span><h1>Coach UAE.<br/>From first introduction<br/>to final payment.</h1><p>One guided story. Follow the same application, collection, order and return all the way to the partner statement.</p><button className="primary" disabled={busy} onClick={()=>void start()}>Start Coach UAE journey <ArrowRight size={18}/></button><small>Use fictional details. No invitations, shipments or payments are sent outside this demo.</small></div><div className="coach-welcome-art"><ProductArt/><span>COACH UAE</span><p>PARTNER JOURNEY</p><small>Illustrative sample collection</small></div></section>
   <div className="coach-intro-grid">{[['01','Apply and approve','Separate partner application and ATI review pages.'],['02','Prepare and launch','Review products, prices and stock before opening sales.'],['03','Deliver and settle','Follow orders, returns, exchange and partner payment.']].map(([n,title,copy])=><section className="coach-card" key={n}><span className="coach-number">{n}</span><h3>{title}</h3><p>{copy}</p></section>)}</div>
   <section className="coach-card"><h2>Continue a saved journey</h2><p>Each new journey starts clean. Previous presentations are never reset.</p>{runs.length?runs.map(r=><Link className="coach-resume" key={r.id} href={route(coachSteps[r.cursor]?.page??'operator',r.id)}><div><b>Coach UAE · {r.status==='complete'?'Completed':coachSteps[r.cursor]?.title}</b><small>{new Date(r.updatedAt).toLocaleString()} · {r.cursor} of {coachSteps.length} steps</small></div><ArrowRight size={18}/></Link>):<p>No saved Coach journeys yet.</p>}</section>
  </>:run?<>
   <header className="coach-heading"><div><span className="eyebrow">{partner?'BLOOMINGDALE’S PARTNER APPLICATION & WORKSPACE':'AL TAYER REVIEW & OPERATIONS'}</span><h1>{partner?'Welcome, Coach UAE':'Coach UAE partner journey'}</h1><p>{partner?'Your application and daily work, with a clear next step.':'Guide the partner from application through launch, delivery and settlement.'}</p></div><button className="button" disabled={busy} onClick={()=>void load()}><RefreshCw size={15}/> Refresh saved progress</button></header>
   <div className="coach-savebar"><span><ShieldCheck size={16}/> Saved to the demo database</span><span>{run.cursor} / {coachSteps.length} steps complete</span><span>{run.partnerStatus}</span></div>
   <progress aria-label="Journey progress" max={coachSteps.length} value={run.cursor}/>
   <nav className="coach-tabs" aria-label="Journey views">{[['journey','Your next step'],['results','Saved business records'],['coverage','Workbook checklist']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>{setTab(key);setInspect(null);}}>{label}</button>)}</nav>
   {saved&&<div className="coach-success" role="status"><Check size={18}/>{saved}</div>}
   {tab==='journey'&&<div className="coach-layout"><aside className="coach-outline" aria-label="Journey chapters">{coachChapters.map((chapter,i)=>{const entries=coachSteps.filter(s=>s.chapter===chapter),done=entries.filter(s=>completed.has(s.id)).length;return <section key={chapter} className={step?.chapter===chapter?'current':''}><h3><span>{String(i+1).padStart(2,'0')}</span>{chapter}<small>{done}/{entries.length}</small></h3>{(step?.chapter===chapter||done===entries.length)&&<ol>{entries.map(s=><li key={s.id}><button disabled={!completed.has(s.id)&&s.id!==step?.id} aria-current={s.id===step?.id?'step':undefined} onClick={()=>setInspect(s.id===step?.id?null:s.id)}>{completed.has(s.id)?<Check size={13}/>:<span className="coach-step-dot"/>}{s.title}</button></li>)}</ol>}</section>;})}</aside>
   <div className="coach-workspace">{inspected?<section className="coach-card"><span className="eyebrow">COMPLETED STEP</span><h2>{inspected.title}</h2><p>{inspected.result}</p><dl className="coach-summary">{Object.entries(inspected.values).map(([k,v])=><div key={k}><dt>{coachSteps.find(s=>s.id===inspected.step)?.fields.find(f=>f.key===k)?.label??k}</dt><dd>{typeof v==='boolean'?(v?'Yes':'No'):String(v)}</dd></div>)}</dl><button className="primary" onClick={()=>setInspect(null)}>Return to the next step</button></section>:!step?<section className="coach-card coach-complete"><Check size={38}/><h2>Coach UAE’s journey is complete.</h2><p>The same application, products, order, return and statement are saved together. Review the business records or replay the story in a new journey.</p><p>{covered.size}/54 workbook requirements have a completed demonstration step. This is demo coverage, not production acceptance.</p><button className="primary" onClick={()=>setTab('results')}>Review the final records</button><Link href="/operator/coach">Start another journey</Link></section>:!correctPage?<section className="coach-card coach-handoff"><span className="eyebrow">NEXT: {step.owner.toUpperCase()}</span><h2>{step.page==='partner'?'The partner takes the next step.':'ATI takes the next step.'}</h2><p>{step.title}. The saved application and records come with you.</p><Link className="primary" href={route(step.page,run.id)}>Open {step.page==='partner'?'Coach partner page':'ATI review page'} <ArrowRight size={17}/></Link><small>Presenter mode: you demonstrate both sides. No account permissions are changed.</small></section>:<section className="coach-card coach-action" key={step.id}>
    <span className="eyebrow">{step.chapter.toUpperCase()} · STEP {run.cursor+1} OF {coachSteps.length}</span><div className="coach-owner">{ar?'المسؤول':'Who does this'}: <b>{step.owner}</b></div><h2>{t(step.title)}</h2><p className="coach-help">{t(step.help)}</p>
    {['apply','correct'].includes(step.id)&&<div className="coach-documents">{(step.id==='correct'?['Trade licence · version 2']:['Trade licence','Tax certificate','Bank letter']).map(name=><button type="button" key={name} onClick={()=>download(`COACH-SAMPLE-${name.split(' ')[0]}.txt`,`FICTIONAL COACH UAE DEMO\n${name}\nNot a real legal, banking or compliance document.\nJourney ${run.id}`)}><ShieldCheck size={19}/><div><b>{name}</b><small>Fictional sample · preview</small></div><Download size={15}/></button>)}</div>}
    {step.id==='correct'&&<div className="coach-warning"><AlertCircle size={17}/>{String(run.facts.reviewMessage)}</div>}
    {['validate','images','translate','catalogue-review','promotion','storefront'].includes(step.id)&&<CoachProducts run={run} preview={step.id==='storefront'} ar={ar}/>}
    {step.id==='activate'&&<div className="coach-ready-list">{[['documents','Documents reviewed'],['erp','Business registered'],['terms','Commercial terms agreed'],['rights','UAE selling permission approved'],['locations','Locations registered'],['published','Products published'],['stock','Stock checked'],['visible','All product previews checked'],['test','Safe launch check passed']].map(([k,title])=><p key={k}><Check size={16}/>{title}<b>{run.checks[k]?'Ready':'Needs attention'}</b></p>)}</div>}
    {['pack','pause','deliver','restore'].includes(step.id)&&<CoachParcels run={run} partner={partner}/>}
    {['return','pickup','inspect','refund','exchange'].includes(step.id)&&<div className="coach-order-summary"><ShoppingBag size={22}/><div><b>{String(run.facts.orderId)}</b><p>Coach bag paid price: {currency(run.products[0]?.paid)} · Wallet: {currency(run.products[2]?.paid)}</p><p>{String(run.facts.returnState??'Delivered order ready for a return request')}</p></div></div>}
    {['statement','payout','reconcile'].includes(step.id)&&<CoachStatement run={run}/>}
    <form onSubmit={e=>{e.preventDefault();void submit();}}><div className="coach-fields">{step.fields.map(f=><label className={f.kind==='checkbox'?'coach-checkbox':''} key={f.key}>{f.kind==='checkbox'?<><input type="checkbox" checked={values[f.key]===true} onChange={e=>setValues({...values,[f.key]:e.target.checked})}/><span>{t(f.label)}</span></>:<><span>{t(f.label)}</span>{f.kind==='select'?<select value={String(values[f.key]??'')} onChange={e=>setValues({...values,[f.key]:e.target.value})}>{f.options?.map(v=><option key={v}>{v}</option>)}</select>:<input required type={f.kind==='number'?'number':f.kind==='email'?'email':'text'} min={f.min} max={f.max} step={f.kind==='number'?'any':undefined} value={String(values[f.key]??'')} onChange={e=>setValues({...values,[f.key]:f.kind==='number'?Number(e.target.value):e.target.value})}/>}</>}</label>)}</div>
    {error&&<div className="coach-warning" role="alert"><AlertCircle size={18}/><span>{error}</span></div>}
    <div className="coach-actions"><button className="primary" disabled={busy}>{busy?'Saving…':run.status==='needs_attention'?'Try this update again':t(step.action)}<ArrowRight size={17}/></button><span>Expected result: {step.result}</span></div></form>
    {step.system&&<details className="coach-technical"><summary>Try a failed update</summary><p>This interrupts only this sample update. It leaves the current business records unchanged, so you can demonstrate recovery.</p><button className="button" disabled={busy||run.status==='needs_attention'} onClick={()=>void submit(true)}>Simulate an unavailable service</button></details>}
   </section>}
   <section className="coach-card coach-recent"><h3>What happened so far</h3>{run.history.length?run.history.slice(-4).reverse().map(h=><div key={h.id}><span className={h.status==='done'?'coach-event-ok':'coach-event-fail'}>{h.status==='done'?<Check size={14}/>:<AlertCircle size={14}/>}</span><div><b>{h.title}</b><p>{h.result}</p><small>{h.owner} · {new Date(h.at).toLocaleTimeString()}</small></div></div>):<p>Create the invitation to begin. Each decision will appear here.</p>}</section></div></div>}
   {tab==='results'&&<div className="coach-results"><section className="coach-card"><h2>Coach UAE business records</h2><p>These records belong to this saved journey only. The separate operational workspace is unchanged.</p><dl className="coach-summary"><div><dt>Partner</dt><dd>{String(run.profile.legalName??'Coach UAE')}</dd></div><div><dt>Status</dt><dd>{run.partnerStatus}</dd></div><div><dt>Market</dt><dd>UAE · AED</dd></div><div><dt>Product count</dt><dd>{run.products.length}</dd></div></dl><CoachProducts run={run} ar={ar}/></section>{run.legs.length>0&&<section className="coach-card"><h2>Deliveries</h2><CoachParcels run={run} partner={partner}/><button className="button" onClick={()=>download('COACH-DEMO-packing-slip.txt',`BLOOMINGDALE'S UAE\nDEMO ONLY — NOT A CARRIER LABEL OR TAX INVOICE\n${run.facts.orderId}\n${run.legs.filter(l=>l.partner==='Coach UAE').map(l=>`${l.product} · ${l.quantity} units · ${l.location} · ${l.state}`).join('\n')}`)}>Download sample packing slip</button></section>}{run.ledger.length>0&&<section className="coach-card"><h2>Coach statement</h2><CoachStatement run={run}/><button className="button" onClick={()=>download('COACH-DEMO-statement.csv','Description,Product,Sales,Tax,Commission,Charges\n'+run.ledger.map(e=>[e.kind,e.product,e.gross,e.tax,e.commission,e.fee].join(',')).join('\n')+'\nNet payable,AED,'+(run.statement??coachTotals(run)).payable,'text/csv')}>Download statement entries</button></section>}
    <section className="coach-card"><h2>Decisions and sample system updates</h2>{run.history.map(h=><details className="coach-history" key={h.id}><summary>{h.status==='done'?'Completed':'Needs attention'} · {h.title}</summary><p>{h.result}</p><p>{h.system} · {h.owner} · {new Date(h.at).toLocaleString()}</p><p>Reference: <code>{h.key}</code></p></details>)}<button className="button" onClick={()=>download('COACH-DEMO-saved-journey.json',JSON.stringify({notice:coachNotice,run},null,2),'application/json')}>Download full saved record</button></section>
    <section className="coach-card"><h2>Other saved outcomes</h2><dl className="coach-summary">{Object.entries(run.facts).map(([k,v])=><div key={k}><dt>{k.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase())}</dt><dd>{String(v)}</dd></div>)}</dl></section></div>}
   {tab==='coverage'&&<section className="coach-card"><h2>The workbook checklist</h2><p>{covered.size} of 54 requirements have a completed step in this journey. Each requirement below links to the steps that demonstrate it. “Covered” does not mean live integration or production acceptance.</p><div className="coach-coverage">{Array.from({length:54},(_,i)=>i+1).map(n=><article key={n}><span>{String(n).padStart(2,'0')}</span><div><h3>{coachRequirements[n-1]}</h3><b>{covered.has(n)?'Demonstrated':'Still to demonstrate'}</b><p>{coachSteps.filter(s=>s.requirements.includes(n)).map(s=>s.title).join(' · ')}</p></div></article>)}</div><p>External-system responses, generated-image examples, translations, invitations and money movement are simulated. Multi-market and second-business steps demonstrate configuration only; no production load testing is claimed.</p></section>}
  </>:null}
  {error&&(!run||!correctPage)&&<div className="coach-warning" role="alert">{error} <Link href="/login?next=/operator/coach">Sign in to the demo</Link></div>}
  <footer className="coach-footnote">{coachNotice}. Presenter roles illustrate responsibilities; your actual account permissions remain unchanged.</footer>
 </div>;
 return partner?<BloomShell>{content}</BloomShell>:content;
}
function CoachProducts({run,preview=false,ar=false}:{run:CoachRun;preview?:boolean;ar?:boolean}){return <div className="coach-products">{run.products.map(p=><article key={p.sku}><div className="coach-product-art"><ProductArt wallet={p.category==='Wallets'}/><span>Sample illustration</span></div><div><b>{ar?p.arabic||'Arabic name awaiting review':p.title}</b><small>{p.colour} · {p.category}</small><strong>{currency(p.paid)}</strong>{preview?<p>Sold by Bloomingdale’s UAE</p>:<><p>{p.approved?p.approval:'Needs review'}{p.published?' · Published':''}</p><small>Physical: {p.onHand} · Held for orders: {p.reserved} · Available: {coachAvailable(p,run.partnerStatus==='Active')}</small></>}</div></article>)}</div>;}
function CoachParcels({run,partner}:{run:CoachRun;partner:boolean}){return <div className="coach-parcels">{run.legs.filter(l=>!partner||l.partner==='Coach UAE').map(l=><article key={l.id}><ShoppingBag size={20}/><div><b>{l.partner} · {l.product}</b><p>{l.quantity} {l.quantity===1?'unit':'units'} · {l.location}</p><small>{l.tracking||'Tracking added at dispatch'}</small></div><span>{l.state}</span></article>)}</div>;}
function CoachStatement({run}:{run:CoachRun}){const totals=run.statement??coachTotals(run);return <div className="coach-statement"><div><span>{totals.locked?'Locked statement':'Current statement preview'}</span><strong>{currency(totals.payable)}</strong><small>Net payable to Coach · no payment made</small></div><dl>{[['Sales after refunds',totals.sales],['Tax included in sales',totals.tax],['Commission',totals.commission],['Shipping and return charges',totals.charges]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{currency(value)}</dd></div>)}</dl></div>;}
