'use client';
import {useEffect,useState} from 'react';
import {Plus,FileCheck2,Calculator,LockKeyhole} from 'lucide-react';
import {api,type Partner,type User} from '../lib/api';
type Agreement={id:string;version:number;rate:string;currency:string;cadence:string;validFrom:string;validUntil:string;status:string;rules:{market?:string;brand?:string|null;categoryRates?:Record<string,string>;returnDays?:number;handlingCharge?:string}};
type Form={rate:string;currency:string;cadence:string;validFrom:string;validUntil:string;market:string;brand:string;categoryRates:{category:string;rate:string}[];returnDays:number;handlingCharge:string};
type Preview={currency:string;basis:string;customerNet:string;current:{version:number;rate:string;commission:string;payable:string}|null;proposed:{rate:string;commission:string;payable:string};returnHandling:string;note:string};
const initial:Form={rate:'0.28',currency:'AED',cadence:'WEEKLY',validFrom:'2026-09-23T12:00',validUntil:'2027-12-31T23:59',market:'AE',brand:'',categoryRates:[{category:'Handbags',rate:'0.30'}],returnDays:30,handlingCharge:'20.00'};
export function Commercials({user}:{user:User}){
 const[brands,setBrands]=useState<string[]>([]),[latestVersion,setLatestVersion]=useState(0);
 const[partners,setPartners]=useState<Partner[]>([]),[partnerId,setPartnerId]=useState(''),[items,setItems]=useState<Agreement[]>([]),[clock,setClock]=useState(''),[form,setForm]=useState<Form>(initial),[open,setOpen]=useState(false),[reason,setReason]=useState(''),[approval,setApproval]=useState<Record<string,string>>({}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<Preview|null>(null),[category,setCategory]=useState('Handbags'),[brand,setBrand]=useState('Maison Azure'),[gross,setGross]=useState('1000.00'),[vendorDiscount,setVendorDiscount]=useState('0.00'),[operatorDiscount,setOperatorDiscount]=useState('0.00');
 const write=['ATI_SUPER_ADMIN','ATI_PARTNER_MANAGER','ATI_FINANCE_ANALYST'].includes(user.role);
 useEffect(()=>{void api<{items:Partner[]}>('/partners?limit=100').then(r=>{setPartners(r.items);setPartnerId(r.items.find(p=>p.id==='vnd_maz')?.id??r.items[0]?.id??'');}).catch(e=>setError(e.message));},[]);
 async function load(id:string){const r=await api<{items:Agreement[];now:string;brands:string[];latestVersion:number}>(`/partners/${id}/agreements`);setItems(r.items);setClock(r.now);setBrands(r.brands);setLatestVersion(r.latestVersion);return r;}
 useEffect(()=>{if(partnerId)void load(partnerId).then(()=>{setOpen(false);setPreview(null);setError('');}).catch(e=>setError(e.message));},[partnerId]);
 function update<K extends keyof Form>(key:K,value:Form[K]){setForm({...form,[key]:value});setPreview(null);}
 function terms(){return {...form,brand:form.brand.trim()||null,validFrom:new Date(`${form.validFrom}Z`).toISOString(),validUntil:new Date(`${form.validUntil}Z`).toISOString()};}
 function newVersion(a?:Agreement){setPreview(null);setReason('');setNotice('');setOpen(true);const from=new Date(Math.ceil(new Date(clock).getTime()/60000)*60000).toISOString().slice(0,16);setForm(a?{rate:a.rate,currency:a.currency,cadence:a.cadence,validFrom:from,validUntil:a.validUntil.slice(0,16),market:a.rules.market??'AE',brand:a.rules.brand??'',categoryRates:Object.entries(a.rules.categoryRates??{}).map(([category,rate])=>({category,rate})),returnDays:a.rules.returnDays??30,handlingCharge:a.rules.handlingCharge??'20.00'}:{...initial,validFrom:from});setBrand(a?.rules.brand??brands[0]??'');}
 async function save(){setBusy(true);setError('');try{await api(`/partners/${partnerId}/agreements`,{...terms(),expectedVersion:latestVersion,reason});await load(partnerId);setOpen(false);setPreview(null);setNotice('Draft saved. It does not affect orders until separately approved and effective.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function calculate(){setError('');setBusy(true);try{setPreview(await api<Preview>(`/partners/${partnerId}/agreements/preview`,{...terms(),category,productBrand:brand,gross,vendorDiscount,operatorDiscount}));}catch(e){setError((e as Error).message);setPreview(null);}finally{setBusy(false);}}
 async function approve(id:string,action='approve'){setError('');setBusy(true);try{await api(`/agreements/${id}/${action}`,{reason:approval[id]});await load(partnerId);setNotice(action==='approve'?'Approved demo configuration. Previous versions and historical order snapshots are unchanged.':'Draft rejected with an audit reason; no trading terms changed.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="commercial-workbench"><section className="panel commercial-intro"><div><FileCheck2 size={24}/><h2>Commercial agreements</h2><p>Configure the rules behind each partnership. ECS owns these terms; external bank disbursement stays with ATI Finance.</p></div><label>Partner<select value={partnerId} onChange={e=>setPartnerId(e.target.value)}>{partners.map(p=><option key={p.id} value={p.id}>{p.displayName}</option>)}</select></label>{write&&<button className="primary" disabled={!partnerId} onClick={()=>newVersion(items[0])}><Plus size={16}/>New version</button>}</section>{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="journey-notice" role="status">{notice}</div>}
 <p className="footnote">Demo clock: {clock.replace('T',' ').slice(0,19)} UTC · Brand-specific terms take precedence over partner defaults. Within a scope, the highest effective approved version wins. Approved versions are immutable. This is configuration of fictional commercial rules, not a legal agreement or payment.</p>
 {open&&write&&<section className="panel commercial-editor"><div className="panel-title"><h2>Draft v{latestVersion+1}</h2><button className="text-button" onClick={()=>{setOpen(false);setPreview(null);}}>Cancel draft</button></div><div className="commercial-grid"><label>Market<select value={form.market} onChange={e=>{setForm({...form,market:e.target.value,currency:({AE:'AED',SA:'SAR',KW:'KWD'} as Record<string,string>)[e.target.value]});setPreview(null);}}>{partners.find(p=>p.id===partnerId)?.markets.filter(m=>user.markets.includes(m)).map(m=><option key={m}>{m}</option>)}</select></label><label>Currency<input value={form.currency} readOnly/></label><label>Canonical brand scope<select value={form.brand} onChange={e=>update('brand',e.target.value)}><option value="">All partner brands</option>{brands.map(b=><option key={b}>{b}</option>)}</select></label><label>Base commission fraction (0.28 = 28%)<input type="number" min="0" max="1" step="0.0001" value={form.rate} onChange={e=>update('rate',e.target.value)}/></label><label>Settlement cadence<select value={form.cadence} onChange={e=>update('cadence',e.target.value)}>{['WEEKLY','BIWEEKLY','MONTHLY'].map(s=><option key={s}>{s}</option>)}</select></label><label>Return window (days)<input type="number" min="0" max="365" value={form.returnDays} onChange={e=>update('returnDays',Number(e.target.value))}/></label><label>Effective from (UTC)<input type="text" placeholder="YYYY-MM-DDTHH:mm (UTC)" value={form.validFrom} onChange={e=>update('validFrom',e.target.value)}/></label><label>Effective until, exclusive (UTC)<input type="text" placeholder="YYYY-MM-DDTHH:mm (UTC)" value={form.validUntil} onChange={e=>update('validUntil',e.target.value)}/></label><label>Return handling charge<input type="number" min="0" step="0.01" value={form.handlingCharge} onChange={e=>update('handlingCharge',e.target.value)}/></label></div>
 <div className="commercial-overrides"><h3>Category overrides</h3><p>Exact category path wins, then the deepest matching category segment, then the base rate.</p>{form.categoryRates.map((r,i)=><div className="override-row" key={i}><label>Category {i+1}<input value={r.category} onChange={e=>update('categoryRates',form.categoryRates.map((v,n)=>n===i?{...v,category:e.target.value}:v))}/></label><label>Rate fraction {i+1}<input type="number" step="0.0001" min="0" max="1" value={r.rate} onChange={e=>update('categoryRates',form.categoryRates.map((v,n)=>n===i?{...v,rate:e.target.value}:v))}/></label><button className="text-button" onClick={()=>update('categoryRates',form.categoryRates.filter((_,n)=>n!==i))}>Remove</button></div>)}<button className="button" onClick={()=>update('categoryRates',[...form.categoryRates,{category:'',rate:form.rate}])}><Plus size={14}/>Add category</button></div>
 <section className="commercial-preview"><h3><Calculator size={18}/> Preview payable impact</h3><div className="commercial-grid"><label>Example product brand<input list="commercial-brand-ids" value={brand} onChange={e=>{setBrand(e.target.value);setPreview(null);}}/><datalist id="commercial-brand-ids">{brands.map(b=><option key={b} value={b}/>)}</datalist></label><label>Example category<input value={category} onChange={e=>{setCategory(e.target.value);setPreview(null);}}/></label><label>Gross amount<input type="number" min="0" value={gross} onChange={e=>{setGross(e.target.value);setPreview(null);}}/></label><label>Vendor-funded discount<input type="number" min="0" value={vendorDiscount} onChange={e=>{setVendorDiscount(e.target.value);setPreview(null);}}/></label><label>ATI-funded discount<input type="number" min="0" value={operatorDiscount} onChange={e=>{setOperatorDiscount(e.target.value);setPreview(null);}}/></label></div><button className="button" disabled={busy} onClick={()=>void calculate()}>Calculate preview</button>{preview&&<div className="preview-result"><div><small>Current effective v{preview.current?.version??'—'}</small><strong>{preview.currency} {preview.current?.payable??'No agreement'}</strong><span>Commission: {preview.current?.commission??'—'}</span></div><div><small>Proposed vendor payable</small><strong>{preview.currency} {preview.proposed.payable}</strong><span>Commission: {preview.proposed.commission} ({(Number(preview.proposed.rate)*100).toLocaleString('en',{maximumFractionDigits:2})}%)</span></div><p>{preview.note}</p></div>}</section><label className="decision-reason">Change reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="primary" disabled={busy||reason.trim().length<5} onClick={()=>void save()}>Save new draft version</button></section>}
 <section className="panel commercial-history"><div className="panel-title"><h2>Version history</h2><span>{items.length} versions</span></div>{items.map(a=><article key={a.id}><div className="commercial-version"><strong>v{a.version}</strong><span className={`badge ${a.status==='APPROVED'?'green':'amber'}`}>{a.status}</span><b>{(Number(a.rate)*100).toLocaleString('en',{maximumFractionDigits:2})}% base · {a.cadence}</b><small>{a.rules.market??'AE'} · {a.currency} · {a.rules.brand??'All partner brands'}</small>{write&&<button className="text-button" onClick={()=>newVersion(a)}>Copy to new version</button>}</div><p>{a.validFrom.slice(0,16).replace('T',' ')} → {a.validUntil.slice(0,16).replace('T',' ')} UTC</p><div className="commercial-tags">{Object.entries(a.rules.categoryRates??{}).map(([c,r])=><span key={c}>{c} · {(Number(r)*100).toLocaleString('en',{maximumFractionDigits:2})}%</span>)}<span>{a.rules.returnDays??30}-day returns</span><span>{a.currency} {a.rules.handlingCharge??'20.00'} return handling</span></div>{a.status==='APPROVED'?<small className="locked-note"><LockKeyhole size={13}/>Immutable approved terms · Existing orders retain their snapshots</small>:write&&a.status==='DRAFT'&&<div className="commercial-approval"><label>Approval reason for v{a.version}<input value={approval[a.id]??''} onChange={e=>setApproval({...approval,[a.id]:e.target.value})}/></label><button className="primary" disabled={busy||(approval[a.id]??'').trim().length<5} onClick={()=>void approve(a.id)}>Approve demo terms</button><button className="button" disabled={busy||(approval[a.id]??'').trim().length<5} onClick={()=>void approve(a.id,'reject')}>Reject draft</button></div>}</article>)}{!items.length&&<div className="empty">No commercial versions yet. ATI must configure and approve terms before activation.</div>}</section></div>;
}
