'use client';
import { useState } from 'react';
import { Download,FileCheck2,Upload,ShieldAlert } from 'lucide-react';
import { api,partnerAccess,type Partner } from '../lib/api';
const types=[['TRADE_LICENSE','Trade licence','الرخصة التجارية'],['VAT_CERTIFICATE','VAT certificate','شهادة ضريبة القيمة المضافة'],['BANK_LETTER','Bank confirmation','خطاب تأكيد البنك'],['BRAND_AUTHORIZATION','Brand authorization (optional)','تفويض العلامة التجارية (اختياري)']];
export function ComplianceDocuments({partner,editable=false,canReview=false,ar=false,onChanged}:{partner:Partner;editable?:boolean;canReview?:boolean;ar?:boolean;onChanged:()=>Promise<void>}){
  const[error,setError]=useState(''),[busy,setBusy]=useState(false),[reasons,setReasons]=useState<Record<string,string>>({}),[files,setFiles]=useState<Record<string,File>>({}),[expires,setExpires]=useState<Record<string,string>>({});
  const t=(en:string,arabic:string)=>ar?arabic:en;
  const access=partnerAccess(partner),visibleTypes=types.filter(([type])=>!access||access.documentTypes.includes(type));
  async function upload(type:string,sample:boolean){setError('');setBusy(true);try{
    const file=sample?new File([`FICTIONAL DEMONSTRATION DOCUMENT\nPartner: ${partner.code}\nType: ${type}\nNot a real legal, tax, banking or brand-rights document.\n`],`SAMPLE-${type}.txt`,{type:'text/plain'}):files[type];
    if(!file)throw new Error(t('Select a file first.','اختر ملفاً أولاً.'));if(file.size>5*1024*1024)throw new Error(t('Maximum file size is 5 MB.','الحد الأقصى لحجم الملف 5 ميجابايت.'));
    const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Could not read file'));reader.readAsDataURL(file);});
    await api(`/partners/${partner.id}/documents`,{expectedVersion:partner.version,type,fileName:file.name,contentType:file.type||'text/plain',base64,expiresAt:expires[type]?`${expires[type]}T23:59:59Z`:type==='TRADE_LICENSE'?'2027-12-31T23:59:59Z':null});await onChanged();
  }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function review(id:string,status:string){setBusy(true);setError('');try{await api(`/documents/${id}/review`,{status,reason:reasons[id]});await onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function download(id:string){setError('');try{const result=await api<{url:string}>(`/documents/${id}/download-link`,{});location.assign(result.url);}catch(e){setError((e as Error).message);}}
  return <div className="compliance"><p className="privacy-note"><ShieldAlert size={17}/>{t('Private evidence · 5 MB maximum · PDF, PNG, JPEG or demo TXT. The local scanner is a simulation, not production malware protection.','مستندات خاصة · 5 ميجابايت كحد أقصى · PDF أو PNG أو JPEG أو TXT تجريبي. الفحص محاكاة وليس حماية فعلية من البرمجيات الضارة.')}</p>{error&&<div className="error" role="alert">{error}</div>}
  {access&&visibleTypes.length<types.length&&<p className="review-feedback" role="note">{t('Some compliance documents are restricted for your role. Hidden documents are not missing documents.','بعض مستندات الامتثال غير متاحة لدورك. إخفاء المستندات لا يعني أنها غير مرفقة.')}</p>}
  {visibleTypes.map(([type,en,arabic])=>{const versions=partner.documents?.filter(d=>d.type===type).sort((a,b)=>b.version-a.version)??[],d=versions[0];return <section className="compliance-card" key={type}><div className="compliance-heading"><FileCheck2 size={20}/><h4>{t(en,arabic)}</h4><span className={`badge ${d?.status==='APPROVED'?'green':d?.status==='REJECTED'?'red':'amber'}`}>{d?.status.replaceAll('_',' ').toLowerCase()??t('missing','غير مرفق')}</span></div>
    {d&&<><p>{d.fileName} · v{d.version} · {Math.ceil(d.byteSize/1024)} KB</p><small>{d.expiresAt?`${t('Expires','ينتهي')} ${d.expiresAt.slice(0,10)}`:t('No expiry specified','لم يحدد تاريخ الانتهاء')} · {d.scanStatus.toLowerCase().replaceAll('_',' ')}</small>{d.reason&&<div className="document-feedback">{d.reason}</div>}{d.byteSize>0&&['MOCK_CLEAN','CLEAN'].includes(d.scanStatus)&&<button type="button" className="text-button" onClick={()=>void download(d.id)}><Download size={14}/>{t('Download private evidence','تنزيل المستند الخاص')}</button>}
    {canReview&&d.status==='PENDING'&&['SUBMITTED','UNDER_REVIEW'].includes(partner.status)&&<div className="document-decision"><label>{t('Review evidence / reason','سبب قرار المراجعة')}<input value={reasons[d.id]??''} onChange={e=>setReasons({...reasons,[d.id]:e.target.value})}/></label><div><button type="button" className="button" disabled={busy||(reasons[d.id]??'').trim().length<5} onClick={()=>void review(d.id,'APPROVED')}>{t('Approve','موافقة')}</button><button type="button" className="button" disabled={busy||(reasons[d.id]??'').trim().length<5} onClick={()=>void review(d.id,'REJECTED')}>{t('Reject with reason','رفض مع السبب')}</button></div></div>}
    </>}
    {editable&&<div className="document-upload"><label>{t('Select evidence','اختيار المستند')}<input type="file" aria-label={`${en} file`} accept="application/pdf,image/png,image/jpeg,text/plain" onChange={e=>{if(e.target.files?.[0])setFiles({...files,[type]:e.target.files[0]});}}/></label><label>{t('Expiry date','تاريخ الانتهاء')}<input type="date" aria-label={`${en} expiry`} value={expires[type]??(type==='TRADE_LICENSE'?'2027-12-31':'')} onChange={e=>setExpires({...expires,[type]:e.target.value})}/></label><div className="document-buttons"><button type="button" className="button" disabled={busy||!files[type]} onClick={()=>void upload(type,false)}><Upload size={14}/>{t('Upload new version','رفع نسخة جديدة')}</button><button type="button" className="text-button" disabled={busy} onClick={()=>void upload(type,true)}>{t('Use fictional sample','استخدام نموذج تجريبي')}</button></div></div>}
    {versions.length>1&&<details><summary>{t('Version history','سجل الإصدارات')} ({versions.length})</summary>{versions.slice(1).map(v=><div className="old-document" key={v.id}><span>v{v.version} · {v.fileName} · {v.status.toLowerCase()}</span>{v.byteSize>0&&['MOCK_CLEAN','CLEAN'].includes(v.scanStatus)&&<button type="button" className="text-button" onClick={()=>void download(v.id)}>{t('Download','تنزيل')}</button>}</div>)}</details>}
  </section>;})}</div>;
}
