'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {AlertTriangle,ArrowLeft,RefreshCw,UserCheck} from 'lucide-react';
import {api,type User} from '../lib/api';
type Item={id:string;kind:string;status:string;version:number;partnerId:string|null;partnerName:string|null;market:string;title:string;summary:string;reason:string|null;createdAt:string;updatedAt:string;resolvedAt:string|null;assignee:{id:string;name:string;active:boolean}|null;source:{type:string;id:string;status:string}|null;actions:string[];canReplay:boolean};
type Detail={item:Item;activity:{id:string;action:string;reason:string|null;createdAt:string;actorName:string}[]};
type Queue={items:Item[];total:number;page:number;limit:number;kinds:string[];metrics:{open:number;replayRequested:number;resolved:number;waived:number;unassigned:number}};
const labels:Record<string,string>={FULFILMENT:'Shipment investigations',SLA:'Service levels',CATALOG_REVIEW:'Catalogue review',INTEGRATION_DLQ:'Outbound integrations',INBOX_DLQ:'Inbound processing'};
const label=(s:string)=>s.replaceAll('_',' ').toLowerCase(),date=(s:string)=>new Date(s).toLocaleString('en-GB',{timeZone:'Asia/Dubai'});
export function Exceptions({user,root,id,refreshToken}:{user:User;root:string;id?:string;refreshToken:number}){
 const [data,setData]=useState<Queue|null>(null),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState('');
 const [status,setStatus]=useState('ACTIONABLE'),[kind,setKind]=useState(''),[market,setMarket]=useState(''),[ownership,setOwnership]=useState('ALL'),[page,setPage]=useState(1);
 async function load(){setError('');try{if(id)setDetail(await api<Detail>(`/exceptions/${encodeURIComponent(id)}`));else{const result=await api<Queue>(`/exceptions?${new URLSearchParams({status,ownership,page:String(page),limit:'15',...(kind?{kind}:{}),...(market?{market}:{})})}`);setData(result);if(page>Math.max(1,Math.ceil(result.total/15)))setPage(Math.max(1,Math.ceil(result.total/15)));}}catch(e){setError((e as Error).message);}}
 useEffect(()=>{setDetail(null);setNotice('');setReason('');void load();},[id,status,kind,market,ownership,page,refreshToken]);
 async function command(action:string){if(!detail)return;setBusy(true);setError('');setNotice('');try{await api(`/exceptions/${detail.item.id}/commands`,{action,expectedVersion:detail.item.version,reason});setReason('');await load();setNotice(action==='CLAIM'?'You now own the next action.':action==='RELEASE'?'Ownership released. The exception remains actionable.':action==='RESOLVE_REPORT'?'ATI resolution recorded. Shipment, stock, finance and SLA state are unchanged.':'Operational note recorded.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function replay(){const source=detail?.item.source;if(!source)return;setBusy(true);setError('');try{await api(`/integrations/${source.type==='INBOX_RECEIPT'?'inbox':'jobs'}/${source.id}/replay`,{reason});setReason('');await load();setNotice('Replay requested, not resolved. Refresh after the worker processes the source record.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function workflow(item:Item){const s=item.source;if(!s)return null;return `${root}/${({SHIPMENT:`orders/${encodeURIComponent(s.id)}`,RETURN:`returns/${encodeURIComponent(s.id)}`,PRODUCT:`catalog/items/${encodeURIComponent(s.id)}`,INTEGRATION_JOB:'integrations',INBOX_RECEIPT:'orders'} as Record<string,string>)[s.type]}`;}
 return <div className="operations exception-center">{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success-note">{notice}</p>}
 <div className="operations-toolbar">{id?<Link className="back-link" href={`${root}/exceptions`}><ArrowLeft size={16}/> All exceptions</Link>:<span className="eyebrow">TRIAGE · OWNERSHIP · AUDITED RESOLUTION</span>}<button className="button" disabled={busy} onClick={()=>void load()}><RefreshCw size={15}/> Refresh exceptions</button></div>
 {!id&&<><section className="panel exception-intro"><AlertTriangle size={24}/><div><h2>Keep every exception moving.</h2><p>Claim the next action, record your investigation and resolve the issue in its source workflow. Reading an alert or claiming an issue does not close it.</p></div></section>
 {data&&<div className="exception-metrics">{[['Open',data.metrics.open],['Replay requested',data.metrics.replayRequested],['Unassigned',data.metrics.unassigned],['Resolved',data.metrics.resolved],['Waived',data.metrics.waived]].map(([name,value])=><div className="panel" key={name}><span>{name}</span><strong>{value}</strong></div>)}</div>}
 <section className="panel exception-filters"><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}>{['ACTIONABLE','ALL','OPEN','REPLAY_REQUESTED','RESOLVED','WAIVED'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>Issue type<select value={kind} onChange={e=>{setKind(e.target.value);setPage(1);}}><option value="">All authorized types</option>{data?.kinds.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><label>Market<select value={market} onChange={e=>{setMarket(e.target.value);setPage(1);}}><option value="">My markets</option>{user.markets.map(m=><option key={m}>{m}</option>)}</select></label><label>Ownership<select value={ownership} onChange={e=>{setOwnership(e.target.value);setPage(1);}}>{['ALL','MINE','UNASSIGNED'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label></section>
 <section className="panel"><div className="exception-table"><table><thead><tr>{['Exception / partner','Source','Owner','State',''].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{data?.items.map(item=><tr key={item.id}><td><b>{item.title}</b><small>{item.partnerName??'ATI operations'} · {item.market}</small></td><td>{item.source?label(item.source.status):'Source unavailable'}<small>{labels[item.kind]}</small></td><td>{item.assignee?.name??'Unassigned'}{item.assignee&&!item.assignee.active&&<small>Inactive account · release required</small>}</td><td><span className={`badge ${['RESOLVED','WAIVED'].includes(item.status)?'green':'amber'}`}>{label(item.status)}</span></td><td><Link className="text-button" href={`${root}/exceptions/${item.id}`}>Review →</Link></td></tr>)}</tbody></table></div>{data&&!data.items.length&&<div className="empty"><UserCheck size={36}/><h3>No exceptions in this view</h3><p>Filters and your current role determine which issues are visible.</p></div>}{data&&<div className="sla-pagination"><span>{data.total} issues · Page {page} of {Math.max(1,Math.ceil(data.total/15))}</span><button className="button" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="button" disabled={page*15>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div>}</section><p className="footnote">Counts respect issue type, market and ownership filters, but are independent of the selected status/page. Integration failures are visible only to authorized ATI operators.</p></>}
 {id&&detail&&<><section className="panel exception-detail"><span className="eyebrow">{labels[detail.item.kind]} · {detail.item.market}</span><h2>{detail.item.title}</h2><span className={`badge ${['RESOLVED','WAIVED'].includes(detail.item.status)?'green':'amber'}`}>{label(detail.item.status)}</span><p>{detail.item.summary}</p><dl><div><dt>Partner</dt><dd>{detail.item.partnerName??'ATI operations'}</dd></div><div><dt>Assigned owner</dt><dd>{detail.item.assignee?.name??'Unassigned'}{detail.item.assignee&&!detail.item.assignee.active?' (inactive)':''}</dd></div><div><dt>Source status</dt><dd>{detail.item.source?label(detail.item.source.status):'Unavailable'}</dd></div><div><dt>Resolved / waived</dt><dd>{detail.item.resolvedAt?`${date(detail.item.resolvedAt)} GST`:['RESOLVED','WAIVED'].includes(detail.item.status)?'Legacy timestamp not recorded':'Not completed'}</dd></div></dl>{detail.item.reason&&<p className="exception-reason">Latest transition reason: {detail.item.reason}</p>}{workflow(detail.item)&&<Link className="button" href={workflow(detail.item)!}>Open source workflow →</Link>}<p className="footnote">Reported shipment issues require an ATI resolution note. System-generated failures require successful replay, catalogue resubmission, or SLA completion/waiver; they cannot be manually hidden. Closing an investigation never changes shipment or financial state. Timestamps for queue actions use wall-clock time; SLA business deadlines use the demo clock.</p></section>
 {!!detail.item.actions.length&&<section className="panel exception-action"><h3>Take the next action</h3><label>Operational note / handoff reason<textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Describe the investigation, intended action or handoff (at least 10 characters). Shared with authorized users of this exception."/></label><div className="decision-actions">{detail.item.actions.map(a=><button className={a==='CLAIM'?'primary':'button'} key={a} disabled={busy||reason.trim().length<10} onClick={()=>void command(a)}>{({CLAIM:'Assign to me',RELEASE:'Release ownership',COMMENT:'Add note',RESOLVE_REPORT:'Record ATI resolution'} as Record<string,string>)[a]}</button>)}{detail.item.canReplay&&<button className="primary" disabled={busy||reason.trim().length<10} onClick={()=>void replay()}>Replay failed operation</button>}</div></section>}
 <section className="panel exception-activity"><h3>Ownership & investigation history</h3><p className="footnote">Latest 50 recorded queue actions. Source workflow evidence remains on the linked record.</p>{detail.activity.map(e=><article key={e.id}><b>{e.actorName} · {label(e.action.replace('exception.',''))}</b><p>{e.reason}</p><small>{date(e.createdAt)} GST</small></article>)}{!detail.activity.length&&<p className="muted">No ownership or investigation notes recorded yet.</p>}</section></>}
 </div>;
}
