'use client';
import { useState } from 'react';
import { api,type User } from '../lib/api';
export type StockRow={id:string;sequence:number;onHand:number;reserved:number;damaged:number;unavailable:number;safetyStock:number;sellable:number;product:{sku:string};location:{name:string;partnerId:string|null}};
export function InventoryEditor({row,user,onSaved}:{row:StockRow;user:User;onSaved:()=>Promise<void>}){
  const[open,setOpen]=useState(false),[values,setValues]=useState(row),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  if(!['ATI_SUPER_ADMIN','ATI_OPERATIONS_MANAGER','VENDOR_ADMIN','VENDOR_FULFILMENT_OPERATOR'].includes(user.role)||user.role.startsWith('VENDOR_')&&row.location.partnerId!==user.partnerId)return null;
  return <><button className="text-button" onClick={()=>{setValues(row);setOpen(!open);}}>Adjust stock</button>{open&&<div className="stock-editor"><b>{row.product.sku} · {row.location.name}</b><p>Source sequence {row.sequence}. Reserved units ({row.reserved}) cannot be edited.</p>{(['onHand','damaged','unavailable','safetyStock'] as const).map(key=><label key={key}>{key.replace(/([A-Z])/g,' $1')}<input type="number" min="0" value={values[key]} onChange={e=>setValues({...values,[key]:Number(e.target.value)})}/></label>)}<label>Adjustment reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<div role="alert" className="error">{error}</div>}<button className="primary" disabled={busy||reason.trim().length<5} onClick={async()=>{setBusy(true);setError('');try{await api(`/inventory/${row.id}/adjust`,{expectedSequence:row.sequence,sourceSequence:row.sequence+1,onHand:values.onHand,damaged:values.damaged,unavailable:values.unavailable,safetyStock:values.safetyStock,reason});await onSaved();setOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Save & synchronize</button><button className="button" onClick={()=>setOpen(false)}>Close</button></div>}</>;
}
