'use client';
import {useEffect,useState} from 'react';
import {api,type User,type Partner} from '../lib/api';
type Location={id:string;name:string;partnerId:string|null;market:string;type:string;status:string;version:number;fyndId:string|null;deliveryCities:string[];cutoffHour:number;dailyCapacity:number};
const blank={name:'',partnerId:'',type:'WAREHOUSE',status:'ACTIVE',cities:'Dubai',cutoffHour:18,dailyCapacity:100,reason:''};
export function Locations({user,refreshToken}:{user:User;refreshToken:number}){
 const[rows,setRows]=useState<Location[]>([]),[partners,setPartners]=useState<Partner[]>([]),[editing,setEditing]=useState<Location|null>(null),[open,setOpen]=useState(false),[values,setValues]=useState(blank),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState('');
 const canWrite=['ATI_SUPER_ADMIN','ATI_PARTNER_MANAGER','ATI_OPERATIONS_MANAGER'].includes(user.role);
 async function load(){try{setRows((await api<{items:Location[]}>('/locations')).items);setPartners((await api<{items:Partner[]}>('/partners?limit=100')).items);setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[refreshToken]);
 function edit(row:Location|null){setEditing(row);setValues(row?{name:row.name,partnerId:row.partnerId??'',type:row.type,status:row.status==='ACTIVE'?'ACTIVE':'INACTIVE',cities:row.deliveryCities.join(', '),cutoffHour:row.cutoffHour,dailyCapacity:row.dailyCapacity,reason:''}:blank);setOpen(true);setError('');}
 async function save(){setBusy(true);try{const data={name:values.name,type:values.type,status:values.status,deliveryCities:values.cities.split(',').map(s=>s.trim()).filter(Boolean),cutoffHour:Number(values.cutoffHour),dailyCapacity:Number(values.dailyCapacity),reason:values.reason};await api(editing?`/locations/${editing.id}`:'/locations',editing?{...data,expectedVersion:editing.version}:{...data,requestId:crypto.randomUUID(),partnerId:values.partnerId||null,market:'AE'});await load();setOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><section className="panel location-panel"><div className="panel-title"><div><h2>Fulfilment locations</h2><p>Configure ownership, service area and operating limits. Fynd IDs are assigned only by acknowledged mock provisioning.</p></div>{canWrite&&<button className="primary" onClick={()=>edit(null)}>Add location</button>}</div><label className="location-search">Search locations<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, owner or mapping ID"/></label><table><thead><tr>{['Location / owner','Service area','Cut-off / capacity','Mapping',''].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{rows.filter(r=>(r.name+r.partnerId+r.fyndId).toLowerCase().includes(query.toLowerCase())).map(r=><tr key={r.id}><td><b>{r.name}</b><small>{partners.find(p=>p.id===r.partnerId)?.displayName??'Al Tayer Insignia'} · {r.type.replaceAll('_',' ')}</small><small>{r.market} · {r.status} · v{r.version}</small></td><td>{r.deliveryCities.join(', ')}</td><td>{String(r.cutoffHour).padStart(2,'0')}:00 Dubai<small>{r.dailyCapacity} orders/day</small></td><td><code>{r.fyndId??'Not provisioned'}</code><small>Current proof is shown in partner readiness</small></td><td>{canWrite&&<button className="text-button" onClick={()=>edit(r)}>Configure</button>}</td></tr>)}</tbody></table>{!rows.length&&<p className="empty">No locations configured.</p>}</section>
 {open&&<div className="drawer-backdrop" onClick={()=>setOpen(false)}><aside className="drawer location-form" aria-label="Location configuration" onClick={e=>e.stopPropagation()}><button className="drawer-close" aria-label="Close location configuration" onClick={()=>setOpen(false)}>×</button><h2>{editing?'Configure location':'Add location'}</h2><p>Changes invalidate the old mapping and gate customer availability. Physical stock, reservations and existing shipments remain unchanged.</p><label>Name<input value={values.name} onChange={e=>setValues({...values,name:e.target.value})}/></label><label>Owner<select disabled={Boolean(editing)} value={values.partnerId} onChange={e=>setValues({...values,partnerId:e.target.value,type:e.target.value?'VENDOR_WAREHOUSE':'WAREHOUSE'})}><option value="">Al Tayer Insignia</option>{partners.filter(p=>p.markets.includes('AE')).map(p=><option value={p.id} key={p.id}>{p.displayName}</option>)}</select></label><label>Location type<select value={values.type} onChange={e=>setValues({...values,type:e.target.value})}>{(values.partnerId?['VENDOR_WAREHOUSE','BRAND_STORE']:['WAREHOUSE']).map(t=><option key={t} value={t}>{t.replaceAll('_',' ')}</option>)}</select></label><label>Status<select value={values.status} onChange={e=>setValues({...values,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></label><label>Delivery cities (comma separated)<input value={values.cities} onChange={e=>setValues({...values,cities:e.target.value})}/></label><label>Daily cut-off hour (Dubai)<input type="number" min="0" max="23" value={values.cutoffHour} onChange={e=>setValues({...values,cutoffHour:Number(e.target.value)})}/></label><label>Daily order capacity<input type="number" min="1" value={values.dailyCapacity} onChange={e=>setValues({...values,dailyCapacity:Number(e.target.value)})}/></label><label>Change reason<input value={values.reason} onChange={e=>setValues({...values,reason:e.target.value})}/></label><p>AE market only in this checkpoint. After saving: open Partners & brands → Review → Prepare brand and locations, then refresh the mapping and inventory evidence.</p>{error&&<div className="error" role="alert">{error}</div>}<button className="primary" disabled={busy||values.reason.trim().length<5||values.name.trim().length<3} onClick={()=>void save()}>Save location</button></aside></div>}{error&&!open&&<div className="error" role="alert">{error}</div>}</>;
}
