'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Bell,Check,RefreshCw} from 'lucide-react';
import {api} from '../lib/api';
type Notice={id:string;category:string;severity:string;entityType:string;entityId:string;partnerId:string|null;market:string;title:string;message:string;eventAt:string;createdAt:string;readAt:string|null};
type Inbox={items:Notice[];total:number;unread:number;page:number;limit:number;deliveryMode:string;categories:string[]};
const labels:Record<string,string>={SLA:'SLA alerts',CATALOG:'Catalogue review',INTEGRATION:'Integration failures',FULFILMENT:'Shipment investigations'};
const date=(v:string)=>new Date(v).toLocaleString('en-GB',{timeZone:'Asia/Dubai'});
export function Notifications({root,refreshToken,onUnread}:{root:string;refreshToken:number;onUnread:(count:number)=>void}){
 const[data,setData]=useState<Inbox|null>(null),[state,setState]=useState('UNREAD'),[category,setCategory]=useState(''),[page,setPage]=useState(1),[busy,setBusy]=useState(''),[error,setError]=useState('');
 async function load(){setError('');try{const result=await api<Inbox>(`/notifications?${new URLSearchParams({state,page:String(page),limit:'15',...(category?{category}:{})})}`);setData(result);onUnread(result.unread);if(page>Math.max(1,Math.ceil(result.total/15)))setPage(Math.max(1,Math.ceil(result.total/15)));}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[state,category,page,refreshToken]);
 const link=(n:Notice)=>`${root}/${({SHIPMENT:`orders/${encodeURIComponent(n.entityId)}`,RETURN:`returns/${encodeURIComponent(n.entityId)}`,PRODUCT:`catalog/items/${encodeURIComponent(n.entityId)}`,INTEGRATION_JOB:'integrations',INBOX_RECEIPT:'orders',EXCEPTION:`exceptions/${encodeURIComponent(n.entityId)}`} as Record<string,string>)[n.entityType]}`;
 async function mark(n:Notice){setBusy(n.id);setError('');try{await api(`/notifications/${n.id}/read`,{read:!n.readAt});await load();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 return <div className="operations notification-center"><section className="panel notification-intro"><Bell size={26}/><div><span className="eyebrow">OPERATIONAL INBOX</span><h2>The right signal. The right team.</h2><p>Private to your account, role and authorized partner scope. These are event notices; open the workflow for its current status.</p></div><span className="count">{data?.unread??0} unread</span><button className="button" onClick={()=>void load()}><RefreshCw size={15}/> Refresh inbox</button></section>
 {error&&<p className="error" role="alert">{error}</p>}
 <section className="panel notification-controls"><div className="order-tabs">{['UNREAD','ALL','READ'].map(s=><button key={s} className={state===s?'selected':''} onClick={()=>{setState(s);setPage(1);}}>{s==='UNREAD'?'Unread':s==='ALL'?'All notices':'Read'}</button>)}</div><label>Category<select value={category} onChange={e=>{setCategory(e.target.value);setPage(1);}}><option value="">All authorized categories</option>{data?.categories.map(c=><option key={c} value={c}>{labels[c]}</option>)}</select></label><p className="footnote">Delivered inside this local application only. No email, SMS or customer communication is sent. Critical SLA breaches additionally notify ATI administrators.</p></section>
 <section className="panel notification-list" aria-label="Operational notifications">{data?.items.map(n=><article className={n.readAt?'is-read':''} key={n.id}><span className={`notification-indicator ${n.severity==='CRITICAL'?'critical':''}`} aria-label={n.readAt?'Read':'Unread'}/><div className="notification-content"><div className="notification-meta"><span>{labels[n.category]}</span><span>{n.market}</span><span className={`badge ${n.severity==='CRITICAL'?'red':'amber'}`}>{n.severity.toLowerCase()}</span></div><h3>{n.title}</h3><p>{n.message}</p><small>{n.partnerId??'ATI operations'} · Reference {n.entityId.slice(-12)}</small><small>Event time: {date(n.eventAt)} GST · Inbox delivery: {date(n.createdAt)} GST</small><div className="notification-actions"><Link className="text-button" href={link(n)}>Open workflow →</Link><button className="button" disabled={!!busy} onClick={()=>void mark(n)}><Check size={14}/>{n.readAt?'Mark unread':'Mark read'}</button></div></div></article>)}
 {data&&!data.items.length&&<div className="empty"><Bell size={38}/><h3>{data.categories.length?'No notices in this view':'No operational alerts assigned to this role'}</h3><p>{data.categories.length?'New relevant events will appear here. Reading a notice does not resolve the underlying exception.':'Catalogue, fulfilment and integration alerts are delivered to the roles responsible for those workflows.'}</p></div>}
 {data&&<div className="sla-pagination"><span>{data.total} matching notices · Page {page} of {Math.max(1,Math.ceil(data.total/15))}</span><button className="button" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="button" disabled={page*15>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div>}</section></div>;
}
