'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ShieldCheck,Save,RefreshCw} from 'lucide-react';
import {api,type User} from '../lib/api';
type Roles={atiRoles:string[];vendorRoles:string[]};
type Policy=Roles&{category:string;severity:string;version:number;source:string;defaults:Roles;roleOptions:{ati:string[];vendor:string[]};recipientCounts:Record<string,number>;activeAtiRecipients:number;updatedAt:string|null};
type Matrix={market:string;deliveryMode:string;appliesTo:string;items:Policy[]};
const labels:Record<string,string>={SLA:'Service levels',CATALOG:'Catalogue review',INTEGRATION:'Integration failures',FULFILMENT:'Shipment investigations',ATI_SUPER_ADMIN:'ATI super admin',ATI_OPERATIONS_MANAGER:'ATI operations manager',ATI_CATALOG_MODERATOR:'ATI catalogue moderator',VENDOR_ADMIN:'Vendor admin',VENDOR_FULFILMENT_OPERATOR:'Vendor fulfilment operator',VENDOR_CATALOG_MANAGER:'Vendor catalogue manager'};
export function NotificationPolicies({user,root,refreshToken}:{user:User;root:string;refreshToken:number}){
 const[market,setMarket]=useState(user.markets[0]??''),[data,setData]=useState<Matrix|null>(null),[selected,setSelected]=useState<Policy|null>(null),[ati,setAti]=useState<string[]>([]),[vendor,setVendor]=useState<string[]>([]),[reason,setReason]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setError('');try{setData(await api<Matrix>(`/notification-policies?${new URLSearchParams({market})}`));}catch(e){setError((e as Error).message);}}
 useEffect(()=>{setData(null);setSelected(null);setNotice('');void load();},[market,refreshToken]);
 const choose=(p:Policy)=>{setSelected(p);setAti([...p.atiRoles]);setVendor([...p.vendorRoles]);setReason('');setNotice('');setError('');};
 async function save(){if(!selected)return;setBusy(true);setError('');setNotice('');try{const result=await api<Policy>('/notification-policies',{market,category:selected.category,severity:selected.severity,expectedVersion:selected.version,atiRoles:ati,vendorRoles:vendor,reason});setSelected(result);setAti(result.atiRoles);setVendor(result.vendorRoles);setReason('');await load();setNotice(`Routing revision ${result.version} saved for ${market}. Historical notices and read state are unchanged.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const change=(role:string,checked:boolean,group:'ati'|'vendor')=>{const update=(values:string[])=>checked?[...values,role]:values.filter(r=>r!==role);if(group==='ati')setAti(update);else setVendor(update);};
 const changed=selected&&JSON.stringify([[...ati].sort(),[...vendor].sort()])!==JSON.stringify([[...selected.atiRoles].sort(),[...selected.vendorRoles].sort()]);
 const recipients=selected?ati.reduce((sum,r)=>sum+(selected.recipientCounts[r]??0),0):0;
 return <div className="operations notification-policy-center"><div className="operations-toolbar"><Link className="back-link" href={`${root}/notifications`}><ArrowLeft size={16}/> Operational inbox</Link><button className="button" disabled={busy} onClick={()=>{setSelected(null);void load();}}><RefreshCw size={15}/> Refresh routing</button></div>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success-note" role="status">{notice}</p>}
 <section className="panel routing-intro"><ShieldCheck size={26}/><div><h2>Route the signal to the responsible team.</h2><p>Configure in-app recipients by market, category and severity. Critical alerts retain ATI administrator escalation; vendor delivery never crosses partner boundaries.</p></div><label>Market<select disabled={busy} value={market} onChange={e=>setMarket(e.target.value)}>{user.markets.map(m=><option key={m}>{m}</option>)}</select></label></section>
 <section className="panel routing-matrix"><table><thead><tr>{['Alert','ATI recipients','Vendor recipients','Revision',''].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{data?.items.map(p=><tr key={`${p.category}-${p.severity}`} className={selected?.category===p.category&&selected?.severity===p.severity?'routing-selected':''}><td><b>{labels[p.category]}</b><small>{p.severity==='CRITICAL'?'Critical escalation':'Warning'}</small></td><td>{p.atiRoles.map(r=><span className="routing-role" key={r}>{labels[r]}</span>)}<small className={p.activeAtiRecipients?'':'error'}>{p.activeAtiRecipients} active ATI recipient{p.activeAtiRecipients===1?'':'s'}</small></td><td>{p.vendorRoles.length?p.vendorRoles.map(r=><span className="routing-role" key={r}>{labels[r]}</span>):<span className="muted">ATI only</span>}</td><td>{p.version?`v${p.version}`:'Demo default'}</td><td><button className="text-button" disabled={busy} onClick={()=>choose(p)}>Configure →</button></td></tr>)}</tbody></table></section>
 {selected&&<section className="panel routing-editor" aria-label="Notification routing editor"><div className="routing-editor-heading"><div><span className="eyebrow">{market} · {selected.severity} · CURRENT REVISION {selected.version}</span><h3>{labels[selected.category]}</h3></div><button className="button" disabled={busy} onClick={()=>{setAti([...selected.defaults.atiRoles]);setVendor([...selected.defaults.vendorRoles]);}}>Select demo defaults</button></div><div className="routing-audiences"><fieldset><legend>ATI operations</legend>{selected.roleOptions.ati.map(r=><label key={r}><input type="checkbox" disabled={busy||selected.severity==='CRITICAL'&&r==='ATI_SUPER_ADMIN'} checked={ati.includes(r)} onChange={e=>change(r,e.target.checked,'ati')}/><span>{labels[r]}<small>{selected.recipientCounts[r]??0} active in {market}{selected.severity==='CRITICAL'&&r==='ATI_SUPER_ADMIN'?' · required escalation':''}</small></span></label>)}</fieldset><fieldset><legend>Partner team</legend>{selected.roleOptions.vendor.map(r=><label key={r}><input type="checkbox" disabled={busy} checked={vendor.includes(r)} onChange={e=>change(r,e.target.checked,'vendor')}/><span>{labels[r]}<small>Only the partner on the originating event</small></span></label>)}{!selected.roleOptions.vendor.length&&<p>Integration payloads and failure traces remain ATI-only.</p>}</fieldset></div><p className={recipients?'routing-preview':'error'}>Routing preview: {recipients} active ATI recipient{recipients===1?'':'s'}; {vendor.length} vendor role{vendor.length===1?'':'s'} within the event partner. At least one active ATI recipient is required.</p><label className="routing-reason">Reason for this revision<textarea disabled={busy} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain the responsibility or escalation change (at least 10 characters)."/></label><button className="primary" disabled={busy||!changed||reason.trim().length<10||!recipients||!ati.length} onClick={()=>void save()}><Save size={16}/> Save routing revision</button><p className="footnote">The server rechecks current recipients and version when saving. This changes the next delivery evaluation, including currently active SLA alerts; existing notices and read/unread state are retained. It does not alter underlying workflow permissions.</p></section>}
 <p className="footnote">In-app only. Email, digest scheduling and repeated timed escalation are not enabled. WARNING integration routing is reserved for future warning events; current dead-letter failures emit CRITICAL. Market selection reflects your account scope, not proof that every market's commerce workflow is implemented.</p></div>;
}
