'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,CheckCircle2,Circle,Save} from 'lucide-react';
import {BloomShell} from './bloom-shell';
import {ComplianceDocuments} from './compliance-documents';
import {api,type Application,type Partner,type User} from '../lib/api';
const blank:Application={registrationNumber:'',taxRegistrationNumber:'',contactName:'',contactEmail:'',phone:'',address:'',brands:'',website:'',beneficiaryName:'',bankLast4:'',estimatedSkus:0,fulfilmentModel:'VENDOR_WAREHOUSE',declaration:false};
const steps=[['Business details','بيانات الشركة'],['Brands & operations','العلامات والعمليات'],['Compliance documents','مستندات الامتثال'],['Commercial agreement','الاتفاقية التجارية'],['Review & submit','المراجعة والإرسال'],['Launch readiness','الاستعداد للإطلاق']];
export function OnboardingWizard(){
 const[partner,setPartner]=useState<Partner|null>(null),[user,setUser]=useState<User|null>(null),[draft,setDraft]=useState<Application>(blank),[legal,setLegal]=useState(''),[display,setDisplay]=useState(''),[step,setStep]=useState(0),[ar,setAr]=useState(false),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const t=(en:string,arabic:string)=>ar?arabic:en;
 async function reload(id:string){const p=await api<Partner>(`/partners/${id}`);setPartner(p);setDraft({...blank,...p.application});setLegal(p.legalName);setDisplay(p.displayName);setDirty(false);}
 useEffect(()=>{void(async()=>{try{const me=await api<{user:User}>('/auth/me');setUser(me.user);if(!me.user.partnerId){location.href='/operator/partners';return;}await reload(me.user.partnerId);}catch(e){setError((e as Error).message);}})();},[]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const editable=user?.role==='VENDOR_ADMIN'&&!!partner&&['APPLICATION_IN_PROGRESS','MORE_INFO_REQUIRED'].includes(partner.status);
 function change<K extends keyof Application>(key:K,value:Application[K]){setDraft({...draft,[key]:value});setDirty(true);setNotice('');}
 async function save(){if(!partner)return;setBusy(true);setError('');try{await api(`/partners/${partner.id}/application`,{expectedVersion:partner.version,legalName:legal,displayName:display,application:draft});await reload(partner.id);setNotice(t('Your application draft has been saved.','تم حفظ مسودة الطلب.'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function submit(){if(!partner)return;setBusy(true);setError('');try{await api(`/partners/${partner.id}/commands`,{action:'submit',expectedVersion:partner.version});await reload(partner.id);setNotice(t('Application submitted to ATI. Your partner manager will review your evidence.','تم إرسال الطلب إلى الطاير لمراجعة المستندات.'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function field(key:keyof Application,en:string,arabic:string,type='text'){return <label key={key}>{t(en,arabic)}<input type={type} value={String(draft[key])} disabled={!editable||busy} onChange={e=>change(key,type==='number'?Number(e.target.value):e.target.value)} min={type==='number'?0:undefined} maxLength={key==='bankLast4'?4:undefined}/></label>;}
 return <BloomShell><main className="partner-journey" dir={ar?'rtl':'ltr'} lang={ar?'ar':'en'}><div className="journey-top"><span className="eyebrow">EXTERNAL CONCESSIONS · UAE</span><button type="button" className="text-button" onClick={()=>setAr(!ar)}>{ar?'English':'العربية'}</button></div><header className="journey-intro"><div><h1>{t('A partnership, beautifully connected.','شراكة استثنائية ومتكاملة.')}</h1><p>{t('Your brand. Our shared ambition. Let’s prepare your business for Bloomingdale’s.','علامتكم التجارية وطموحنا المشترك. لنجهّز أعمالكم للانضمام إلى بلومينغديلز.')}</p></div><div><b>{partner?.displayName??t('Partner application','طلب الشراكة')}</b><small>{partner?.code}</small><span className="application-status">{partner?.status.replaceAll('_',' ').toLowerCase()}</span></div></header>
 <nav className="journey-steps" aria-label="Application steps">{steps.map(([en,arabic],i)=><button type="button" key={en} aria-current={step===i?'step':undefined} onClick={()=>setStep(i)}><span>{String(i+1).padStart(2,'0')}</span>{t(en,arabic)}</button>)}</nav>
 {error&&<div className="error" role="alert">{error}{!user&&<p><Link href="/login?next=/onboarding">Sign in to your partner account →</Link></p>}</div>}{notice&&<div className="journey-notice" role="status">{notice}</div>}
 {partner&&<div className="journey-body"><section className="journey-content"><span className="eyebrow">{t('STEP','الخطوة')} {step+1} / 6</span><h2>{t(...steps[step] as [string,string])}</h2>{partner.reviewReason&&<div className="review-feedback"><b>{t('ATI review feedback','ملاحظات مراجعة الطاير')}</b><p>{partner.reviewReason}</p></div>}{!editable&&<p className="privacy-note">{t('This application is read-only at its current stage. ATI must request changes before you can edit it.','هذا الطلب للقراءة فقط في مرحلته الحالية. يجب أن تطلب الطاير تعديلات قبل تحريره.')}</p>}
 {step===0&&<div className="journey-fields"><label>{t('Legal company name','الاسم القانوني للشركة')}<input value={legal} disabled={!editable||busy} onChange={e=>{setLegal(e.target.value);setDirty(true);}}/></label><label>{t('Trading name','الاسم التجاري')}<input value={display} disabled={!editable||busy} onChange={e=>{setDisplay(e.target.value);setDirty(true);}}/></label>{field('registrationNumber','Company registration number','رقم تسجيل الشركة')}{field('taxRegistrationNumber','Tax registration number','رقم التسجيل الضريبي')}{field('contactName','Primary contact','جهة الاتصال الرئيسية')}{field('contactEmail','Business email','البريد الإلكتروني للعمل','email')}{field('phone','Phone number','رقم الهاتف','tel')}{field('address','Registered address','العنوان المسجل')}</div>}
 {step===1&&<><div className="journey-fields">{field('brands','Brands represented','العلامات التجارية الممثلة')}{field('website','Brand website','موقع العلامة التجارية','url')}{field('estimatedSkus','Estimated SKU count','عدد المنتجات المتوقع','number')}<label>{t('Fulfilment model','نموذج تنفيذ الطلبات')}<select value={draft.fulfilmentModel} disabled={!editable||busy} onChange={e=>change('fulfilmentModel',e.target.value)}><option value="VENDOR_WAREHOUSE">{t('Partner warehouse','مستودع الشريك')}</option><option value="BRAND_STORE">{t('Partner store','متجر الشريك')}</option><option value="ATI_WAREHOUSE">{t('ATI warehouse','مستودع الطاير')}</option></select></label>{field('beneficiaryName','Beneficiary name (fictional)','اسم المستفيد (تجريبي)')}{field('bankLast4','Account last four digits (demo)','آخر أربعة أرقام للحساب (تجريبي)')}</div><p className="privacy-note">{t('Use fictional data only. Do not enter a real account number or IBAN. Territorial brand authorization is independently reviewed by ATI.','استخدم بيانات تجريبية فقط. لا تُدخل رقم حساب حقيقي أو آيبان. تراجع الطاير تفويض العلامة التجارية بصورة مستقلة.')}</p></>}
 {step===2&&<>{dirty&&<p className="review-feedback">{t('Save your business changes before uploading evidence.','احفظ تعديلات الشركة قبل رفع المستندات.')}</p>}<ComplianceDocuments partner={partner} editable={editable&&!dirty} ar={ar} onChanged={()=>reload(partner.id)}/></>}
 {step===3&&<><p>{t('ATI controls commercial terms and their effective dates. This is a read-only demonstration, not an electronic signature or binding contract.','تتحكم الطاير في الشروط التجارية وتواريخ سريانها. هذه محاكاة للقراءة فقط وليست توقيعاً إلكترونياً أو عقداً ملزماً.')}</p>{partner.agreements?.length?partner.agreements.map(a=><div className="agreement-summary" key={a.id}><h3>{t('Agreement','الاتفاقية')} · v{a.version}</h3><dl><dt>{t('Commission','العمولة')}</dt><dd>{(Number(a.rate)*100).toLocaleString('en',{maximumFractionDigits:2})}%</dd><dt>{t('Currency / cadence','العملة / الدورة')}</dt><dd>{a.currency} · {a.cadence}</dd><dt>{t('Effective period','مدة السريان')}</dt><dd>{a.validFrom.slice(0,10)} – {a.validUntil.slice(0,10)}</dd><dt>{t('Status','الحالة')}</dt><dd>{a.status}</dd></dl></div>):<div className="review-feedback">{t('Your ATI partner manager has not assigned an agreement yet. You can submit the application; launch remains blocked until an effective agreement is approved.','لم يحدد مدير الشراكة اتفاقية بعد. يمكنك إرسال الطلب، لكن الإطلاق يتطلب الموافقة على اتفاقية سارية.')}</div>}</>}
 {step===4&&<><dl className="application-review"><dt>{t('Legal entity','الكيان القانوني')}</dt><dd>{legal}</dd><dt>{t('Contact','جهة الاتصال')}</dt><dd>{draft.contactName} · {draft.contactEmail}</dd><dt>{t('Brands','العلامات')}</dt><dd>{draft.brands}</dd><dt>{t('Catalogue size','حجم الكتالوج')}</dt><dd>{draft.estimatedSkus} SKUs</dd></dl><label className="declaration"><input type="checkbox" checked={draft.declaration} disabled={!editable||busy} onChange={e=>change('declaration',e.target.checked)}/>{t('I confirm that these are fictional demonstration details and are ready for ATI review. This is not legal acceptance.','أؤكد أن هذه بيانات تجريبية جاهزة لمراجعة الطاير. لا يشكل هذا قبولاً قانونياً.')}</label>{!!partner.applicationIssues?.length&&<div className="review-feedback"><b>{t('Still needed before submission','المطلوب قبل الإرسال')}</b><ul>{partner.applicationIssues.map(s=><li key={s}>{s}</li>)}</ul></div>}<p>{t('After submission, ATI reviews the latest documents. If more information is needed, the application reopens with a reason and retains every document version.','بعد الإرسال، تراجع الطاير أحدث المستندات. عند الحاجة إلى معلومات إضافية، يُعاد فتح الطلب مع ذكر السبب والاحتفاظ بجميع الإصدارات.')}</p>{editable&&<button type="button" className="primary black" disabled={dirty||busy} onClick={()=>void submit()}>{t('Submit for ATI review','إرسال لمراجعة الطاير')}<ArrowRight size={16}/></button>}{dirty&&<p>{t('Save the draft before submitting.','احفظ المسودة قبل الإرسال.')}</p>}</>}
 {step===5&&<><p>{t('Approval is not activation. Each operational check must pass before your assortment can go live.','الموافقة لا تعني التفعيل. يجب اجتياز جميع الفحوص التشغيلية قبل نشر منتجاتكم.')}</p><div className="readiness">{partner.readiness?.map(g=><div key={g.key}>{g.passed?<CheckCircle2 size={18} className="ok"/>:<Circle size={18}/>}<span>{g.label}</span><small>{g.passed?t('Complete','مكتمل'):t('Pending','قيد الانتظار')}</small></div>)}</div><Link className="primary black" href="/vendor/dashboard">{t('Open partner workspace','فتح مساحة عمل الشريك')}<ArrowRight size={16}/></Link></>}
 <footer className="journey-actions"><button type="button" className="button" disabled={step===0} onClick={()=>setStep(step-1)}><ArrowLeft size={15}/>{t('Back','السابق')}</button>{editable&&<button type="button" className="button" disabled={!dirty||busy} onClick={()=>void save()}><Save size={15}/>{busy?t('Saving…','جارٍ الحفظ…'):t('Save draft','حفظ المسودة')}</button>}{step<5&&<button type="button" className="primary black" onClick={()=>setStep(step+1)}>{t('Continue','متابعة')}<ArrowRight size={15}/></button>}</footer></section><aside className="journey-support"><span className="eyebrow">{t('YOUR PARTNERSHIP','شراكتكم')}</span><h3>{t('Considered at every step.','عناية في كل خطوة.')}</h3><p>{t('Your ATI partner manager reviews the business, documents and brand rights before enabling operations.','يراجع مدير الشراكة أعمالكم ومستنداتكم وحقوق العلامة قبل تفعيل العمليات.')}</p><hr/><b>{t('Before you begin','قبل البدء')}</b><p>{t('Prepare your trade licence, tax certificate and bank confirmation. All sample evidence is private and explicitly fictional.','جهّز الرخصة التجارية والشهادة الضريبية وخطاب البنك. جميع النماذج خاصة وتجريبية بوضوح.')}</p><Link href="/vendor/dashboard">{t('Partner workspace','مساحة عمل الشريك')} →</Link><p className="footnote">{t('Local demo · No documents are sent to Fynd or external services.','عرض محلي · لا تُرسل المستندات إلى فايند أو خدمات خارجية.')}</p></aside></div>}</main></BloomShell>;
}
