'use client';
import { useEffect,useState,useCallback,useRef } from 'react';
import Link from 'next/link';
import { ArrowLeft,Package,RefreshCw,Send,Download,Truck } from 'lucide-react';
import { api,type User } from '../lib/api';
import {InvoiceReferences} from './invoice-references';
import {SlaPanel} from './sla-panel';
import {ShipmentIssues} from './shipment-issues';
type Line={id:string;sku:string;quantity:number;net:string};
type Shipment={id:string;partnerId:string;locationId:string;status:string;requestedStatus:string|null;version:number;fyndId:string|null;tracking:string|null;deadline:string;lines:Line[];order:{externalId:string;currency:string};routingTrace:{sku:string;policy:string;chosenLocation:string;candidates:{locationId:string;name:string;available:number;reasons:string[]}[]}[]};
const label=(s:string)=>s.replaceAll('_',' ').toLowerCase();
export function Orders({user,root,id}:{user:User;root:string;id?:string}){
  const[rows,setRows]=useState<Shipment[]>([]),[selected,setSelected]=useState<Shipment|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('All'),[query,setQuery]=useState('');
  const[reference,setReference]=useState('BLOOM-AE-2026-000101'),[policy,setPolicy]=useState('HYBRID_WATERFALL'),[tracking,setTracking]=useState(''),[reason,setReason]=useState(''),[quantities,setQuantities]=useState<Record<string,number>>({});
  const[partnerId,setPartnerId]=useState(''),[partnerNames,setPartnerNames]=useState<{id:string;displayName:string;status:string}[]>([]),[locationNames,setLocationNames]=useState<{id:string;name:string}[]>([]);
  const[receipts,setReceipts]=useState<{id:string;eventId:string;status:string;error:string|null}[]>([]);
  const vendor=user.role.startsWith('VENDOR_');
  const readGeneration=useRef(0);
  const load=useCallback(async()=>{const generation=++readGeneration.current;try{
    const partners=await api<{items:typeof partnerNames}>('/partners?limit=100'),locations=await api<{items:typeof locationNames}>('/locations');
    const shipment=id?await api<Shipment>(`/shipments/${id}`):null;
    const shipments=id?null:(await api<{items:Shipment[]}>('/shipments?limit=100')).items;
    const inbox=!vendor&&['ATI_SUPER_ADMIN','ATI_OPERATIONS_MANAGER'].includes(user.role)?(await api<{items:typeof receipts}>('/integrations/inbox?limit=25')).items:[];
    if(generation!==readGeneration.current)return;
    setPartnerNames(partners.items);setLocationNames(locations.items);setError('');setSelected(shipment);if(shipment&&!shipment.requestedStatus)setNotice('');if(shipments)setRows(shipments);setReceipts(inbox);
  }catch(e){if(generation!==readGeneration.current)return;setSelected(null);setRows([]);setReceipts([]);setError((e as Error).message);}},[id,vendor,user.role]);
  useEffect(()=>{setSelected(null);setRows([]);setReceipts([]);setNotice('');setTracking('');setReason('');setQuantities({});void load();return()=>{readGeneration.current++;};},[load]);
  const pending=id?!!selected&&(!!selected.requestedStatus||['AWAITING_PAYMENT','AWAITING_FYND'].includes(selected.status)):rows.some(r=>r.requestedStatus||['AWAITING_PAYMENT','AWAITING_FYND'].includes(r.status))||receipts.some(r=>['PENDING','PROCESSING','RETRY'].includes(r.status));
  useEffect(()=>{if(!pending)return;const timer=setInterval(()=>void load(),2500);return()=>clearInterval(timer);},[pending,load]);
  async function emit(){setBusy(true);setNotice('');setError('');try{const result=await api<{receiptId:string;duplicate?:boolean}>('/demo/orders',{externalOrderId:reference,routingPolicy:policy,...(partnerId?{partnerId}:{})});setNotice(`${result.duplicate?'Existing receipt':'Signed SFCC receipt accepted'}: ${result.receiptId}. Processing and allocated shipments refresh automatically.`);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function transition(next:string){if(!selected)return;setBusy(true);setError('');setNotice('');try{await api(`/shipments/${selected.id}/commands`,{next,expectedVersion:selected.version,...(tracking?{tracking}:{}),...(reason?{reason}:{}),...(next==='PACKED'?{confirmedQuantities:quantities}:{})});setNotice('Transition queued. Current status changes only after Fynd acknowledges it.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const next=selected?({ASSIGNED:'ACCEPTED',ACCEPTED:'PICKING',PICKING:'PACKED',PACKED:'READY_TO_DISPATCH',READY_TO_DISPATCH:'DISPATCHED',...(!vendor?{DISPATCHED:'DELIVERED'}:{})} as Record<string,string>)[selected.status]:undefined;
  return <div className="operations">{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="success-note" role="status">{notice}</div>}
    <div className="operations-toolbar">{id?<Link className="back-link" href={`${root}/orders`}><ArrowLeft size={16}/> All shipments</Link>:<span className="eyebrow">{vendor?'YOUR PARTNER SHIPMENTS':'SFCC ORDER → ECS ROUTING → FYND OMS'}</span>}<button className="button" onClick={()=>void load()}><RefreshCw size={15}/> Refresh shipments</button></div>
    {!id&&!vendor&&<section className="panel demo-order"><div><span className="eyebrow">SIGNED SFCC SIMULATOR</span><h3>Receive a customer order</h3><p>{partnerId?'One of each of this partner’s first three published products, using current prices and stock.':'Original sample: a dress, two serums and a candle across three partners.'} This creates an order in the normal fulfilment screens. No customer payment is taken.</p></div><div className="catalog-form"><label>Sample basket<select aria-label="Sample basket" value={partnerId} onChange={e=>{setPartnerId(e.target.value);setReference(`BLOOM-AE-${Date.now()}`);}}><option value="">Original three-partner basket</option>{partnerNames.map(p=><option key={p.id} value={p.id} disabled={p.status!=='ACTIVE'}>{p.displayName}{p.status!=='ACTIVE'?' — complete launch checks first':''}</option>)}</select></label><label>SFCC order reference<input value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Routing policy<select value={policy} onChange={e=>setPolicy(e.target.value)}>{['HYBRID_WATERFALL','WAREHOUSE_FIRST','BRAND_FIRST','STORE_FIRST','LOWEST_SPLIT_COUNT'].map(p=><option key={p} value={p}>{label(p)}</option>)}</select></label><button className="primary" disabled={busy} onClick={()=>void emit()}><Send size={16}/> Receive sample order</button></div></section>}
    {!id&&<section className="panel data-panel"><div className="order-tabs">{['All','Unfulfilled','Processed'].map(t=><button key={t} className={filter===t?'selected':''} onClick={()=>setFilter(t)}>{t}</button>)}</div><div className="table-toolbar"><input aria-label="Search shipments" placeholder="Search order, SKU or partner…" value={query} onChange={e=>setQuery(e.target.value)}/><span className="muted">Shipment view · {rows.length} legs</span></div><table><thead><tr>{['Order / shipment','Partner / source','Items','Status',''].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.filter(r=>(r.order.externalId+r.partnerId+(partnerNames.find(p=>p.id===r.partnerId)?.displayName??'')+r.lines.map(l=>l.sku).join('')).toLowerCase().includes(query.toLowerCase())&&(filter==='All'||(filter==='Processed'?['DISPATCHED','DELIVERED','CANCELLED'].includes(r.status):!['DISPATCHED','DELIVERED','CANCELLED'].includes(r.status)))).map(r=><tr key={r.id}><td><b>{r.order.externalId}</b><small>{r.id.slice(-10)}</small></td><td><b>{partnerNames.find(p=>p.id===r.partnerId)?.displayName??r.partnerId}</b><small>{locationNames.find(l=>l.id===r.locationId)?.name??r.locationId}</small></td><td>{r.lines.reduce((s,l)=>s+l.quantity,0)}</td><td><span className={`badge ${r.status==='DELIVERED'?'green':'amber'}`}>{label(r.status)}</span>{r.requestedStatus&&<small>Pending {label(r.requestedStatus)}</small>}</td><td><Link className="text-button" href={`${root}/orders/${r.id}`}>Open →</Link></td></tr>)}</tbody></table>{!rows.length&&<div className="empty"><Package size={40}/><h3>No allocated shipments yet</h3><p>{vendor?'Only shipments allocated to your partner will appear here.':'Receive the signed sample order, then refresh after processing.'}</p></div>}</section>}
    {!id&&!vendor&&!!receipts.length&&<section className="panel receipt-list"><h3>Inbound processing</h3>{receipts.map(r=><div key={r.id}><b>{r.eventId}</b><span className={`badge ${r.status==='PROCESSED'?'green':r.status==='DEAD_LETTER'?'red':'amber'}`}>{label(r.status)}</span>{r.error&&<p className="error">{r.error}</p>}</div>)}</section>}
    {id&&selected&&<><div className="detail-heading"><div><span className="eyebrow">{selected.order.externalId}</span><h2>Shipment {selected.id.slice(-10)}</h2><span className="badge amber">{label(selected.status)}</span></div><Truck size={32}/></div><div className="catalog-columns"><section className="panel"><h3>Fulfilment workspace</h3><p className="muted">{partnerNames.find(p=>p.id===selected.partnerId)?.displayName??selected.partnerId} · {locationNames.find(l=>l.id===selected.locationId)?.name??selected.locationId}</p><p className="muted">Fynd ID: {selected.fyndId??'Awaiting acknowledgement'}</p><p className="muted">Milestone deadline: {new Date(selected.deadline).toLocaleString('en-GB',{timeZone:'Asia/Dubai'})} GST</p><table><thead><tr><th>SKU</th><th>Quantity</th><th>Confirm picked</th></tr></thead><tbody>{selected.lines.map(l=><tr key={l.id}><td>{l.sku}</td><td>{l.quantity}</td><td>{selected.status==='PICKING'?<input type="number" min="0" max={l.quantity} aria-label={`Picked ${l.sku}`} value={quantities[l.id]??''} onChange={e=>setQuantities({...quantities,[l.id]:Number(e.target.value)})}/>:<span>—</span>}</td></tr>)}</tbody></table>
      {selected.status==='AWAITING_PAYMENT'&&<p className="success-note">Replacement stock is reserved. Fulfilment is blocked until the simulated SFCC payment is acknowledged. No actual money moves. Refreshing automatically.</p>}
      {selected.requestedStatus?<div className="success-note">Awaiting Fynd: {label(selected.requestedStatus)}. Refreshing automatically until acknowledged.</div>:<div className="catalog-form">{selected.status==='READY_TO_DISPATCH'&&<label>Carrier tracking reference<input value={tracking} onChange={e=>setTracking(e.target.value)} placeholder="ATI-DEMO-…"/></label>}{next&&<button className="primary" disabled={busy} onClick={()=>void transition(next)}>{({ACCEPTED:'Accept shipment',PICKING:'Start picking',PACKED:'Confirm picked quantities',READY_TO_DISPATCH:'Ready for dispatch',DISPATCHED:'Confirm carrier handover',DELIVERED:'Confirm demo delivery'} as Record<string,string>)[next]}</button>}{['ASSIGNED','ACCEPTED','PICKING'].includes(selected.status)&&<><label>Cancellation reason<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain why this leg cannot be fulfilled"/></label><button className="button" disabled={busy||reason.trim().length<5} onClick={()=>void transition('CANCELLED')}>Cancel this leg</button></>}</div>}
      {selected.tracking&&<p>Tracking: <b>{selected.tracking}</b></p>}{['PACKED','READY_TO_DISPATCH','DISPATCHED','DELIVERED'].includes(selected.status)&&<a className="button" href={`/api/v1/shipments/${selected.id}/packing-slip`}><Download size={15}/> Download ATI packing slip</a>}<p className="footnote">Customer communication and VAT invoice remain with SFCC. This is a fictional operational demo.</p></section>
      <section className="panel routing-panel"><h3>Why this fulfilment location?</h3>{Array.isArray(selected.routingTrace)?selected.routingTrace.map(trace=><div key={trace.sku}><span className="eyebrow">{label(trace.policy)}</span><h4>{trace.sku}</h4>{trace.candidates.map(c=><div className={`route-candidate ${c.locationId===trace.chosenLocation?'chosen':''}`} key={c.locationId}><b>{c.name}</b><span>{c.available} units ATP at allocation</span><small>{c.reasons.length?c.reasons.join(' · '):c.locationId===trace.chosenLocation?'Selected by routing policy':'Eligible alternative'}</small></div>)}</div>):<div className="route-candidate"><b>Historical demonstration fixture</b><p>This delivered order provides a coherent starting point for returns. Opening inventory already reflects its delivery. Fixture IDs are not live Fynd acknowledgements.</p></div>}</section></div></>}
    {id&&selected&&!vendor&&<InvoiceReferences shipmentId={selected.id} status={selected.status}/>}
    {id&&selected&&<ShipmentIssues shipmentId={selected.id} version={selected.version} status={selected.status} root={root}/>}
    {id&&selected&&<SlaPanel entityType="SHIPMENT" entityId={selected.id} revision={`${selected.version}:${selected.status}`} operator={['ATI_SUPER_ADMIN','ATI_OPERATIONS_MANAGER'].includes(user.role)}/>}
  </div>;
}
