'use client';
import {useEffect,useState} from 'react';
import {PauseCircle,ShieldCheck,RefreshCw} from 'lucide-react';
import {api} from '../lib/api';
import type {ProductSalesResponse} from '../../../packages/contracts/product-sales-responses';

export function ProductSales({id,moderator,refreshToken}:{id:string;moderator:boolean;refreshToken:number}){
 const [value,setValue]=useState<ProductSalesResponse|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[action,setAction]=useState<'pause'|'delist'|'restore'|null>(null),[notice,setNotice]=useState('');
 async function load(){try{setValue(await api<ProductSalesResponse>(`/catalog/items/${id}/sales-control`));setError('');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[id,refreshToken]);
 async function save(){if(!value||!action)return;setBusy(true);setError('');try{setValue(await api<ProductSalesResponse>(`/catalog/items/${id}/sales-control`,{action,expectedVersion:value.version,reason}));setAction(null);setReason('');setNotice('Decision recorded. Stock updates are queued; refresh to verify downstream acknowledgements.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel product-sales" aria-label="Product sales controls"><div className="sales-heading"><div><h3><ShieldCheck size={18}/> Sales availability</h3><p className="muted">Item-level governance · {value?.market??'…'} · independent of catalogue approval</p></div><button className="button" disabled={busy} onClick={()=>void load()}><RefreshCw size={14}/> Check stock sync</button></div>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success-note">{notice}</p>}
 {!value?<p>Loading sales controls…</p>:<><div className="sales-summary"><span className={`badge ${value.status==='ENABLED'?'green':value.status==='DELISTED'?'red':'amber'}`}>{value.status==='ENABLED'?'Sales enabled':value.status==='PAUSED'?'Sales paused':'Delisted'}</span><span>Decision revision {value.version}</span><span>{value.openShipments} open shipment{value.openShipments===1?'':'s'} retained</span></div>
 <p className="footnote">{value.notice}</p>{value.reason&&<div className="review-feedback"><b>Latest decision · effective {new Date(value.effectiveAt!).toLocaleString()}</b><p>{value.reason}</p></div>}
 <div className="sales-positions">{value.positions.length?value.positions.map(p=><article key={p.id}><b>{p.location}</b><div className="sales-quantities"><span>Physical <strong>{p.onHand}</strong></span><span>Reserved <strong>{p.reserved}</strong></span><span>Sellable <strong>{p.sellable}</strong></span></div><small>Stock revision {p.revision}</small><div className="sales-targets">{p.targets.map(t=><span key={t.target} className={`badge ${t.verified?'green':'amber'}`}>{t.target}: {t.verified?'verified':t.status.replaceAll('_',' ').toLowerCase()} · observed {t.observedSellable??'—'}</span>)}</div></article>):<p>No stock positions yet. This sales restriction will also apply when stock is added.</p>}</div>
 {moderator&&!action&&<div className="drawer-actions">{value.status==='ENABLED'&&<button className="button" onClick={()=>setAction('pause')}><PauseCircle size={15}/> Pause sales</button>}{value.status!=='DELISTED'&&<button className="button" onClick={()=>setAction('delist')}>Delist item</button>}{value.status!=='ENABLED'&&<button className="button" onClick={()=>setAction('restore')}>Review restoration</button>}</div>}
 {moderator&&action&&<div className="sales-confirm"><h3>{action==='restore'?'Restore sales eligibility?':action==='pause'?'Pause new sales?':'Delist this SKU?'}</h3><p>{action==='restore'?'Current approval, partner, brand rights and mapping gates must pass. Location and stock gates still apply.':'All locations for this SKU will advertise zero sellable stock after acknowledgement. Existing orders continue normally; physical stock and reservations are not deleted.'}</p><label className="review-reason">Decision reason<textarea maxLength={1000} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)} placeholder="Explain the reason and supporting review…"/></label><div className="drawer-actions"><button className="primary" disabled={busy||reason.trim().length<5} onClick={()=>void save()}>{busy?'Saving…':`Confirm ${action}`}</button><button className="button" disabled={busy} onClick={()=>{setAction(null);setReason('');}}>Cancel</button></div></div>}
 <details className="sales-history"><summary>Decision history · latest {value.history.length}</summary>{value.history.length?value.history.map(h=><article key={h.id}><b>{h.action.replace('catalog.sales-','')} · {new Date(h.at).toLocaleString()}</b><p>{h.reason}</p><small>Actor {h.actorId}</small></article>):<p>No item-level sales decisions recorded.</p>}</details></>}
 </section>;
}
