'use client';
import {useEffect,useState} from 'react';
import {RefreshCw,ScanLine,ShieldCheck} from 'lucide-react';
import {api,type User} from '../lib/api';
import type {ReconciliationList,ReconciliationDetail} from '../../../packages/contracts/reconciliation-responses';
const allowedRoles=['ATI_SUPER_ADMIN','ATI_FINANCE_ANALYST','ATI_AUDITOR'];
type Target={entityType:'SHIPMENT'|'SETTLEMENT';id:string};
export function Reconciliation({user,refreshToken}:{user:User;refreshToken:number}){
 const allowed=allowedRoles.includes(user.role),[market,setMarket]=useState(user.markets[0]??'AE'),[status,setStatus]=useState('OPEN'),[epoch,setEpoch]=useState(0);
 const [list,setList]=useState<ReconciliationList|null>(null),[target,setTarget]=useState<Target>({entityType:'SHIPMENT',id:''}),[detail,setDetail]=useState<ReconciliationDetail|null>(null);
 const [reason,setReason]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!allowed)return;let active=true;setList(null);setError('');void api<ReconciliationList>(`/reconciliation?${new URLSearchParams({market,status})}`).then(r=>{if(active)setList(r);}).catch(e=>{if(active)setError((e as Error).message);});return()=>{active=false;};},[allowed,market,status,epoch,refreshToken,user.id]);
 useEffect(()=>{setDetail(null);if(!allowed||!target.id)return;let active=true;setError('');void api<ReconciliationDetail>(`/reconciliation/evidence?${new URLSearchParams(target)}`).then(r=>{if(active)setDetail(r);}).catch(e=>{if(active)setError((e as Error).message);});return()=>{active=false;};},[allowed,target,epoch,refreshToken,user.id]);
 function select(next:Target){setTarget(next);setNotice('');setReason('');}
 async function command(issue?:ReconciliationDetail['issues'][number]){if(!detail||reason.trim().length<10)return;setBusy(true);setError('');setNotice('');try{
  if(issue)await api(`/reconciliation/issues/${issue.id}/resolve`,{expectedVersion:issue.version,reason});else await api('/reconciliation/scan',{...target,reason});
  setNotice(issue?'Source evidence matched. Resolution and reason recorded.':'Scan recorded. Missing/mismatched evidence is now tracked; matching checks do not silently close open issues.');setEpoch(v=>v+1);
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function repair(){if(!detail||!detail.canRepairLedger)return;setBusy(true);setError('');setNotice('');try{const r=await api<{createdEntries:number}>(`/reconciliation/shipments/${detail.id}/repair-ledger`,{expectedShipmentVersion:detail.entityVersion,reason});setNotice(`${r.createdEntries} missing delivery entries appended from captured terms. No amounts were overwritten and no money moved. Verify and resolve each open investigation separately.`);setEpoch(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!allowed)return <p className="error" role="alert">ATI finance or audit access is required. Vendor sales reporting remains in Analytics and Settlements.</p>;
 return <div className="reconciliation-workspace">
  <section className="panel reconciliation-intro"><div><span className="eyebrow">TRANSACTION-LEVEL CONTROL</span><h2>Trace the difference. Keep the evidence.</h2><p>Compare source order lines, recorded Fynd/SFCC exchanges, delivery ledger entries and Finance exports. These are local mock receipts—not independent downstream read-back or proof of money movement.</p></div><ShieldCheck size={40}/></section>
  <section className="panel reconciliation-picker"><div className="reconciliation-filters"><label>Market<select disabled={busy} value={market} onChange={e=>{setMarket(e.target.value);select({entityType:'SHIPMENT',id:''});}}>{user.markets.filter(m=>['AE','SA','KW'].includes(m)).map(m=><option key={m}>{m}</option>)}</select></label><label>Issue queue<select value={status} onChange={e=>setStatus(e.target.value)}>{['OPEN','RESOLVED','ALL'].map(s=><option key={s}>{s}</option>)}</select></label><button className="button" disabled={busy} onClick={()=>setEpoch(v=>v+1)}><RefreshCw size={16}/>Refresh evidence</button></div>
   <label>Inspect a transaction<select disabled={!list||busy} value={target.id?`${target.entityType}:${target.id}`:''} onChange={e=>{const [entityType,id]=e.target.value.split(':');select({entityType:entityType as Target['entityType'],id:id??''});}}><option value="">Select shipment or statement…</option><optgroup label="Latest 100 shipment legs">{list?.shipments.map(s=><option key={s.id} value={`SHIPMENT:${s.id}`}>{s.reference} · {s.partnerId} · {s.status} · {s.id.slice(-8)}</option>)}</optgroup><optgroup label="Latest 100 statements">{list?.statements.map(s=><option key={s.id} value={`SETTLEMENT:${s.id}`}>{s.partnerId} · {s.status} · {s.id.slice(-8)}</option>)}</optgroup></select></label>
   <p className="footnote">Viewing evidence is read-only. “Record scan” creates or updates investigation records and an audit entry. It never changes ledger, order, shipment or payout values.</p>
  </section>
  {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="reconciliation-notice" role="status">{notice}</p>}
  {list&&<section className="panel reconciliation-table"><div className="panel-title"><h2>{list.total} {status.toLowerCase()} reconciliation issues</h2><span className="muted">Showing latest {list.limit} at most</span></div>{list.items.length?<table><thead><tr><th>Source / check</th><th>Transaction</th><th>Status</th><th>Observed</th><th/></tr></thead><tbody>{list.items.map(i=><tr key={i.id}><td><b>{i.source}</b><small>{i.checkKey}</small></td><td>{i.entityType}<small>{i.entityId.slice(-12)}</small></td><td><span className={`badge ${i.status==='OPEN'?'amber':'green'}`}>{i.status}</span><small>Revision {i.version}</small></td><td>{new Date(i.observedAt).toLocaleString()}</td><td><button className="text-button" disabled={busy} onClick={()=>select({entityType:i.entityType,id:i.entityId})}>Inspect →</button></td></tr>)}</tbody></table>:<div className="reconciliation-empty"><ScanLine size={26}/><h3>No recorded issues in this queue</h3><p>This is not an all-clear: select a transaction and inspect its evidence. Only recorded scans populate the queue.</p></div>}</section>}
  {target.id&&!detail&&!error&&<p role="status">Reading transaction evidence…</p>}
  {detail&&<><section className="panel reconciliation-details"><div className="panel-title"><div><h2>{detail.entityType==='SHIPMENT'?'Shipment reconciliation':'Statement reconciliation'}</h2><p className="muted">{detail.reference} · {detail.partnerId} · {detail.market} / {detail.currency}</p></div><span className="badge">Recorded mock evidence</span></div>
   <div className="reconciliation-summary">{(['MATCH','MISSING','MISMATCH','NOT_DUE'] as const).map(s=><span key={s}><b>{detail.checks.filter(c=>c.status===s).length}</b>{s.replaceAll('_',' ')}</span>)}</div>
   {list?.canManage&&<div className="reconciliation-action"><label>Investigation / resolution reason<textarea value={reason} disabled={busy} onChange={e=>setReason(e.target.value)} minLength={10} maxLength={1000} placeholder="Describe why this scan is being recorded, or the source correction verified."/></label><button className="primary" disabled={busy||reason.trim().length<10} onClick={()=>void command()}><ScanLine size={16}/>Record scan</button></div>}
   <p className="footnote">MATCH proves consistency between the named stored records only. MISSING is not zero. NOT DUE is not a passed check. Repair discrepancies through their source workflow; no balancing entry is created here.</p>
   {detail.canRepairLedger&&<div className="reconciliation-action"><div><b>Local demo recovery · missing delivery ledger</b><p className="footnote">Source lines and recorded delivery receipts match. Reconstruct only absent delivery entries from captured terms. Existing discrepancies block this action; original events remain immutable.</p></div><button className="button" disabled={busy||reason.trim().length<10} onClick={()=>void repair()}>Reconstruct missing entries</button></div>}
   {detail.checks.map(c=>{const issue=detail.issues.find(i=>i.checkKey===c.key);return <article className="reconciliation-check" key={c.key}><div><h3>{c.label}</h3><span className={`badge ${c.status==='MATCH'?'green':c.status==='MISMATCH'?'red':'amber'}`}>{c.status.replaceAll('_',' ')}</span></div><small>{c.source} · {c.key}</small><div className="reconciliation-values"><section><b>Expected</b><pre>{c.expected}</pre></section><section><b>Observed now</b><pre>{c.actual}</pre></section></div>{issue&&<div className="reconciliation-case"><b>Investigation {issue.status.toLowerCase()} · revision {issue.version}</b><details><summary>First-observed evidence · {new Date(issue.firstSeenAt).toLocaleString()}</summary><pre>Expected: {issue.firstExpected}{'\n'}Actual: {issue.firstActual}</pre></details>{issue.resolvedAt&&<small>Resolved {new Date(issue.resolvedAt).toLocaleString()}</small>}{issue.status==='OPEN'&&list?.canManage&&<><button className="button" disabled={busy||c.status!=='MATCH'||reason.trim().length<10} onClick={()=>void command(issue)}>Verify source & resolve</button><small>Requires current matching evidence and an investigation reason. A fresh server check runs before closure.</small></>}</div>}</article>;})}
  </section><section className="panel reconciliation-history"><h2>Audit history</h2><p className="footnote">Latest {detail.historyLimit} events. Original values and before/after snapshots are retained in the audit store.</p>{detail.history.map(h=><article key={h.id}><b>{h.action.replace('reconciliation.','')}</b><time>{new Date(h.createdAt).toLocaleString()}</time><p>{h.reason}</p></article>)}{!detail.history.length&&<p>No scans or reconciliation decisions have been recorded for this transaction.</p>}</section></>}
 </div>;
}
