'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { ArrowLeft,RefreshCw,RotateCcw,PackageCheck,ShieldCheck,Truck } from 'lucide-react';
import { api,type User } from '../lib/api';
import {SlaPanel} from './sla-panel';
import {ReturnEvidence} from './return-evidence';
import {ExchangePreview} from './exchange-preview';
type Case={id:string;legId:string;lineId:string;partnerId:string;quantity:number;status:string;version:number;reason:string;refund:string;payableReversal:string;chargeback:string;currency:string;qc:string|null;refundStatus:string;fyndReturnId:string|null;logisticsId:string|null;refundId:string|null;policy:{days:number;version:number;deliveredAt:string;line:{sku:string};refundOverride?:{reason:string};qcDecision?:{condition:string;disposition:string;reason:string;decidedAt:string;actorId:string;evidenceIds:string[]}}};
type Shipment={id:string;status:string;order:{externalId:string};lines:{id:string;sku:string;quantity:number}[]};
const label=(s:string)=>s.replaceAll('_',' ').toLowerCase();
const money=(s:string)=>`AED ${Number(s).toLocaleString('en-AE',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const actions:Record<string,[string,string][]>= {REQUESTED:[['approve','Approve return'],['reject','Reject request']],APPROVED:[['book-pickup','Book mock pickup']],PICKUP_BOOKED:[['receive','Record receipt']],RECEIVED:[['qc-good','QC passed · Restock'],['qc-bad','QC failed · Quarantine']],QC_FAILED:[['approve-refund','Approve refund override']]};
export function Returns({user,root,id}:{user:User;root:string;id?:string}){
  const[items,setItems]=useState<Case[]>([]),[selected,setSelected]=useState<Case|null>(null),[ships,setShips]=useState<Shipment[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[filter,setFilter]=useState('All'),[query,setQuery]=useState('');
  const[legId,setLegId]=useState(''),[lineId,setLineId]=useState(''),[quantity,setQuantity]=useState(1),[requestId,setRequestId]=useState(''),[creating,setCreating]=useState(false);
  const operator=['ATI_SUPER_ADMIN','ATI_OPERATIONS_MANAGER'].includes(user.role);
  async function load(){setError('');try{if(id)setSelected(await api<Case>(`/returns/${id}`));else{setItems((await api<{items:Case[]}>('/returns?limit=100')).items);setShips((await api<{items:Shipment[]}>('/shipments?limit=100')).items.filter(s=>s.status==='DELIVERED'));}}catch(e){setError((e as Error).message);}}
  useEffect(()=>{setSelected(null);void load();},[id]);
  async function command(action:string){if(!selected)return;setBusy(true);setError('');try{setSelected(await api<Case>(`/returns/${selected.id}/commands`,{action,expectedVersion:selected.version,reason}));setReason('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  useEffect(()=>{if(!selected?.status.endsWith('PENDING'))return;const t=setInterval(()=>void load(),2500);return()=>clearInterval(t);},[selected?.status,id]);
  const currentShip=ships.find(s=>s.id===legId);
  return <div className="operations lifecycle"><div className="operations-toolbar">{id?<Link className="back-link" href={`${root}/returns`}><ArrowLeft size={15}/>All returns</Link>:<span className="eyebrow">POLICY-CONTROLLED REVERSE LOGISTICS</span>}<button className="button" onClick={()=>void load()}><RefreshCw size={14}/>Refresh returns</button></div>
    {error&&<div role="alert" className="error">{error}</div>}
    {!id&&<><div className="flow-banner"><RotateCcw size={30}/><div><h2>Every return, fully accounted for.</h2><p>Validate eligibility → receive & inspect → update stock → instruct SFCC → reverse vendor payable.</p></div><button className="primary" onClick={()=>{setCreating(!creating);if(!requestId)setRequestId(crypto.randomUUID());}}>Request a return</button></div>
    {creating&&<section className="panel workflow-form"><h3>New return request</h3><p className="muted">Only delivered shipments are eligible. Remaining quantity and the original policy are checked on the server.</p>{ships.length===0?<p>No delivered shipments yet. Complete a shipment in My orders, then return here.</p>:<form className="catalog-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await api<Case>('/returns',{legId,lineId,quantity,reason,requestId});location.href=`${root}/returns/${r.id}`;}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>
      <label>Delivered shipment<select required value={legId} onChange={e=>{setLegId(e.target.value);setLineId('');}}><option value="">Select a shipment</option>{ships.map(s=><option key={s.id} value={s.id}>{s.order.externalId} · {s.lines[0]?.sku}</option>)}</select></label>
      <div className="form-pair"><label>Item<select required value={lineId} onChange={e=>setLineId(e.target.value)}><option value="">Select an item</option>{currentShip?.lines.map(l=><option key={l.id} value={l.id}>{l.sku} · {l.quantity} delivered</option>)}</select></label><label>Return quantity<input required type="number" min={1} max={currentShip?.lines.find(l=>l.id===lineId)?.quantity??1} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label></div>
      <label>Reason<input required minLength={5} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Customer request or quality concern"/></label><button className="primary" disabled={busy}>Validate & submit return</button>
    </form>}</section>}
    <section className="panel"><div className="order-tabs">{['All','Needs action','Refund pending','Closed'].map(t=><button key={t} className={filter===t?'selected':''} onClick={()=>setFilter(t)}>{t}</button>)}</div><div className="table-toolbar"><input aria-label="Search returns" placeholder="Search SKU or return reference" value={query} onChange={e=>setQuery(e.target.value)}/><span className="muted">{items.length} authorized returns</span></div><table><thead><tr><th>Return / item</th><th>Units</th><th>Status</th><th>Customer refund</th><th>QC</th><th/></tr></thead><tbody>{items.filter(r=>(r.id+r.policy.line.sku).toLowerCase().includes(query.toLowerCase())&&(filter==='All'||filter==='Closed'&&r.status==='CLOSED'||filter==='Refund pending'&&r.status==='REFUND_PENDING'||filter==='Needs action'&&actions[r.status])).map(r=><tr key={r.id}><td><b>{r.policy.line.sku}</b><small>{r.id.slice(-10)}</small></td><td>{r.quantity}</td><td><span className={`badge ${r.status==='CLOSED'?'green':r.status==='QC_FAILED'?'red':'amber'}`}>{label(r.status)}</span></td><td>{money(r.refund)}</td><td>{r.qc??'Awaiting inspection'}</td><td><Link className="text-button" href={`${root}/returns/${r.id}`}>Open →</Link></td></tr>)}</tbody></table>{items.length===0&&<div className="empty"><RotateCcw size={36}/><h3>No returns yet</h3><p>Start with a delivered order to demonstrate the full return lifecycle.</p></div>}</section></>}
    {selected&&<><div className="detail-heading"><div><span className="eyebrow">RETURN {selected.id.slice(-10)}</span><h2>{selected.policy.line.sku}</h2><p className="muted">{selected.quantity} unit · {selected.reason}</p></div><span className={`badge ${selected.status==='CLOSED'?'green':'amber'}`}>{label(selected.status)}</span></div>
      <div className="metrics">{[[money(selected.refund),'Customer refund instruction'],[money(selected.payableReversal),'Vendor payable reversal'],[money(selected.chargeback),'Return handling charge'],[`${selected.policy.days} days`,'Original return window']].map(([n,l])=><div className="metric" key={l}><span>{l}</span><strong>{n}</strong><small>Agreement policy v{selected.policy.version}</small></div>)}</div>
      <div className="catalog-columns"><section className="panel workflow-form"><h3><PackageCheck size={19}/>Operations decision</h3><p className="muted">{selected.status==='CLOSED'?'SFCC mock acknowledged the refund instruction. No real refund or bank movement occurred.':selected.status==='QC_FAILED'?'Stock has been quarantined as damaged. Refund is held; an operator must record an explicit override to proceed.':selected.status.endsWith('PENDING')?'Waiting for the durable integration job to be acknowledged. This page refreshes automatically.':'Review the evidence and record the next decision.'}</p>
        {operator&&actions[selected.status]&&<><label className="review-reason">Decision reason / evidence<textarea minLength={5} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Record the inspection findings or approval evidence"/></label><div className="decision-actions">{actions[selected.status].map(([a,l])=><button className={a==='qc-bad'||a==='reject'?'button':'primary'} key={a} disabled={busy||reason.trim().length<5} onClick={()=>void command(a)}>{l}</button>)}</div></>}
        {!operator&&<p className="footnote">ATI operations owns approval, pickup, receipt, QC and refund exceptions. Your partner view tracks the same case without operator permissions.</p>}
        {selected.policy.refundOverride&&<div className="success-note">Override recorded: {selected.policy.refundOverride.reason}</div>}
      </section><section className="panel workflow-form"><h3><ShieldCheck size={19}/>Policy & integration evidence</h3><div className="evidence-row"><span>Delivered</span><b>{selected.policy.deliveredAt.slice(0,10)}</b></div><div className="evidence-row"><span>Quality check</span><b>{selected.qc??'Not inspected'}</b></div><div className="evidence-row"><span>Refund status</span><b>{label(selected.refundStatus)}</b></div>{[['Fynd return',selected.fyndReturnId],['Logistics pickup',selected.logisticsId],['SFCC instruction',selected.refundId]].map(([l,v])=><div className="evidence-row" key={l}><span>{l}</span><code>{v??'Awaiting acknowledgement'}</code></div>)}<Link className="text-button" href={`${root}/orders/${selected.legId}`}><Truck size={14}/> View original shipment →</Link><p className="footnote">ATI remains merchant of record. ECS instructs and reconciles; SFCC owns customer refunds. All external acknowledgements here are simulated.</p></section></div>
    {selected.policy.qcDecision&&<section className="panel workflow-form" aria-label="Recorded QC decision"><h3>Recorded inspection decision</h3><p><b>{selected.policy.qcDecision.condition} · {selected.policy.qcDecision.disposition}</b></p><p>{selected.policy.qcDecision.reason}</p><p className="footnote">{selected.policy.qcDecision.evidenceIds.length} photos retained at decision · Demo clock: {new Date(selected.policy.qcDecision.decidedAt).toLocaleString('en-GB',{timeZone:'Asia/Dubai'})} GST</p>{selected.policy.refundOverride&&<p>Refund override does not change the original condition or release quarantined stock.</p>}</section>}
    <ReturnEvidence key={selected.id} id={selected.id} version={selected.version} editable={operator&&selected.status==='RECEIVED'} onSaved={load}/>
    <ExchangePreview key={`${selected.id}:${selected.version}`} id={selected.id} version={selected.version} operator={operator} root={root}/>
    <SlaPanel entityType="RETURN" entityId={selected.id} revision={`${selected.version}:${selected.status}`} operator={operator}/></>}
  </div>;
}
