'use client';
import {useEffect,useState} from 'react';
import {api} from '../lib/api';
type Photo={id:string;fileName:string;notes:string;checksum:string;width:number;height:number;actorId:string;createdAt:string;returnVersion:number};
type Upload={fileName:string;base64:string;requestId:string;expectedVersion:number};
export function ReturnEvidence({id,version,editable,onSaved}:{id:string;version:number;editable:boolean;onSaved:()=>Promise<void>}){
 const[photos,setPhotos]=useState<Photo[]>([]),[file,setFile]=useState<Upload|null>(null),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let active=true;setError('');void api<{items:Photo[]}>(`/returns/${id}/evidence`).then(r=>{if(active)setPhotos(r.items);}).catch(e=>{if(active){setPhotos([]);setError((e as Error).message);}});return()=>{active=false;};},[id,version]);
 return <section className="panel workflow-form" aria-label="Return inspection photos"><h3>Inspection photos</h3><p className="muted">Retain the condition of the returned item, packaging and seal. Do not include faces, addresses or customer documents. Photos become immutable evidence; QC records exactly which photos were available at the decision.</p>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success-note" role="status">{notice}</p>}
 {editable&&photos.length<6?<div className="catalog-form"><label>Inspection photo<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={async e=>{setFile(null);setError('');setNotice('');const f=e.target.files?.[0];if(!f)return;if(f.size>5*1024*1024){setError('Photo exceeds 5 MB.');return;}try{const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Could not read photo'));reader.readAsDataURL(f);});setFile({fileName:f.name,base64,requestId:crypto.randomUUID(),expectedVersion:version});}catch(err){setError((err as Error).message);}}}/></label><label>Photo inspection notes<textarea minLength={5} maxLength={1000} value={notes} disabled={busy} onChange={e=>{setNotes(e.target.value);if(file)setFile({...file,requestId:crypto.randomUUID()});}} placeholder="What does this photo show?"/></label><button className="button" disabled={busy||!file||notes.trim().length<5} onClick={async()=>{if(!file)return;setBusy(true);setError('');try{await api(`/returns/${id}/evidence`,{...file,notes});setFile(null);setNotes('');setNotice('Inspection photo retained privately.');await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Validating photo…':'Save inspection photo'}</button></div>:<p className="footnote">Photos can only be added by ATI operations after receipt and before QC. Existing evidence cannot be replaced or deleted.</p>}
 <p className="footnote">PNG/JPEG/WebP · 128–4096 pixels per side · 5 MB each · up to 6 photos. Metadata is stripped. Local mock scanning only—not a production malware guarantee.</p>
 {!photos.length&&<p>No inspection photos retained. A decision without photos will explicitly record an empty evidence set.</p>}
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:16}}>{photos.map((p,i)=><figure key={p.id} style={{margin:0,border:'1px solid #e5e5eb',padding:16,borderRadius:8}}><a href={`/api/v1/returns/evidence/${p.id}/content`} target="_blank" rel="noreferrer"><img src={`/api/v1/returns/evidence/${p.id}/content`} alt={`Inspection photo ${i+1}: ${p.notes}`} width={224} height={168} style={{objectFit:'contain',width:'100%',background:'#f5f5f8'}}/></a><figcaption><b>Photo {i+1} · {p.fileName}</b><p>{p.notes}</p><small>{p.width} × {p.height} · Return revision {p.returnVersion}<br/>Server upload time: {new Date(p.createdAt).toLocaleString('en-GB',{timeZone:'Asia/Dubai'})} GST</small><details><summary>Integrity reference</summary><code style={{overflowWrap:'anywhere'}}>{p.checksum}</code></details></figcaption></figure>)}</div></section>;
}
