'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import Decimal from 'decimal.js';
import { ArrowLeft,RefreshCw,Wallet,LockKeyhole,Download } from 'lucide-react';
import { api,type User,type Partner } from '../lib/api';
type Event={id:string;partnerId:string;kind:string;amount:string;currency:string;sourceId:string;createdAt:string;settlementId:string|null};
type Statement={id:string;partnerId:string;version:number;status:string;from:string;to:string;payable:string;exportedId:string|null;evidence:{events?:Event[];convention?:string}};
const label=(s:string)=>s.replaceAll('_',' ').toLowerCase();
const money=(s:string)=>`AED ${Number(s).toLocaleString('en-AE',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const actions:Record<string,[string,string][]>= {DRAFT:[['calculate','Calculate statement']],CALCULATED:[['review','Mark reviewed'],['calculate','Recalculate']],REVIEWED:[['lock','Lock statement'],['calculate','Recalculate']],LOCKED:[['export','Export to mock Finance']],EXPORTED:[['confirm-payment','Simulate payout confirmation']]};
export function Settlements({user,root,id}:{user:User;root:string;id?:string}){
  const[items,setItems]=useState<Statement[]>([]),[selected,setSelected]=useState<Statement|null>(null),[events,setEvents]=useState<Event[]>([]),[partners,setPartners]=useState<Partner[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[tab,setTab]=useState('Statements');
  const[creating,setCreating]=useState(false),[partner,setPartner]=useState('vnd_lum'),[from,setFrom]=useState('2026-09-01'),[to,setTo]=useState('2026-10-01'),[amount,setAmount]=useState(''),[requestId,setRequestId]=useState('');
  const canWrite=['ATI_SUPER_ADMIN','ATI_FINANCE_ANALYST'].includes(user.role);
  async function load(){setError('');try{setPartners((await api<{items:Partner[]}>('/partners?limit=100')).items);if(id)setSelected(await api<Statement>(`/settlements/${id}`));else{setItems((await api<{items:Statement[]}>('/settlements?limit=100')).items);setEvents((await api<{items:Event[]}>('/finance/events?limit=100')).items);}}catch(e){setError((e as Error).message);}}
  useEffect(()=>{setSelected(null);void load();},[id]);
  useEffect(()=>{if(!selected?.status.endsWith('PENDING'))return;const t=setInterval(()=>void load(),2500);return()=>clearInterval(t);},[id,selected?.status]);
  const partnerName=(id:string)=>partners.find(p=>p.id===id)?.displayName??id;
  async function command(action:string){if(!selected)return;setBusy(true);setError('');try{setSelected(await api<Statement>(`/settlements/${selected.id}/commands`,{action,expectedVersion:selected.version,reason}));setReason('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const selectedEvents=selected?.evidence.events??[];
  const totals=selectedEvents.reduce<Record<string,Decimal>>((a,e)=>{a[e.kind]=(a[e.kind]??new Decimal(0)).plus(e.amount);return a;},{});
  const locked=selected&&['LOCKED','EXPORT_PENDING','EXPORTED','PAYMENT_PENDING','PAID'].includes(selected.status);
  return <div className="operations lifecycle"><div className="operations-toolbar">{id?<Link className="back-link" href={`${root}/settlements`}><ArrowLeft size={15}/>All statements</Link>:<span className="eyebrow">IMMUTABLE EVIDENCE · EXTERNAL PAYOUT</span>}<button className="button" onClick={()=>void load()}><RefreshCw size={14}/>Refresh finance</button></div>{error&&<div className="error" role="alert">{error}</div>}
    {!id&&<><div className="flow-banner"><Wallet size={30}/><div><h2>From delivered sale to partner statement.</h2><p>Reconcile the ledger, review deductions, lock the evidence and hand off to ATI Finance.</p></div>{canWrite&&<button className="primary" onClick={()=>setCreating(!creating)}>New statement</button>}</div>
    {creating&&canWrite&&<section className="panel workflow-form"><h3>Create settlement period</h3><form className="catalog-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const s=await api<Statement>('/settlements',{partnerId:partner,from:`${from}T00:00:00Z`,to:`${to}T00:00:00Z`});location.href=`${root}/settlements/${s.id}`;}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><label>Partner<select value={partner} onChange={e=>setPartner(e.target.value)}>{partners.map(p=><option value={p.id} key={p.id}>{p.displayName}</option>)}</select></label><div className="form-pair"><label>From, inclusive<input type="date" required value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Until, exclusive<input type="date" required min={from} value={to} onChange={e=>setTo(e.target.value)}/></label></div><small>UTC boundaries. Only unassigned ledger events in this period are eligible.</small><button disabled={busy} className="primary">Create draft statement</button></form></section>}
    <section className="panel"><div className="order-tabs">{['Statements','Financial ledger',...(canWrite?['Adjustment']:[])].map(t=><button className={tab===t?'selected':''} key={t} onClick={()=>{setTab(t);if(!requestId)setRequestId(crypto.randomUUID());}}>{t}</button>)}</div>
      {tab==='Statements'&&<><table><thead><tr><th>Partner / reference</th><th>Period, UTC</th><th>Payable</th><th>Status</th><th/></tr></thead><tbody>{items.map(s=><tr key={s.id}><td><b>{partnerName(s.partnerId)}</b><small>{s.id.slice(-10)}</small></td><td>{s.from.slice(0,10)} → {s.to.slice(0,10)}</td><td><b>{money(s.payable)}</b></td><td><span className={`badge ${s.status==='PAID'?'green':'amber'}`}>{s.status==='PAID'?'paid · simulated':label(s.status)}</span></td><td><Link className="text-button" href={`${root}/settlements/${s.id}`}>Review →</Link></td></tr>)}</tbody></table>{!items.length&&<div className="empty"><Wallet size={36}/><h3>No statements yet</h3><p>Delivered sales create ledger events. ATI Finance can calculate the first period.</p></div>}</>}
      {tab==='Financial ledger'&&<><p className="ledger-note">Latest 100 authorized events. Append-only signed entries; operator-funded discounts and payout markers do not reduce vendor payable.</p><EventTable events={events} partnerName={partnerName}/></>}
      {tab==='Adjustment'&&canWrite&&<form className="catalog-form workflow-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('/finance/adjustments',{partnerId:partner,amount,reason,requestId});setAmount('');setReason('');setRequestId(crypto.randomUUID());setTab('Financial ledger');await load();}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><h3>Append a correction</h3><p className="muted">This creates a new ledger entry for a later statement. Existing locked evidence is never rewritten.</p><label>Partner<select value={partner} onChange={e=>setPartner(e.target.value)}>{partners.map(p=><option value={p.id} key={p.id}>{p.displayName}</option>)}</select></label><label>Signed amount, AED<input required inputMode="decimal" pattern="-?[0-9]+(\.[0-9]{1,2})?" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="15.00 or -15.00"/></label><label>Approval evidence / reason<input required minLength={10} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="primary" disabled={busy}>Record adjustment</button></form>}
    </section></>}
    {selected&&<><div className="detail-heading"><div><span className="eyebrow">STATEMENT {selected.id.slice(-10)}</span><h2>{partnerName(selected.partnerId)}</h2><p className="muted">{selected.from.slice(0,10)} inclusive → {selected.to.slice(0,10)} exclusive · AED · v{selected.version}</p></div><span className={`badge ${selected.status==='PAID'?'green':'amber'}`}>{selected.status==='PAID'?'paid · simulated':label(selected.status)}</span></div>
      <div className="statement-steps">{['DRAFT','CALCULATED','REVIEWED','LOCKED','EXPORTED','PAID'].map((s,i)=><div key={s} className={selected.status===s||selected.status==='EXPORT_PENDING'&&s==='EXPORTED'||selected.status==='PAYMENT_PENDING'&&s==='PAID'?'current':''}><span>{i+1}</span>{label(s)}</div>)}</div>
      <div className="catalog-columns"><section className="panel workflow-form"><div className="statement-total"><span>Net vendor payable</span><strong>{money(selected.payable)}</strong><small>{locked?'Locked evidence · changes move to later statements':'Provisional until reviewed and locked'}</small></div>{Object.entries(totals).map(([kind,total])=><div className="evidence-row" key={kind}><span>{label(kind)}{kind==='OPERATOR_FUNDED_DISCOUNT'?' (informational)':''}</span><b>{money(total.toFixed(2))}</b></div>)}<p className="footnote">Customer refund and vendor reversal are different amounts. Commission uses the original agreement snapshot, not today’s commercial terms.</p></section>
      <section className="panel workflow-form"><h3><LockKeyhole size={18}/>Review & handoff</h3><p className="muted">{selected.status==='PAID'?'Mock Finance has confirmed the simulated payout. No real money moved.':selected.status.endsWith('PENDING')?'Waiting for mock Finance acknowledgement. Refreshing automatically.':locked?'This statement is immutable. Export sends the fixed ledger snapshot to the mock Finance adapter.':'Calculation includes unassigned events only. Any ledger change before locking requires recalculation.'}</p>
      {canWrite&&actions[selected.status]&&<><label className="review-reason">Decision / reconciliation evidence<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Record your review and approval reference"/></label><div className="decision-actions">{actions[selected.status].map(([a,l])=><button key={a} className={a==='calculate'?'button':'primary'} disabled={busy||reason.trim().length<5} onClick={()=>void command(a)}>{l}</button>)}</div></>}
      {locked&&<a className="button evidence-download" href={`/api/v1/settlements/${selected.id}/export`}><Download size={15}/>Download locked CSV</a>}{selected.exportedId&&<div className="evidence-row"><span>Finance acknowledgement</span><code>{selected.exportedId}</code></div>}<p className="footnote">ECS does not hold customer funds, issue VAT invoices or execute bank payments. The payment confirmation control is a local demonstration only.</p></section></div>
      <section className="panel"><div className="panel-title"><h3>Statement evidence</h3><span className="count">{selectedEvents.length} events</span></div><EventTable events={selectedEvents} partnerName={partnerName}/></section>
    </>}
  </div>;
}
function EventTable({events,partnerName}:{events:Event[];partnerName:(id:string)=>string}){return <table><thead><tr><th>Event / partner</th><th>Signed amount</th><th>Source reference</th><th>Booking date</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td><b>{label(e.kind)}</b><small>{partnerName(e.partnerId)}</small></td><td>{money(e.amount)}</td><td><code>{e.sourceId.slice(-18)}</code></td><td>{e.createdAt.slice(0,10)}</td></tr>)}</tbody></table>;}
