'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {AlertTriangle,RefreshCw} from 'lucide-react';
import {api} from '../lib/api';
type Issue={id:string;code:string;severity:string;details:string;reportedStatus:string;reportedVersion:number;createdAt:string;exceptionId:string|null;status:string};
const codes=['STOCK_MISMATCH','DAMAGED_ITEM','PICK_PACK_DELAY','CARRIER_DELAY','DELIVERY_ISSUE','OTHER'];
const label=(s:string)=>s.replaceAll('_',' ').toLowerCase();
export function ShipmentIssues({shipmentId,version,status,root}:{shipmentId:string;version:number;status:string;root:string}){
 const[items,setItems]=useState<Issue[]>([]),[open,setOpen]=useState(false),[code,setCode]=useState('STOCK_MISMATCH'),[severity,setSeverity]=useState('WARNING'),[details,setDetails]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const request=useRef<{signature:string;key:string}|null>(null);
 async function load(){setError('');try{setItems((await api<{items:Issue[]}>(`/shipments/${shipmentId}/issues`)).items);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{setItems([]);setNotice('');setOpen(false);setDetails('');request.current=null;void load();},[shipmentId]);
 async function report(){setBusy(true);setError('');setNotice('');const payload={expectedShipmentVersion:version,code,severity,details:details.trim()},signature=JSON.stringify({shipmentId,...payload});if(request.current?.signature!==signature)request.current={signature,key:crypto.randomUUID()};try{await api(`/shipments/${shipmentId}/issues`,{...payload,requestKey:request.current.key});request.current=null;setDetails('');setOpen(false);await load();setNotice('Report added to the scoped exception centre. ATI and eligible partner users receive an in-app alert; shipment state is unchanged.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel shipment-issues"><div className="operations-toolbar"><div><span className="eyebrow">INVESTIGATION · NOT A SHIPMENT TRANSITION</span><h3>Shipment issues</h3></div><div className="decision-actions"><button className="button" disabled={busy} onClick={()=>void load()}><RefreshCw size={15}/> Refresh issues</button><button className="button" disabled={busy} onClick={()=>setOpen(v=>!v)}><AlertTriangle size={15}/>{open?'Close report form':'Report an issue'}</button></div></div>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success-note" role="status">{notice}</p>}
 {open&&<div className="catalog-form"><p>Reporting against <b>{label(status)}</b>, shipment revision {version}. This does not reserve stock, cancel the leg, stop its SLA clock or contact a customer.</p><label>Issue type<select disabled={busy} value={code} onChange={e=>setCode(e.target.value)}>{codes.map(c=><option key={c} value={c}>{label(c)}</option>)}</select></label><label>Priority<select disabled={busy} value={severity} onChange={e=>setSeverity(e.target.value)}><option value="WARNING">Warning — investigation required</option><option value="CRITICAL">Critical — urgent ATI escalation</option></select></label><label>What happened and what help is needed?<textarea disabled={busy} maxLength={1000} value={details} onChange={e=>setDetails(e.target.value)} placeholder="At least 10 characters. Shared with authorized ATI and partner fulfilment users; do not include payment details or credentials."/></label><button className="primary" disabled={busy||details.trim().length<10} onClick={()=>void report()}>Submit issue report</button></div>}
 <p className="footnote">Latest 100 reports. Reports can be raised at any shipment stage, including after delivery or cancellation. Only ATI operations can record a resolution after investigation. System-generated SLA and integration failures retain their own resolution rules.</p>
 {!items.length&&<p className="muted">No reported issues for this shipment.</p>}
 {items.map(item=><article key={item.id} className="route-candidate"><div><b>{label(item.code)}</b> <span className={`badge ${item.status==='RESOLVED'?'green':item.severity==='CRITICAL'?'red':'amber'}`}>{label(item.status)} · {label(item.severity)}</span></div><p>{item.details}</p><small>Reported at {label(item.reportedStatus)} · revision {item.reportedVersion} · {new Date(item.createdAt).toLocaleString('en-GB',{timeZone:'Asia/Dubai'})} GST</small>{item.exceptionId&&<Link className="text-button" href={`${root}/exceptions/${item.exceptionId}`}>Open investigation →</Link>}</article>)}
 </section>;
}
