'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,Play,FlaskConical,CheckCircle2,AlertTriangle,RotateCcw,Copy,Download,ChevronDown,Clock3,Search,Settings2,Printer,Square,Network} from 'lucide-react';
import {api} from '../lib/api';
import {scenarios,scenarioById,simulationNotice} from '../../../packages/simulation/catalog';
import {simConfig,type SimConfig,type SimRun,type Facts} from '../../../packages/simulation/engine';

const labels:Record<keyof SimConfig,string>={market:'Market',locale:'Application language',source:'Catalogue source',price:'Item price (local currency)',floor:'Minimum advertised price',discount:'Brand-funded discount (%)',commission:'Commission (%)',handling:'Handling charge',stock:'Stock on hand',safety:'Safety stock / threshold',quantity:'Requested units',trusted:'Trusted vendor',restricted:'Restricted category',threshold:'Auto-approval value ceiling',consent:'Creative-use consent',collectionCode:'Collection code (fixture: 4826)',routing:'Routing strategy',elapsedHours:'Elapsed dispatch hours',returnDay:'Return requested on day',window:'Customer return window (days)',grace:'Warehouse grace period (days)',nonReturnable:'Non-returnable item',condition:'QC outcome',replacementPrice:'Replacement purchase price',paymentApproved:'Replacement payment approved',taxRate:'Fictional tax rate (%)',fxRate:'Agreed FX to AED',actualFx:'Received FX to AED',importVat:'Import VAT disclosure (fixture)'};
const choices:Partial<Record<keyof SimConfig,string[]>>={market:['AE','SA','KW'],locale:['en','ar'],source:['CSV','XLSX','API','SFTP','Shopify','WooCommerce'],routing:['warehouse-first','brand-first','hybrid'],condition:['GOOD','BAD']};
const friendly=(key:string)=>key.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());
const format=(value:unknown)=>typeof value==='boolean'?value?'Yes':'No':String(value);
const req=(n:number)=>`REQ-${String(n).padStart(2,'0')}`;
function download(name:string,content:string,type='application/json'){
 const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function FactsView({facts}:{facts:Facts}){return <dl className="sim-facts">{Object.entries(facts).map(([key,value])=><div key={key}><dt>{friendly(key)}</dt><dd dir={key.toLowerCase().includes('arabic')?'rtl':undefined}>{format(value)}</dd></div>)}</dl>;}
export function SimulationStudio({scenarioId,ar=false}:{scenarioId?:string;ar?:boolean}){
 const scenario=scenarioId?scenarioById(scenarioId):undefined;
 const[runs,setRuns]=useState<SimRun[]>([]),[run,setRun]=useState<SimRun|null>(null),[config,setConfig]=useState<SimConfig>(simConfig.parse({}));
 const[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[chapter,setChapter]=useState('All chapters'),[tab,setTab]=useState('outcome');
 const[focusEvent,setFocusEvent]=useState<string|null>(null);const stop=useRef(false);const mounted=useRef(true);
 const t=(en:string,arabic:string)=>ar?arabic:en;
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;stop.current=true;};},[]);
 useEffect(()=>{let live=true;setLoading(true);api<{runs:SimRun[]}>('/simulations').then(data=>{if(!live)return;setRuns(data.runs);const latest=data.runs.find(r=>r.scenarioId===scenarioId);setRun(latest??null);if(latest)setConfig(latest.config);}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[scenarioId]);
 function remember(next:SimRun){if(!mounted.current)return;setRun(next);setRuns(items=>[next,...items.filter(r=>r.id!==next.id)].slice(0,54));}
 async function start(){if(!scenario)return;setBusy(true);setError('');try{const validated=simConfig.safeParse(config);if(!validated.success)throw Error(validated.error.issues.map(i=>`${labels[i.path[0] as keyof SimConfig]??i.path[0]}: ${i.message}`).join('; '));const data=await api<{run:SimRun}>('/simulations',{scenarioId:scenario.id,config:validated.data,requestId:crypto.randomUUID()});remember(data.run);setTab('outcome');setFocusEvent(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function command(action:'next'|'fail'|'retry'|'duplicate',all=false){if(!run)return;setBusy(true);setError('');stop.current=false;let current=run;try{do{const result=await api<{run:SimRun}>(`/simulations/${current.id}/commands`,{expectedVersion:current.version,commandId:crypto.randomUUID(),action});current=result.run;remember(current);}while(all&&current.status==='RUNNING'&&!stop.current&&mounted.current);if(action==='fail'||action==='duplicate')setTab('trace');}catch(e){setError((e as Error).message);try{remember((await api<{run:SimRun}>(`/simulations/${current.id}`)).run);}catch{/* Original failure remains visible. */}}finally{setBusy(false);}}
 const demonstrated=new Set(runs.flatMap(r=>r.events.filter(e=>e.status==='ACKNOWLEDGED').flatMap(e=>scenarioById(r.scenarioId)?.steps.find(s=>s.id===e.stepId)?.requirements??[])));
 const complete=new Set(runs.filter(r=>r.status==='COMPLETED').map(r=>r.scenarioId));
 const event=run?.events.find(e=>e.id===focusEvent)??[...(run?.events??[])].reverse().find(e=>e.status==='ACKNOWLEDGED');
 const ids=scenario?[...new Set(scenario.steps.flatMap(s=>s.requirements))].sort((a,b)=>a-b):[];
 const activeStep=scenario?.steps[run?.cursor??0];
 if(scenarioId&&!scenario)return <section className="panel"><h2>Scenario not found</h2><Link href="/operator/simulations">Return to Simulation Studio</Link></section>;
 return <div className="sim-studio">
  <div className="sim-banner"><FlaskConical size={20}/><div><b>{t('Simulation Studio','استوديو المحاكاة')}</b><span>{t('Fictional data. Simulated integrations. No external transactions.','بيانات افتراضية وتكاملات محاكاة. لا توجد معاملات خارجية.')}</span></div><span className="sim-tag">SANDBOX</span></div>
  {error&&<div className="error" role="alert">{error}</div>}
  {loading&&<p role="status">Loading your saved simulations…</p>}
  {!scenario?<>
   <section className="sim-hero"><div><span className="eyebrow">AL TAYER · STAKEHOLDER DEMONSTRATION</span><h2>Every handoff.<br/>Every “what if”.</h2><p>Explore the complete concession lifecycle with guided scenarios, editable rules and inspectable system receipts.</p><p className="sim-small">These isolated simulations complement the operational demo. They do not mark the underlying requirements as production-complete.</p></div><div className="sim-hero-stats"><strong>{demonstrated.size}<span>/ 54</span></strong><p>requirements exercised in your saved runs</p><div>{complete.size} of {scenarios.length} scenarios completed</div></div></section>
   <div className="sim-catalog-toolbar"><label className="search-input"><Search size={16}/><input aria-label="Search simulation scenarios" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a workflow or requirement ID…"/></label><select aria-label="Filter simulation chapter" value={chapter} onChange={e=>setChapter(e.target.value)}>{['All chapters',...new Set(scenarios.map(s=>s.chapter))].map(c=><option key={c}>{c}</option>)}</select></div>
   <div className="sim-grid">{scenarios.filter(s=>(chapter==='All chapters'||chapter===s.chapter)&&`${s.title} ${s.summary} ${s.steps.flatMap(s=>s.requirements.map(req)).join(' ')}`.toLowerCase().includes(query.toLowerCase())).map((s,i)=>{const saved=runs.find(r=>r.scenarioId===s.id);return <Link href={`/operator/simulations/${s.id}`} className="sim-card" key={s.id}><div className="sim-card-top"><span>{s.chapter}</span>{complete.has(s.id)?<CheckCircle2 size={19}/>:<span className="sim-card-number">{String(i+1).padStart(2,'0')}</span>}</div><h3>{s.title}</h3><p>{s.summary}</p><div className="sim-chips">{[...new Set(s.steps.flatMap(x=>x.requirements))].sort((a,b)=>a-b).map(n=><span key={n}>{req(n)}</span>)}</div><div className="sim-card-bottom"><span>{saved?`${saved.cursor}/${s.steps.length} steps saved`:`${s.steps.length} guided steps`}</span><ArrowRight size={18}/></div></Link>;})}</div>
   <details className="sim-coverage"><summary>54-requirement simulation index <ChevronDown size={16}/></summary><p>“Exercised” means a simulated response was produced, including expected rejection paths. It is not functional acceptance or proof of an external system.</p><div className="sim-coverage-grid">{Array.from({length:54},(_,i)=>i+1).map(n=>{const owner=scenarios.find(s=>s.steps.some(step=>step.requirements.includes(n)))!;return <Link key={n} href={`/operator/simulations/${owner.id}`} className={demonstrated.has(n)?'done':''}>{req(n)}<span>{demonstrated.has(n)?'Exercised':'Ready to simulate'}</span></Link>;})}</div></details>
  </>:<>
   <Link className="sim-back" href="/operator/simulations"><ArrowLeft size={15}/> All scenarios</Link>
   <section className="sim-heading"><div><span className="eyebrow">{scenario.chapter}</span><h2>{scenario.title}</h2><p>{scenario.summary}</p><div className="sim-chips">{ids.map(n=><span key={n}>{req(n)}</span>)}</div></div><Link className="button" href={`/operator/${scenario.workspace}`}>Open operational workspace <ArrowRight size={15}/></Link></section>
   <div className="sim-workbench"><aside className="sim-control-panel"><h3><Settings2 size={17}/> {run?'Next run settings':'Scenario settings'}</h3><p>Fictional inputs. Start a new run to apply changes; saved snapshots are preserved.</p><div className="sim-inputs">{scenario.fields.map(raw=>{const key=raw as keyof SimConfig,val=config[key];return <label key={key}>{labels[key]}{choices[key]?<select disabled={busy} value={String(val)} onChange={e=>setConfig({...config,[key]:e.target.value})}>{choices[key]!.map(option=><option key={option}>{option}</option>)}</select>:typeof val==='boolean'?<select disabled={busy} value={String(val)} onChange={e=>setConfig({...config,[key]:e.target.value==='true'})}><option value="true">Yes</option><option value="false">No</option></select>:<input disabled={busy} type={typeof val==='number'?'number':'text'} step="any" value={String(val)} onChange={e=>setConfig({...config,[key]:typeof val==='number'?Number(e.target.value):e.target.value})}/>}</label>;})}</div><button className="primary sim-start" disabled={busy||loading} onClick={()=>void start()}><Play size={16}/>{run?'Start a new run':'Start simulation'}</button>
   {runs.some(r=>r.scenarioId===scenario.id)&&<label className="sim-history-label">Saved runs<select aria-label="Saved simulation runs" disabled={busy} value={run?.id??''} onChange={e=>{const found=runs.find(r=>r.id===e.target.value);if(found){setRun(found);setConfig(found.config);setFocusEvent(null);}}}>{runs.filter(r=>r.scenarioId===scenario.id).map(r=><option key={r.id} value={r.id}>{new Date(r.createdAt).toLocaleString()} · {r.status.toLowerCase().replaceAll('_',' ')}</option>)}</select></label>}
   <p className="sim-small">Saved to the server under your operator login. Changes here never alter the operational demo database records.</p></aside>
   <section className="sim-stage">
    {!run?<div className="sim-empty"><Network size={52}/><h3>Ready when you are.</h3><p>Set the inputs, then step through the workflow. You can interrupt any handoff with a simulated failure and replay it safely.</p><div className="sim-route">{[...new Set(scenario.steps.map(s=>s.target))].map(target=><span key={target}>{target==='SOURCE'?'Supplier feed':target}</span>)}</div></div>:<>
    <div className="sim-run-bar"><div><span className={`badge ${run.status==='COMPLETED'?'green':run.status==='DEAD_LETTER'?'red':'amber'}`}>{run.status.replaceAll('_',' ')}</span><small>Run {run.id.slice(0,8)} · revision {run.version} · {run.config.market} · {run.config.locale.toUpperCase()}</small></div><span>{run.cursor} / {scenario.steps.length}</span></div>
    <div className="sim-progress"><div style={{width:`${run.cursor/scenario.steps.length*100}%`}}/></div>
    <div className="sim-current"><span className="eyebrow">{run.status==='COMPLETED'?'SCENARIO COMPLETE':run.status==='DEAD_LETTER'?'RECOVERY REQUIRED':`NEXT · ${activeStep?.actor}`}</span><h3>{run.status==='COMPLETED'?'Your evidence is ready.':activeStep?.title}</h3><p>{run.status==='COMPLETED'?'Review the simulated outcomes, inspect receipts or export this run for your stakeholder discussion.':activeStep?.description}</p><div className="sim-actions">{run.status==='DEAD_LETTER'?<button disabled={busy} className="primary" onClick={()=>void command('retry')}><RotateCcw size={16}/> Replay failed handoff</button>:run.status!=='COMPLETED'&&<><button disabled={busy} className="primary" onClick={()=>void command('next')}><ArrowRight size={16}/> Next step</button><button disabled={busy} className="button" onClick={()=>void command('next',true)}><Play size={15}/> Run remaining steps</button><button disabled={busy} className="button sim-danger" onClick={()=>void command('fail')}><AlertTriangle size={15}/> Fail next handoff</button></>}{busy&&<button className="button" onClick={()=>{stop.current=true;}}><Square size={14}/> Stop after this step</button>}{run.events.some(e=>e.status==='ACKNOWLEDGED')&&<button disabled={busy} className="button" onClick={()=>void command('duplicate')}><Copy size={14}/> Replay duplicate</button>}</div><span className="sim-small" role="status">{busy?'Saving the next simulated receipt…':run.status==='DEAD_LETTER'?'No business facts were changed by this failure. Replay uses the same idempotency key.':'No live calls. Every acknowledged step is saved.'}</span></div>
    <div className="sim-tabs" role="tablist" aria-label="Simulation evidence">{[['outcome','Outcomes'],['trace','Integration trace'],['steps','Workflow'],['snapshot','Run inputs']].map(([key,label])=><button role="tab" aria-selected={tab===key} key={key} onClick={()=>setTab(key)}>{label}{key==='trace'&&<span>{run.events.length}</span>}</button>)}</div>
    <div className="sim-tab-panel" role="tabpanel">
     {tab==='outcome'&&<><div className="sim-result-head"><h4>{event?scenario.steps.find(s=>s.id===event.stepId)?.title:'Scenario context'}</h4><span className="sim-tag">SIMULATED RESULT</span></div>{scenario.id==='media-studio'&&event?.response.imageOutput&&<div className="sim-image-preview"><img src={String(event.response.imageOutput)} alt="Bundled product illustration used as a simulated creative job output"/><p>Bundled sample output<br/>Not newly generated imagery</p></div>}<FactsView facts={event?.response??run.facts}/><details className="sim-details"><summary>All accumulated scenario facts</summary><FactsView facts={run.facts}/></details></>}
     {tab==='trace'&&<div className="sim-trace">{run.events.length===0?<p>No messages yet. Execute the first step to see its request and response.</p>:[...run.events].reverse().map(e=><details key={e.id} className={`sim-message ${e.status==='DEAD_LETTER'?'failed':''}`}><summary><span className="sim-message-icon">{e.status==='DEAD_LETTER'?<AlertTriangle size={17}/>:e.status==='DUPLICATE_IGNORED'?<Copy size={17}/>:<CheckCircle2 size={17}/>}</span><span><b>{e.actor} → {e.target}</b><small>{e.operation} · attempt {e.attempt}</small></span><span className="sim-message-status">{e.status.replaceAll('_',' ')}</span></summary><div className="sim-message-detail"><p><b>Idempotency key</b><br/>{e.idempotencyKey}</p><p><b>Receipt time</b> {new Date(e.at).toLocaleString()}</p><div className="sim-payloads"><div><h5>Request fixture</h5><pre>{JSON.stringify(e.request,null,2)}</pre></div><div><h5>Response fixture</h5><pre>{JSON.stringify(e.response,null,2)}</pre></div></div></div></details>)}</div>}
     {tab==='steps'&&<ol className="sim-step-list">{scenario.steps.map((step,i)=>{const receipt=run.events.find(e=>e.stepId===step.id&&e.status==='ACKNOWLEDGED');return <li key={step.id} className={i<run.cursor?'done':i===run.cursor?'current':''}><span>{i<run.cursor?<CheckCircle2 size={19}/>:String(i+1).padStart(2,'0')}</span><div><b>{step.title}</b><p>{step.description}</p><small>{step.actor} → {step.target} · {step.requirements.map(req).join(', ')}</small></div>{receipt&&<button className="text-button" onClick={()=>{setFocusEvent(receipt.id);setTab('outcome');}}>Inspect</button>}</li>;})}</ol>}
     {tab==='snapshot'&&<><p>These inputs are pinned to this run. Editing the settings panel affects only a new run.</p><FactsView facts={Object.fromEntries(scenario.fields.map(f=>[f,run.config[f as keyof SimConfig]]))}/></>}
    </div><div className="sim-export"><button className="button" onClick={()=>download(`SIMULATION-${scenario.id}-${run.id.slice(0,8)}.json`,JSON.stringify({disclosure:simulationNotice,scenario:scenario.title,requirements:ids,run},null,2))}><Download size={15}/> Export run evidence</button><button className="button" onClick={()=>window.print()}><Printer size={15}/> Print demo evidence / Save PDF</button><span><Clock3 size={13}/> Saved {new Date(run.updatedAt).toLocaleTimeString()}</span></div>
    <div className="sim-print-document"><h2>SIMULATION — NOT A COMMERCIAL DOCUMENT</h2><h3>{scenario.title}</h3><p>{simulationNotice}</p><p>Run {run.id} · {run.updatedAt}</p><FactsView facts={run.facts}/></div>
    </>}
   </section></div>
  </>}
 </div>;
}
