'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Clock3,RefreshCw,Search,Settings2,ShieldCheck} from 'lucide-react';
import {api,type User} from '../lib/api';
import {SlaPanel} from './sla-panel';
type Policy={stage:string;version:number;durationMinutes:number;warningMinutes:number;source:string};
type Row={id:string;entityId:string;entityType:'SHIPMENT'|'RETURN';stage:string;status:string;version:number;partnerName:string;deadline:string;breachedAt:string|null;origin:string};
type Queue={now:string;page:number;limit:number;total:number;metrics:{onTrack:number;atRisk:number;breached:number;waived:number;resolved:number;breachedEver:number};items:Row[]};
const label=(s:string)=>s.replaceAll('_',' ').toLowerCase();
const date=(s:string)=>new Date(s).toLocaleString('en-GB',{timeZone:'Asia/Dubai'});
export function SlaCenter({user,root,refreshToken}:{user:User;root:string;refreshToken:number}){
 const[tab,setTab]=useState('queue'),[market,setMarket]=useState(user.markets[0]??''),[status,setStatus]=useState('ACTIONABLE'),[stage,setStage]=useState(''),[kind,setKind]=useState(''),[page,setPage]=useState(1),[search,setSearch]=useState(''),[query,setQuery]=useState('');
 const[data,setData]=useState<Queue|null>(null),[policies,setPolicies]=useState<Policy[]>([]),[selected,setSelected]=useState<Row|null>(null),[editing,setEditing]=useState<Policy|null>(null),[duration,setDuration]=useState(''),[warning,setWarning]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const operator=['ATI_SUPER_ADMIN','ATI_OPERATIONS_MANAGER'].includes(user.role),canEdit=user.role==='ATI_SUPER_ADMIN';
 const[advanceMinutes,setAdvanceMinutes]=useState('15');
 async function load(){setError('');try{const params=new URLSearchParams({market,status,page:String(page),limit:'20',q:query,...(stage?{stage}:{}),...(kind?{entityType:kind}:{})});const [queue,p]=await Promise.all([api<Queue>(`/slas/queue?${params}`),api<{items:Policy[]}>(`/slas/policies?market=${market}`)]);setData(queue);setPolicies(p.items);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[market,status,stage,kind,page,query,refreshToken]);
 function edit(p:Policy){setEditing(p);setDuration(String(p.durationMinutes));setWarning(String(p.warningMinutes));setReason('');setNotice('');}
 async function save(){if(!editing)return;setBusy(true);setError('');try{const result=await api<Policy>('/slas/policies',{market,stage:editing.stage,expectedVersion:editing.version,durationMinutes:Number(duration),warningMinutes:Number(warning),reason});setNotice(`${label(result.stage)} policy v${result.version} saved for ${market}. Existing milestones keep their deadlines.`);setEditing(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const detail=(r:Row)=>`${root}/${r.entityType==='SHIPMENT'?'orders':'returns'}/${r.entityId}`;
 async function advanceClock(){setBusy(true);setError('');try{const result=await api<{now:string}>('/demo/clock',{minutes:Number(advanceMinutes)});setNotice(`Global demo clock advanced to ${date(result.now)} GST. All active milestones were evaluated.`);setSelected(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="operations sla-center"><div className="flow-banner"><Clock3 size={32}/><div><span className="eyebrow">{operator?'ATI & PARTNER OPERATIONS':'YOUR PARTNER OPERATIONS'}</span><h2>Keep every handoff on time.</h2><p>Review warnings, resolve breaches and preserve the evidence behind every exception.</p></div><button className="button" onClick={()=>void load()}><RefreshCw size={15}/> Refresh SLA workspace</button></div>
 {error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="success-note" role="status">{notice}</div>}
 {canEdit&&<details className="panel sla-presenter"><summary>Local presenter controls · demo clock</summary><p>This advances time for the entire local demo, including SLAs, brand rights and stock freshness. It cannot rewind time and sends no real customer messages.</p><form onSubmit={e=>{e.preventDefault();void advanceClock();}}><label>Advance global demo clock (minutes)<input type="number" min={1} max={240} step={1} value={advanceMinutes} onChange={e=>setAdvanceMinutes(e.target.value)} required/></label><button className="button" disabled={busy}>Advance demo clock</button></form></details>}
 <section className="panel sla-center-controls"><div className="order-tabs"><button className={tab==='queue'?'selected':''} onClick={()=>setTab('queue')}>Exception queue</button><button className={tab==='policies'?'selected':''} onClick={()=>{setTab('policies');setSelected(null);}}><Settings2 size={15}/> Stage policies</button></div><label>Market<select aria-label="SLA market" value={market} disabled={busy} onChange={e=>{setMarket(e.target.value);setPage(1);setSelected(null);setEditing(null);}}>{user.markets.map(m=><option key={m}>{m}</option>)}</select></label><p className="footnote">{data?`Demo clock: ${date(data.now)} GST. `:''}Persisted monitor evidence · Refreshed by worker about every 10 seconds · No external notifications sent.</p></section>
 {tab==='queue'&&<>{data&&<div className="metrics sla-metrics">{[[data.metrics.atRisk,'At risk'],[data.metrics.breached,'Open breaches'],[data.metrics.waived,'Waived milestones'],[data.metrics.breachedEver,'Ever breached']].map(([v,l])=><div className="metric" key={l}><span>{l}</span><strong>{v}</strong><small>Matching market, type, stage and search</small></div>)}</div>}
 <section className="panel data-panel"><div className="sla-filters"><label>State<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);setSelected(null);}}>{['ACTIONABLE','ALL','ON_TRACK','AT_RISK','BREACHED','WAIVED','RESOLVED'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>Entity<select value={kind} onChange={e=>{setKind(e.target.value);setPage(1);setSelected(null);}}><option value="">All workflows</option><option value="SHIPMENT">Shipments</option><option value="RETURN">Returns</option></select></label><label>Stage<select value={stage} onChange={e=>{setStage(e.target.value);setPage(1);setSelected(null);}}><option value="">All stages</option>{policies.map(p=><option value={p.stage} key={p.stage}>{label(p.stage)}</option>)}</select></label><form onSubmit={e=>{e.preventDefault();setQuery(search);setPage(1);setSelected(null);}}><label>Partner or entity reference<input maxLength={100} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Partner name or reference"/></label><button className="button" aria-label="Search SLA queue"><Search size={15}/></button></form></div>
 <div className="sla-table-scroll"><table><thead><tr>{['Partner / workflow','Stage','Deadline · GST','State',''].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data?.items.map(r=><tr key={r.id}><td><b>{r.partnerName}</b><small>{label(r.entityType)} · {r.entityId.slice(-12)}</small></td><td className="sla-stage-label">{label(r.stage)}<small>{r.origin==='LEGACY_OBSERVED'?'Legacy observation':'Event-based'}</small></td><td>{date(r.deadline)}{r.breachedAt&&<small className="sla-breach">Breach retained in history</small>}</td><td><span className={`badge ${r.status==='BREACHED'?'red':r.status==='AT_RISK'?'amber':r.status==='RESOLVED'?'green':''}`}>{label(r.status)}</span></td><td><button className="text-button" onClick={()=>setSelected(r)}>Review evidence →</button></td></tr>)}</tbody></table></div>
 {data&&!data.items.length&&<div className="empty"><ShieldCheck size={36}/><h3>No milestones match this view</h3><p>Choose “All” to see tracked stages. An empty actionable queue does not prove compliance for untracked historical records.</p><button className="button" onClick={()=>{setStatus('ALL');setStage('');setKind('');setQuery('');setSearch('');setPage(1);}}>Show all tracked milestones</button></div>}
 {data&&<div className="sla-pagination"><span>{data.total} matching milestones · Page {page} of {Math.max(1,Math.ceil(data.total/20))}</span><button className="button" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="button" disabled={page*20>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div>}</section>
 {selected&&<div className="sla-review"><div className="operations-toolbar"><b>{selected.partnerName} · {label(selected.entityType)}</b><Link className="text-button" href={detail(selected)}>Open workflow →</Link><button className="button" onClick={()=>setSelected(null)}>Close review</button></div><SlaPanel key={selected.id} entityType={selected.entityType} entityId={selected.entityId} revision={selected.version} operator={operator} onChanged={load}/></div>}</>}
 {tab==='policies'&&<><section className="panel sla-policy-list"><h3>Stage policies · {market}</h3><p>Company-wide baselines for new milestones in this market. Changes are versioned and audited. Existing stage timers are never recalculated.</p>{!canEdit&&<p className="footnote">Read-only for your role. ATI administrators manage the policy; operations managers can review and waive individual exceptions.</p>}<div className="sla-table-scroll"><table><thead><tr>{['Stage','Duration','Warn before deadline','Version',''].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{policies.map(p=><tr key={p.stage}><td className="sla-stage-label"><b>{label(p.stage)}</b></td><td>{p.durationMinutes} min</td><td>{p.warningMinutes} min</td><td>{p.version===0?'Demo default':`v${p.version}`}</td><td>{canEdit&&<button className="text-button" disabled={busy} onClick={()=>edit(p)}>Edit policy →</button>}</td></tr>)}</tbody></table></div></section>
 {editing&&<form className="panel sla-policy-editor" onSubmit={e=>{e.preventDefault();void save();}}><h3>Edit {label(editing.stage)} · {market}</h3><p>Saving replaces the market baseline for future milestones. Current deadlines stay unchanged. These are local demo policies, not contractual Fynd commitments.</p><div className="sla-policy-inputs"><label>Stage duration (minutes)<input type="number" min={2} max={43200} step={1} required value={duration} onChange={e=>setDuration(e.target.value)}/></label><label>Warning before deadline (minutes)<input type="number" min={1} max={Math.max(1,Number(duration)-1)} step={1} required value={warning} onChange={e=>setWarning(e.target.value)}/></label></div><label>Policy change justification<textarea required minLength={10} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain the operational change and scope"/></label><div className="decision-actions"><button className="primary" disabled={busy||reason.trim().length<10}>Save policy revision</button><button type="button" className="button" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button></div></form>}</>}
 </div>;
}
