'use client';
import {useEffect,useState} from 'react';
import {api} from '../lib/api';
type Job={id:string;target:string;operation:string;status:string;attempts:number;error:string|null;correlationId:string;createdAt:string};
const actions:Record<string,string>={provisionMapping:'Register a brand or location',upsertVendor:'Register the partner business',upsertProduct:'Publish product details',publishStorefront:'Refresh customer product preview',syncInventory:'Update available stock',createOrder:'Receive an order',createShipment:'Create a delivery',transitionShipment:'Update delivery progress',shipmentStatus:'Tell the storefront about delivery progress',createPickTask:'Ask the warehouse to pick items',createReturn:'Register a return',bookReturnPickup:'Arrange a return collection',requestRefund:'Request a customer refund',refreshAvailability:'Refresh selling availability',launchOrderStep:'Check a safe launch-order step'};
const states:Record<string,string>={SUCCEEDED:'Completed',PENDING:'Waiting',PROCESSING:'In progress',RETRY:'Will try again',DEAD_LETTER:'Needs attention',FAILED:'Needs attention',SUPERSEDED:'Replaced by a newer update'};
export function SystemUpdates({query,refreshToken}:{query:string;refreshToken:number}){
 const[items,setItems]=useState<Job[]>([]),[page,setPage]=useState(1),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reasons,setReasons]=useState<Record<string,string>>({});
 async function load(){setBusy(true);try{const r=await api<{items:Job[]}>(`/integrations/jobs?limit=50&page=${page}`);setItems(r.items);setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void load();},[page,refreshToken]);
 const filtered=items.filter(j=>`${j.target} ${j.operation} ${actions[j.operation]??''} ${states[j.status]} ${j.correlationId}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="panel system-updates"><h2>Updates between systems</h2><p>These are simulated updates, not live Fynd or storefront activity. Start with anything marked “Needs attention”. Several updates can belong to one order.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="coach-summary"><div><dt>Showing this page</dt><dd>{items.length} updates</dd></div><div><dt>Need attention on this page</dt><dd>{items.filter(j=>['FAILED','DEAD_LETTER','RETRY'].includes(j.status)).length}</dd></div></div>
 {filtered.map(j=><details className="coach-history" key={j.id}><summary><b>{states[j.status]??j.status}</b> · {actions[j.operation]??j.operation.replace(/([A-Z])/g,' $1')} · {j.target} simulator</summary><p>{new Date(j.createdAt).toLocaleString()} · {j.attempts} processing {j.attempts===1?'attempt':'attempts'}</p>{j.error&&<p className="error">{j.error}</p>}<p>Full activity reference: <code>{j.correlationId}</code></p><p>Update reference: <code>{j.id}</code></p>{['DEAD_LETTER','RETRY'].includes(j.status)&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api(`/integrations/jobs/${j.id}/replay`,{reason:reasons[j.id]});await load();}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><label>Why are you trying this update again?<input required minLength={5} value={reasons[j.id]??''} onChange={e=>setReasons({...reasons,[j.id]:e.target.value})}/></label><button className="button" disabled={busy}>Try this update again</button></form>}<details><summary>Technical details</summary><p>{j.target} / {j.operation} / {j.status}</p></details></details>)}{!filtered.length&&<p>{query?'No updates match on this page. Clear the search or check another page.':'No updates on this page.'}</p>}
 <div className="coach-actions"><button className="button" disabled={busy||page<=1} onClick={()=>setPage(p=>p-1)}>Previous page</button><span>Page {page}. Search applies to the 50 most recent updates on this page.</span><button className="button" disabled={busy||items.length<50} onClick={()=>setPage(p=>p+1)}>Next page</button></div></section>;
}
